-- Święta narodowe wpływające na turystykę (MM-DD w roku 2000 = szablon recurring)

insert into country_holidays (country_code, holiday_date, holiday_name_pl, impact, severity) values
  ('PT', '2000-01-01', 'Nowy Rok', 'Wszystko zamknięte', 'warning'),
  ('PT', '2000-04-25', 'Dzień Wolności', 'Wiele atrakcji zamkniętych, procesje', 'info'),
  ('PT', '2000-05-01', 'Święto Pracy', 'Wszystko zamknięte', 'warning'),
  ('PT', '2000-06-10', 'Dzień Portugalii', 'Procesje, ograniczone godziny', 'info'),
  ('PT', '2000-08-15', 'Wniebowzięcie NMP', 'Większość atrakcji zamknięta, kościelne procesje', 'warning'),
  ('PT', '2000-10-05', 'Dzień Republiki', 'Wiele atrakcji zamkniętych', 'info'),
  ('PT', '2000-12-08', 'Niepokalane Poczęcie', 'Wiele atrakcji zamkniętych', 'info'),
  ('PT', '2000-12-25', 'Boże Narodzenie', 'Wszystko zamknięte', 'critical'),
  ('PT', '2000-12-26', 'Drugi dzień świąt', 'Wiele zamknięte', 'warning'),
  ('ES', '2000-01-01', 'Nowy Rok', 'Wszystko zamknięte', 'warning'),
  ('ES', '2000-01-06', 'Trzech Króli', 'Wiele atrakcji zamkniętych, parady', 'warning'),
  ('ES', '2000-05-01', 'Święto Pracy', 'Wszystko zamknięte', 'warning'),
  ('ES', '2000-08-15', 'Wniebowzięcie NMP', 'Atrakcje zamknięte, ferias lokalne', 'warning'),
  ('ES', '2000-10-12', 'Dzień Hiszpanii', 'Wiele atrakcji zamkniętych', 'info'),
  ('ES', '2000-11-01', 'Wszystkich Świętych', 'Wiele atrakcji zamkniętych', 'info'),
  ('ES', '2000-12-06', 'Dzień Konstytucji', 'Wiele zamknięte', 'info'),
  ('ES', '2000-12-08', 'Niepokalane Poczęcie', 'Wiele zamknięte', 'info'),
  ('ES', '2000-12-25', 'Boże Narodzenie', 'Wszystko zamknięte', 'critical'),
  ('IT', '2000-01-01', 'Nowy Rok', 'Wszystko zamknięte', 'warning'),
  ('IT', '2000-01-06', 'Trzech Króli', 'Wiele zamknięte', 'warning'),
  ('IT', '2000-04-25', 'Dzień Wyzwolenia', 'Wiele zamknięte', 'info'),
  ('IT', '2000-05-01', 'Święto Pracy', 'Wszystko zamknięte', 'warning'),
  ('IT', '2000-06-02', 'Dzień Republiki', 'Wiele zamknięte', 'info'),
  ('IT', '2000-08-15', 'Ferragosto', 'Krytyczne - wszystko zamknięte, sklepy też', 'critical'),
  ('IT', '2000-11-01', 'Wszystkich Świętych', 'Wiele zamknięte', 'info'),
  ('IT', '2000-12-08', 'Niepokalane Poczęcie', 'Wiele zamknięte', 'info'),
  ('IT', '2000-12-25', 'Boże Narodzenie', 'Wszystko zamknięte', 'critical'),
  ('IT', '2000-12-26', 'Św. Szczepana', 'Wiele zamknięte', 'warning'),
  ('GR', '2000-01-01', 'Nowy Rok', 'Wszystko zamknięte', 'warning'),
  ('GR', '2000-01-06', 'Trzech Króli (prawosławie)', 'Procesje, ograniczone godziny', 'info'),
  ('GR', '2000-03-25', 'Dzień Niepodległości', 'Wiele zamknięte, parady', 'warning'),
  ('GR', '2000-05-01', 'Święto Pracy', 'Wszystko zamknięte', 'warning'),
  ('GR', '2000-08-15', 'Wniebowzięcie NMP (prawosławie)', 'Bardzo zatłoczone wyspy, ferie krajowe', 'critical'),
  ('GR', '2000-10-28', 'Ohi Day', 'Wiele zamknięte, parady', 'info'),
  ('GR', '2000-12-25', 'Boże Narodzenie', 'Wszystko zamknięte', 'critical'),
  ('AL', '2000-01-01', 'Nowy Rok', 'Wszystko zamknięte', 'warning'),
  ('AL', '2000-03-22', 'Dita e Verës (Dzień Lata)', 'Lokalne festiwale w Elbasan', 'info'),
  ('AL', '2000-05-01', 'Święto Pracy', 'Wszystko zamknięte', 'warning'),
  ('AL', '2000-11-28', 'Dzień Niepodległości', 'Wiele zamknięte', 'warning'),
  ('AL', '2000-11-29', 'Dzień Wyzwolenia', 'Wiele zamknięte', 'info'),
  ('AL', '2000-12-25', 'Boże Narodzenie', 'Formalne święto, mniejszy wpływ niż w UE', 'info'),
  ('MA', '2000-01-01', 'Nowy Rok', 'Zamknięte sklepy', 'info'),
  ('MA', '2000-01-11', 'Dzień Manifestu Niepodległości', 'Państwowe święto', 'info'),
  ('MA', '2000-05-01', 'Święto Pracy', 'Wszystko zamknięte', 'warning'),
  ('MA', '2000-07-30', 'Święto Tronu', 'Państwowe święto', 'info'),
  ('MA', '2000-11-06', 'Marsz Zielony', 'Wiele zamknięte', 'info'),
  ('MA', '2000-11-18', 'Dzień Niepodległości', 'Wiele zamknięte', 'warning');
