import type { DestinationSuggestion } from "./catalog";

/** Kompaktowe wyspy — szybszy próg „cała wyspa” na kroku zakresu. */
const COMPACT: DestinationSuggestion["islandProfile"] = {
  wholeWithBeachDays: 5,
  wholeSightseeingDays: 4,
  kidsExtraDays: 1,
};

/** Huby Canarias z regularnymi lotami z Europy — małe wyspy nie mają bezpośrednich połączeń z PL. */
const CANARY_GATEWAY_AIRPORTS = ["TFS", "TFN", "LPA"] as const;

/**
 * Wyspy z regionami turystycznymi w seedach, których brakowało w głównym katalogu.
 * Uzupełnia DESTINATION_CATALOG (islandBbox + lotniska).
 */
export const ISLAND_CATALOG_ENTRIES: DestinationSuggestion[] = [
  // —— Hiszpania: Baleares ——
  {
    name: "Ibiza",
    country: "Hiszpania",
    aliases: ["ibiza", "eivissa", "baleares", "balearic"],
    geocodeQuery: "Ibiza, Spain",
    lat: 38.9067,
    lon: 1.4206,
    islandBbox: { north: 39.12, south: 38.85, east: 1.65, west: 1.2 },
    primaryAirports: ["IBZ"],
    islandProfile: COMPACT,
  },
  {
    name: "Menorca",
    country: "Hiszpania",
    aliases: ["menorca", "minorca", "mahon", "maó", "baleares"],
    geocodeQuery: "Menorca, Spain",
    lat: 39.9695,
    lon: 4.0816,
    islandBbox: { north: 40.1, south: 39.84, east: 4.35, west: 3.77 },
    primaryAirports: ["MAH"],
    islandProfile: COMPACT,
  },
  {
    name: "Formentera",
    country: "Hiszpania",
    aliases: ["formentera", "baleares"],
    geocodeQuery: "Formentera, Spain",
    lat: 38.705,
    lon: 1.429,
    islandBbox: { north: 38.78, south: 38.65, east: 1.55, west: 1.3 },
    islandProfile: COMPACT,
  },
  // —— Hiszpania: Canarias ——
  {
    name: "La Palma",
    country: "Hiszpania",
    aliases: ["la palma", "canarias", "canary islands"],
    geocodeQuery: "La Palma, Canary Islands",
    lat: 28.6835,
    lon: -17.7642,
    islandBbox: { north: 28.88, south: 28.52, east: -17.67, west: -18.01 },
    primaryAirports: ["SPC"],
    gatewayAirports: [...CANARY_GATEWAY_AIRPORTS],
    islandProfile: COMPACT,
  },
  {
    name: "La Gomera",
    country: "Hiszpania",
    aliases: ["la gomera", "san sebastian de la gomera", "canarias"],
    geocodeQuery: "La Gomera, Canary Islands",
    lat: 28.1235,
    lon: -17.237,
    islandBbox: { north: 28.23, south: 28.02, east: -17.07, west: -17.35 },
    primaryAirports: ["GMZ"],
    gatewayAirports: [...CANARY_GATEWAY_AIRPORTS],
    islandProfile: COMPACT,
  },
  {
    name: "El Hierro",
    country: "Hiszpania",
    aliases: ["el hierro", "canarias"],
    geocodeQuery: "El Hierro, Canary Islands",
    lat: 27.735,
    lon: -18.033,
    islandBbox: { north: 27.86, south: 27.62, east: -17.89, west: -18.18 },
    primaryAirports: ["VDE"],
    gatewayAirports: [...CANARY_GATEWAY_AIRPORTS],
    islandProfile: COMPACT,
  },
  // —— Grecja: Cyklady ——
  {
    name: "Mykonos",
    country: "Grecja",
    aliases: ["mykonos", "mikonos", "kyklady", "cyclades"],
    geocodeQuery: "Mykonos, Greece",
    lat: 37.4467,
    lon: 25.3289,
    islandBbox: { north: 37.47, south: 37.4, east: 25.42, west: 25.3 },
    primaryAirports: ["JMK"],
    islandProfile: COMPACT,
  },
  {
    name: "Naxos",
    country: "Grecja",
    aliases: ["naxos", "naksos", "kyklady", "cyclades"],
    geocodeQuery: "Naxos, Greece",
    lat: 37.1036,
    lon: 25.3764,
    islandBbox: { north: 37.12, south: 36.98, east: 25.58, west: 25.35 },
    primaryAirports: ["JNX"],
    islandProfile: COMPACT,
  },
  {
    name: "Paros",
    country: "Grecja",
    aliases: ["paros", "paros island", "kyklady", "cyclades"],
    geocodeQuery: "Paros, Greece",
    lat: 37.0853,
    lon: 25.152,
    islandBbox: { north: 37.13, south: 36.97, east: 25.3, west: 25.08 },
    primaryAirports: ["PAS"],
    islandProfile: COMPACT,
  },
  {
    name: "Milos",
    country: "Grecja",
    aliases: ["milos", "kyklady", "cyclades"],
    geocodeQuery: "Milos, Greece",
    lat: 36.7489,
    lon: 24.426,
    islandBbox: { north: 36.78, south: 36.68, east: 24.52, west: 24.32 },
    primaryAirports: ["MLO"],
    islandProfile: COMPACT,
  },
  {
    name: "Tinos",
    country: "Grecja",
    aliases: ["tinos", "kyklady", "cyclades"],
    geocodeQuery: "Tinos, Greece",
    lat: 37.583,
    lon: 25.12,
    islandBbox: { north: 37.62, south: 37.52, east: 25.22, west: 25.02 },
    islandProfile: COMPACT,
  },
  {
    name: "Andros",
    country: "Grecja",
    aliases: ["andros", "kyklady", "cyclades"],
    geocodeQuery: "Andros, Greece",
    lat: 37.86,
    lon: 24.9,
    islandBbox: { north: 37.92, south: 37.78, east: 25.02, west: 24.72 },
    islandProfile: COMPACT,
  },
  {
    name: "Sifnos",
    country: "Grecja",
    aliases: ["sifnos", "kyklady", "cyclades"],
    geocodeQuery: "Sifnos, Greece",
    lat: 36.975,
    lon: 24.725,
    islandBbox: { north: 37.02, south: 36.92, east: 24.78, west: 24.65 },
    islandProfile: COMPACT,
  },
  {
    name: "Ios",
    country: "Grecja",
    aliases: ["ios", "kyklady", "cyclades"],
    geocodeQuery: "Ios, Greece",
    lat: 36.723,
    lon: 25.282,
    islandBbox: { north: 36.75, south: 36.68, east: 25.32, west: 25.24 },
    islandProfile: COMPACT,
  },
  {
    name: "Amorgos",
    country: "Grecja",
    aliases: ["amorgos", "kyklady", "cyclades"],
    geocodeQuery: "Amorgos, Greece",
    lat: 36.833,
    lon: 25.898,
    islandBbox: { north: 36.88, south: 36.78, east: 25.98, west: 25.78 },
    islandProfile: COMPACT,
  },
  {
    name: "Syros",
    country: "Grecja",
    aliases: ["syros", "siros", "kyklady", "cyclades"],
    geocodeQuery: "Syros, Greece",
    lat: 37.45,
    lon: 24.917,
    islandBbox: { north: 37.48, south: 37.4, east: 25.02, west: 24.82 },
    primaryAirports: ["JSY"],
    islandProfile: COMPACT,
  },
  // —— Grecja: Sporady ——
  {
    name: "Skiathos",
    country: "Grecja",
    aliases: ["skiathos", "sporades", "sporady"],
    geocodeQuery: "Skiathos, Greece",
    lat: 39.162,
    lon: 23.489,
    islandBbox: { north: 39.2, south: 39.12, east: 23.55, west: 23.42 },
    primaryAirports: ["JSI"],
    islandProfile: COMPACT,
  },
  {
    name: "Skopelos",
    country: "Grecja",
    aliases: ["skopelos", "sporades", "sporady"],
    geocodeQuery: "Skopelos, Greece",
    lat: 39.08,
    lon: 23.72,
    islandBbox: { north: 39.17, south: 38.97, east: 23.72, west: 23.5 },
    islandProfile: COMPACT,
  },
  // —— Grecja: Wyspy Ioniańskie i inne ——
  {
    name: "Zakynthos",
    country: "Grecja",
    aliases: ["zakynthos", "zante", "zanthe", "wyspy jonskie", "ionian"],
    geocodeQuery: "Zakynthos, Greece",
    lat: 37.787,
    lon: 20.898,
    islandBbox: { north: 37.88, south: 37.68, east: 21.0, west: 20.75 },
    primaryAirports: ["ZTH"],
    islandProfile: COMPACT,
  },
  {
    name: "Kefalonia",
    country: "Grecja",
    aliases: ["kefalonia", "cephalonia", "kefallinia", "wyspy jonskie", "ionian"],
    geocodeQuery: "Kefalonia, Greece",
    lat: 38.175,
    lon: 20.565,
    islandBbox: { north: 38.35, south: 38.05, east: 20.85, west: 20.3 },
    primaryAirports: ["EFL"],
    islandProfile: COMPACT,
  },
  {
    name: "Lefkada",
    country: "Grecja",
    aliases: ["lefkada", "lefkas", "wyspy jonskie", "ionian"],
    geocodeQuery: "Lefkada, Greece",
    lat: 38.833,
    lon: 20.708,
    islandBbox: { north: 38.9, south: 38.6, east: 20.85, west: 20.55 },
    primaryAirports: ["PVK"],
    islandProfile: COMPACT,
  },
  {
    name: "Kos",
    country: "Grecja",
    aliases: ["kos", "dodecanese", "dodekanes"],
    geocodeQuery: "Kos, Greece",
    lat: 36.893,
    lon: 27.288,
    islandBbox: { north: 36.95, south: 36.72, east: 27.35, west: 26.95 },
    primaryAirports: ["KGS"],
    islandProfile: COMPACT,
  },
  {
    name: "Samos",
    country: "Grecja",
    aliases: ["samos", "pythagoreio"],
    geocodeQuery: "Samos, Greece",
    lat: 37.754,
    lon: 26.978,
    islandBbox: { north: 37.82, south: 37.67, east: 26.98, west: 26.55 },
    primaryAirports: ["SMI"],
    islandProfile: COMPACT,
  },
  {
    name: "Thasos",
    country: "Grecja",
    aliases: ["thasos", "thassos", "tasos"],
    geocodeQuery: "Thasos, Greece",
    lat: 40.686,
    lon: 24.653,
    islandBbox: { north: 40.78, south: 40.58, east: 24.75, west: 24.55 },
    islandProfile: COMPACT,
  },
  {
    name: "Hydra",
    country: "Grecja",
    aliases: ["hydra", "idra", "saronic", "sarony"],
    geocodeQuery: "Hydra, Greece",
    lat: 37.35,
    lon: 23.467,
    islandBbox: { north: 37.38, south: 37.32, east: 23.52, west: 23.42 },
    islandProfile: COMPACT,
  },
  {
    name: "Spetses",
    country: "Grecja",
    aliases: ["spetses", "spetsai", "saronic", "sarony"],
    geocodeQuery: "Spetses, Greece",
    lat: 37.262,
    lon: 23.152,
    islandBbox: { north: 37.28, south: 37.24, east: 23.2, west: 23.1 },
    islandProfile: COMPACT,
  },
  // —— Chorwacja: wyspy ——
  {
    name: "Krk",
    country: "Chorwacja",
    aliases: ["krk", "krk island", "malinska"],
    geocodeQuery: "Krk, Croatia",
    lat: 45.039,
    lon: 14.573,
    islandBbox: { north: 45.28, south: 45.0, east: 14.85, west: 14.49 },
    primaryAirports: ["RJK"],
    islandProfile: COMPACT,
  },
  {
    name: "Hvar",
    country: "Chorwacja",
    aliases: ["hvar", "hvar island", "stari grad"],
    geocodeQuery: "Hvar, Croatia",
    lat: 43.172,
    lon: 16.441,
    islandBbox: { north: 43.22, south: 43.1, east: 16.78, west: 16.48 },
    islandProfile: COMPACT,
  },
  {
    name: "Brač",
    country: "Chorwacja",
    aliases: ["brac", "brač", "bol", "supetar"],
    geocodeQuery: "Brac, Croatia",
    lat: 43.317,
    lon: 16.658,
    islandBbox: { north: 43.38, south: 43.28, east: 16.92, west: 16.48 },
    primaryAirports: ["BWK"],
    islandProfile: COMPACT,
  },
  {
    name: "Vis",
    country: "Chorwacja",
    aliases: ["vis", "vis island", "komiza", "komiža"],
    geocodeQuery: "Vis, Croatia",
    lat: 43.062,
    lon: 16.183,
    islandBbox: { north: 43.09, south: 43.02, east: 16.25, west: 16.08 },
    islandProfile: COMPACT,
  },
  {
    name: "Korčula",
    country: "Chorwacja",
    aliases: ["korcula", "korčula", "lumbarda"],
    geocodeQuery: "Korcula, Croatia",
    lat: 42.959,
    lon: 17.135,
    islandBbox: { north: 42.98, south: 42.88, east: 17.2, west: 16.95 },
    islandProfile: COMPACT,
  },
  {
    name: "Pag",
    country: "Chorwacja",
    aliases: ["pag", "pag island", "novalja"],
    geocodeQuery: "Pag, Croatia",
    lat: 44.442,
    lon: 15.058,
    islandBbox: { north: 44.52, south: 44.36, east: 15.18, west: 14.92 },
    islandProfile: COMPACT,
  },
  {
    name: "Mljet",
    country: "Chorwacja",
    aliases: ["mljet", "mljet island"],
    geocodeQuery: "Mljet, Croatia",
    lat: 42.744,
    lon: 17.362,
    islandBbox: { north: 42.82, south: 42.68, east: 17.48, west: 17.22 },
    islandProfile: COMPACT,
  },
  {
    name: "Rab",
    country: "Chorwacja",
    aliases: ["rab", "rab island", "lopar"],
    geocodeQuery: "Rab, Croatia",
    lat: 44.756,
    lon: 14.759,
    islandBbox: { north: 44.82, south: 44.72, east: 14.82, west: 14.72 },
    islandProfile: COMPACT,
  },
  // —— Portugalia: Azory ——
  {
    name: "São Miguel (Azory)",
    country: "Portugalia",
    aliases: ["azory", "azores", "sao miguel", "são miguel", "ponta delgada"],
    geocodeQuery: "São Miguel Island, Azores",
    lat: 37.741,
    lon: -25.675,
    islandBbox: { north: 37.92, south: 37.68, east: -25.05, west: -25.55 },
    primaryAirports: ["PDL"],
    islandProfile: { wholeWithBeachDays: 6, wholeSightseeingDays: 4, kidsExtraDays: 1 },
  },
  {
    name: "Faial (Azory)",
    country: "Portugalia",
    aliases: ["azory", "azores", "faial", "horta"],
    geocodeQuery: "Faial Island, Azores",
    lat: 38.534,
    lon: -28.713,
    islandBbox: { north: 38.62, south: 38.48, east: -28.58, west: -28.85 },
    primaryAirports: ["HOR"],
    islandProfile: COMPACT,
  },
  {
    name: "Terceira (Azory)",
    country: "Portugalia",
    aliases: ["azory", "azores", "terceira", "angra do heroismo", "angra"],
    geocodeQuery: "Terceira Island, Azores",
    lat: 38.718,
    lon: -27.22,
    islandBbox: { north: 38.82, south: 38.62, east: -27.02, west: -27.42 },
    primaryAirports: ["TER"],
    islandProfile: COMPACT,
  },
  // —— Włochy: wyspy ——
  {
    name: "Capri",
    country: "Włochy",
    aliases: ["capri", "anacapri"],
    geocodeQuery: "Capri, Italy",
    lat: 40.553,
    lon: 14.242,
    islandBbox: { north: 40.56, south: 40.53, east: 14.26, west: 14.22 },
    islandProfile: COMPACT,
  },
  {
    name: "Ischia",
    country: "Włochy",
    aliases: ["ischia", "forio", "casamicciola"],
    geocodeQuery: "Ischia, Italy",
    lat: 40.731,
    lon: 13.907,
    islandBbox: { north: 40.76, south: 40.68, east: 13.98, west: 13.85 },
    islandProfile: COMPACT,
  },
  {
    name: "Wyspy Eolskie",
    country: "Włochy",
    aliases: ["lipari", "aeolian", "eolie", "stromboli", "salina", "vulcano"],
    geocodeQuery: "Lipari, Aeolian Islands, Italy",
    lat: 38.467,
    lon: 14.954,
    islandBbox: { north: 38.55, south: 38.32, east: 15.05, west: 14.18 },
    islandProfile: COMPACT,
  },
  // —— Inne ——
  {
    name: "Gotlandia",
    country: "Szwecja",
    aliases: ["gotland", "visby", "gotlandia"],
    geocodeQuery: "Gotland, Sweden",
    lat: 57.634,
    lon: 18.294,
    islandBbox: { north: 57.95, south: 56.82, east: 19.25, west: 17.95 },
    primaryAirports: ["VBY"],
    islandProfile: { wholeWithBeachDays: 7, wholeSightseeingDays: 5, kidsExtraDays: 1 },
  },
  {
    name: "Djerba",
    country: "Tunezja",
    aliases: ["djerba", "jerba", "tunezja", "tunisia", "houmt souk"],
    geocodeQuery: "Djerba, Tunisia",
    lat: 33.875,
    lon: 10.908,
    islandBbox: { north: 33.92, south: 33.75, east: 11.05, west: 10.85 },
    primaryAirports: ["DJE"],
    islandProfile: COMPACT,
  },
];
