import type { TouristRegion } from "./tourist-regions";

/** Portugalia — dodatkowe regiony turystyczne (miasta, wybrzeże, interior). */
export const SEED_TOURIST_REGIONS_PORTUGAL: TouristRegion[] = [
  {
    id: "pt-coimbra-university",
    destination_keys: ["coimbra", "portugalia", "portugal"],
    slug: "coimbra-university",
    name_pl: "Coimbra — miasto uniwersyteckie",
    name_en: "Coimbra — university city",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Jedna z najstarszych uczelni Europy, Most Pedro i Miguel i brama do centrum Portugalii.",
    overview_en: "One of Europe's oldest universities, Pedro e Miguel bridge and gateway to central Portugal.",
    stay_hint_pl: "Alta lub Baixa — blisko uniwersytetu i rzeki Mondego.",
    stay_hint_en: "Alta or Baixa — near university and Mondego river.",
    center_lat: 40.21,
    center_lon: -8.43,
    picks: [
      { day_theme: "city_culture", name_pl: "Uniwersytet Coimbra", name_en: "University of Coimbra", why_pl: "Biblioteka Joanina i dziedziniec — UNESCO.", why_en: "Joanina Library and courtyard — UNESCO.", activity_slugs: ["museums", "old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Most Pedro e Miguel", name_en: "Pedro e Miguel bridge", why_pl: "Widok na rzekę Mondego — spacer wieczorem.", why_en: "Mondego river views — evening stroll.", activity_slugs: ["viewpoints", "old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Quinta das Lágrimas", name_en: "Quinta das Lágrimas", why_pl: "Legenda o księżnej Inês — ogrody nad wodą.", why_en: "Princess Inês legend — riverside gardens.", activity_slugs: ["old_towns"], rank: 2 },
    ],
  },
  {
    id: "pt-braga-minho",
    destination_keys: ["braga", "guimaraes", "minho", "portugalia", "portugal"],
    slug: "braga-minho",
    name_pl: "Braga i Guimarães",
    name_en: "Braga & Guimarães",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Sanktuarium Bom Jesus, stolica architektury barokowej i kolebka Portugalii w Guimarães.",
    overview_en: "Bom Jesus sanctuary, baroque architecture capital and Portugal's birthplace in Guimarães.",
    stay_hint_pl: "Braga centro — pociąg do Guimarães ok. 15 min.",
    stay_hint_en: "Braga centre — Guimarães ~15 min by train.",
    center_lat: 41.55,
    center_lon: -8.43,
    picks: [
      { day_theme: "city_culture", name_pl: "Bom Jesus do Monte", name_en: "Bom Jesus do Monte", why_pl: "Schody i widok na miasto — ikona północy.", why_en: "Staircase and city views — north icon.", activity_slugs: ["viewpoints", "old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Zamek Guimarães", name_en: "Guimarães Castle", why_pl: "Miejsce narodzin Portugalii — krótki dojazd.", why_en: "Birthplace of Portugal — short trip.", activity_slugs: ["castles", "old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Centrum Braga", name_en: "Braga old centre", why_pl: "Katedra i barokowe fasady — spacer 2 h.", why_en: "Cathedral and baroque façades — 2 h walk.", activity_slugs: ["old_towns"], rank: 1 },
    ],
  },
  {
    id: "pt-obidos-medieval",
    destination_keys: ["obidos", "portugalia", "portugal", "lisbon"],
    slug: "obidos-medieval",
    name_pl: "Óbidos — średniowieczne mury",
    name_en: "Óbidos — medieval walls",
    character: "historic",
    vibe: "popular",
    overview_pl: "Białe mury, ginjinha w czekoladzie i baśniowa wioska godzinę od Lizbony.",
    overview_en: "White walls, ginjinha in chocolate and fairytale town an hour from Lisbon.",
    stay_hint_pl: "Nocleg w obrębie murów — wieczór bez tłumów autobusów.",
    stay_hint_en: "Stay within the walls — evening without coach crowds.",
    center_lat: 39.36,
    center_lon: -9.16,
    picks: [
      { day_theme: "city_culture", name_pl: "Spacer po murach", name_en: "Wall walk", why_pl: "Obrona wioski z widokiem na okolicę.", why_en: "Fortified village walk with countryside views.", activity_slugs: ["old_towns", "castles"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Ginjinha w czekoladzie", name_en: "Ginjinha in chocolate cup", why_pl: "Lokalna tradycja — degustacja na rynku.", why_en: "Local tradition — tasting on the square.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Nazare (wycieczka)", name_en: "Nazare day trip", why_pl: "Wielkie fale i rybacka wioska — ok. 30 min.", why_en: "Big waves and fishing village — ~30 min.", activity_slugs: ["viewpoints", "old_towns"], rank: 2 },
    ],
  },
  {
    id: "pt-aveiro-canals",
    destination_keys: ["aveiro", "portugalia", "portugal"],
    slug: "aveiro-canals",
    name_pl: "Aveiro — Wenecja Portugalii",
    name_en: "Aveiro — Venice of Portugal",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Kanały, moliceiro i Costa Nova — kolorowe domy nad oceanem.",
    overview_en: "Canals, moliceiro boats and Costa Nova — colourful seaside houses.",
    stay_hint_pl: "Centrum Aveiro — rejs moliceiro i spacer po kanałach.",
    stay_hint_en: "Aveiro centre — moliceiro ride and canal stroll.",
    center_lat: 40.64,
    center_lon: -8.65,
    picks: [
      { day_theme: "city_culture", name_pl: "Rejs moliceiro", name_en: "Moliceiro boat ride", why_pl: "Kanały Aveiro — 45 min z przewodnikiem.", why_en: "Aveiro canals — 45 min guided ride.", activity_slugs: ["boat_tour", "old_towns"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Costa Nova", name_en: "Costa Nova beach", why_pl: "Pasiaste domy nad Atlantykiem — plaża obok.", why_en: "Striped houses by the Atlantic — beach beside.", activity_slugs: ["sandy_beaches", "viewpoints"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Ovos moles", name_en: "Ovos moles sweets", why_pl: "Lokalne słodycze — degustacja w centrum.", why_en: "Local sweets — tasting in centre.", activity_slugs: ["old_towns"], rank: 2 },
    ],
  },
  {
    id: "pt-faro-capital",
    destination_keys: ["faro", "algarve", "portugalia", "portugal"],
    slug: "faro-algarve-capital",
    name_pl: "Faro — stolica Algarve",
    name_en: "Faro — Algarve capital",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Stare Miasto za murami, Ria Formosa i lotnisko regionu — prawdziwe miasto, nie tylko resort.",
    overview_en: "Walled Old Town, Ria Formosa and regional airport — a real city, not just resorts.",
    stay_hint_pl: "Cidade Velha — blisko katedry i promenady.",
    stay_hint_en: "Cidade Velha — near cathedral and promenade.",
    center_lat: 37.02,
    center_lon: -7.93,
    picks: [
      { day_theme: "city_culture", name_pl: "Cidade Velha Faro", name_en: "Faro Old Town", why_pl: "Katedra i muzeum archeologiczne — spacer 2 h.", why_en: "Cathedral and archaeology museum — 2 h walk.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "nature", name_pl: "Ria Formosa", name_en: "Ria Formosa lagoon", why_pl: "Rezerwat ptaków i wyspy — rejs lub spacer.", why_en: "Bird reserve and islands — cruise or walk.", activity_slugs: ["national_parks", "boat_tour"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Ilha de Faro", name_en: "Ilha de Faro beach", why_pl: "Plaża na barierze — prom z centrum.", why_en: "Barrier island beach — ferry from centre.", activity_slugs: ["sandy_beaches"], rank: 1 },
    ],
  },
  {
    id: "pt-sagres-algarve-west",
    destination_keys: ["sagres", "algarve", "portimao", "portugalia", "portugal"],
    slug: "sagres-algarve-west",
    name_pl: "Sagres — koniec Europy",
    name_en: "Sagres — edge of Europe",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Przylądek św. Wincentego, forteca Henryka Nawigatora i dzikie wybrzeże zachodniego Algarve.",
    overview_en: "Cape St Vincent, Henry the Navigator fortress and wild west Algarve coast.",
    stay_hint_pl: "Sagres lub Vila do Bispo — blisko klifów i surfu.",
    stay_hint_en: "Sagres or Vila do Bispo — near cliffs and surf.",
    center_lat: 37.01,
    center_lon: -8.94,
    picks: [
      { day_theme: "nature", name_pl: "Cabo de São Vicente", name_en: "Cape St Vincent", why_pl: "Najbardziej wysunięty punkt kontynentu — zachód słońca.", why_en: "Continental Europe's southwestern tip — sunset.", activity_slugs: ["viewpoints"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Forteca Sagres", name_en: "Sagres fortress", why_pl: "Miejsce szkół nawigacyjnych — muzeum i widoki.", why_en: "Navigation school site — museum and views.", activity_slugs: ["castles", "archaeology"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Praia do Beliche", name_en: "Beliche beach", why_pl: "Ukryta plaża pod klifem — krótki spacer.", why_en: "Hidden cliff beach — short walk.", activity_slugs: ["rocky_beaches"], rank: 2 },
    ],
  },
  {
    id: "pt-evora-alentejo",
    destination_keys: ["evora", "alentejo", "portugalia", "portugal"],
    slug: "evora-alentejo",
    name_pl: "Évora — stolica Alentejo",
    name_en: "Évora — Alentejo capital",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Świątynia Diany, kaplica kości i białe ulice — UNESCO w sercu Alentejo.",
    overview_en: "Temple of Diana, bone chapel and white lanes — UNESCO heart of Alentejo.",
    stay_hint_pl: "Centrum w obrębie murów — wszystko w zasięgu spaceru.",
    stay_hint_en: "Centre within walls — everything walkable.",
    center_lat: 38.57,
    center_lon: -7.91,
    picks: [
      { day_theme: "city_culture", name_pl: "Świątynia Diany", name_en: "Temple of Diana", why_pl: "Rzymskie ruiny w centrum — krótka wizyta.", why_en: "Roman ruins in centre — short visit.", activity_slugs: ["archaeology", "old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Capela dos Ossos", name_en: "Bone Chapel", why_pl: "Kaplica z kości — niezapomniane wrażenie.", why_en: "Bone-lined chapel — unforgettable.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Monsaraz (wycieczka)", name_en: "Monsaraz day trip", why_pl: "Wioska na wzgórzu nad jeziorem — ok. 45 min.", why_en: "Hilltop village above lake — ~45 min.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "pt-tomar-templars",
    destination_keys: ["tomar", "portugalia", "portugal"],
    slug: "tomar-templars",
    name_pl: "Tomar — twierdza templariuszy",
    name_en: "Tomar — Templar stronghold",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Convento de Cristo UNESCO i miasto templariuszy nad rzeką Nabão.",
    overview_en: "UNESCO Convent of Christ and Templar town on the Nabão river.",
    stay_hint_pl: "Centrum Tomar — blisko convento i rzeki.",
    stay_hint_en: "Tomar centre — near convent and river.",
    center_lat: 39.6,
    center_lon: -8.41,
    picks: [
      { day_theme: "city_culture", name_pl: "Convento de Cristo", name_en: "Convent of Christ", why_pl: "Okrągła kaplica i ogrody — rezerwacja zalecana.", why_en: "Round chapel and gardens — booking recommended.", activity_slugs: ["castles", "old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Stare Miasto Tomar", name_en: "Tomar old town", why_pl: "Synagoga i most — spacer po kolacji.", why_en: "Synagogue and bridge — post-dinner stroll.", activity_slugs: ["old_towns", "archaeology"], rank: 1 },
      { day_theme: "nature", name_pl: "Castelo de Bode (wycieczka)", name_en: "Castelo de Bode lake", why_pl: "Jezioro i zapora — półdniowy wypad.", why_en: "Lake and dam — half-day trip.", activity_slugs: ["viewpoints", "boat_tour"], rank: 2 },
    ],
  },
  {
    id: "pt-peniche-atlantic",
    destination_keys: ["peniche", "portugalia", "portugal"],
    slug: "peniche-atlantic",
    name_pl: "Peniche — surf i wyspy",
    name_en: "Peniche — surf & islands",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Stolica surfingu w Europie, forteca i prom na Berlengas — Atlantyk w pełni.",
    overview_en: "European surf capital, fortress and Berlengas ferry — full Atlantic experience.",
    stay_hint_pl: "Peniche centro — blisko portu i plaż.",
    stay_hint_en: "Peniche centre — near harbour and beaches.",
    center_lat: 39.36,
    center_lon: -9.38,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Surf w Peniche", name_en: "Peniche surfing", why_pl: "Superbank i Supertubos — lekcje dla początkujących.", why_en: "Superbank and Supertubos — beginner lessons.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "nature", name_pl: "Berlengas (rejs)", name_en: "Berlengas islands", why_pl: "Rezerwat na wyspach — rezerwacja promu wcześnie.", why_en: "Island reserve — book ferry early.", activity_slugs: ["national_parks", "boat_tour"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Forteca Peniche", name_en: "Peniche fortress", why_pl: "Muzeum więzienia politycznego — historia XX w.", why_en: "Political prison museum — 20th-century history.", activity_slugs: ["castles", "museums"], rank: 2 },
    ],
  },
  {
    id: "pt-viana-castelo",
    destination_keys: ["viana do castelo", "minho", "portugalia", "portugal"],
    slug: "viana-castelo",
    name_pl: "Viana do Castelo",
    name_en: "Viana do Castelo",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Santuario Santa Luzia, rzeka Lima i plaże północy — brama do Minho.",
    overview_en: "Santa Luzia sanctuary, Lima river and northern beaches — Minho gateway.",
    stay_hint_pl: "Centrum nad rzeką — funicular na Santuario.",
    stay_hint_en: "Riverside centre — funicular to sanctuary.",
    center_lat: 41.69,
    center_lon: -8.83,
    picks: [
      { day_theme: "city_culture", name_pl: "Santuario de Santa Luzia", name_en: "Santa Luzia sanctuary", why_pl: "Widok na miasto i ocean — funicular lub schody.", why_en: "City and ocean views — funicular or stairs.", activity_slugs: ["viewpoints", "old_towns"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Praia do Cabedelo", name_en: "Cabedelo beach", why_pl: "Plaża u ujścia Lima — spacer z centrum.", why_en: "River-mouth beach — walk from centre.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Stare Miasto", name_en: "Historic centre", why_pl: "Renesansowe kamienice i ratusz — festiwal latem.", why_en: "Renaissance façades and town hall — summer festival.", activity_slugs: ["old_towns"], rank: 1 },
    ],
  },
  {
    id: "pt-braganca-tras-os-montes",
    destination_keys: ["braganca", "tras-os-montes", "portugalia", "portugal"],
    slug: "braganca-tras-os-montes",
    name_pl: "Bragança i Trás-os-Montes",
    name_en: "Bragança & Trás-os-Montes",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Cytadela na wzgórzu, parki narodowe i dzikie wnętrze północno-wschodniej Portugalii.",
    overview_en: "Hilltop citadel, national parks and wild northeast Portuguese interior.",
    stay_hint_pl: "Bragança centro — baza na Peneda-Gerês i Montesinho.",
    stay_hint_en: "Bragança centre — base for Peneda-Gerês and Montesinho.",
    center_lat: 41.81,
    center_lon: -6.76,
    picks: [
      { day_theme: "city_culture", name_pl: "Cytadela Bragança", name_en: "Bragança citadel", why_pl: "Dom i muzeum wojskowe w obrębie murów.", why_en: "Cathedral and military museum within walls.", activity_slugs: ["castles", "museums"], rank: 1 },
      { day_theme: "nature", name_pl: "Parque Montesinho", name_en: "Montesinho Natural Park", why_pl: "Wilki, wioski graniczne i szlaki — cały dzień.", why_en: "Wolves, border villages and trails — full day.", activity_slugs: ["national_parks", "hiking_trails"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Miranda do Douro", name_en: "Miranda do Douro", why_pl: "Wioska nad rzeką — fado transmontano.", why_en: "Riverside town — transmontano fado.", activity_slugs: ["old_towns"], rank: 2 },
    ],
  },
  {
    id: "pt-arrabida-setubal",
    destination_keys: ["setubal", "arrabida", "portugalia", "portugal", "lisbon"],
    slug: "arrabida-setubal",
    name_pl: "Arrábida i Setúbal",
    name_en: "Arrábida & Setúbal",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Park Arrábida, plaże ukryte w klifach i owoce morza w Setúbal — 40 min od Lizbony.",
    overview_en: "Arrábida park, cliff-hidden beaches and Setúbal seafood — 40 min from Lisbon.",
    stay_hint_pl: "Setúbal centro — prom do Troii lub auto do plaż Arrábida.",
    stay_hint_en: "Setúbal centre — Troia ferry or drive to Arrábida beaches.",
    center_lat: 38.52,
    center_lon: -8.89,
    picks: [
      { day_theme: "nature", name_pl: "Parque da Arrábida", name_en: "Arrábida Natural Park", why_pl: "Klifowe drogi i widoki — wypad samochodem.", why_en: "Cliff roads and views — drive out.", activity_slugs: ["national_parks", "viewpoints"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Praia dos Galapos", name_en: "Galapos beach", why_pl: "Turkus w zatoce — parking nad klifem.", why_en: "Turquoise cove — clifftop parking.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Setúbal — owoce morza", name_en: "Setúbal seafood", why_pl: "Choco frito i rynek rybny — lunch obowiązkowy.", why_en: "Fried cuttlefish and fish market — must-do lunch.", activity_slugs: ["old_towns"], rank: 1 },
    ],
  },
  {
    id: "pt-costa-vicentina",
    destination_keys: ["odeceixe", "costa vicentina", "alentejo", "portugalia", "portugal"],
    slug: "costa-vicentina",
    name_pl: "Costa Vicentina",
    name_en: "Costa Vicentina",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Dziki zachodni wybrzeże — Odeceixe, Zambujeira i klify bez tłumów Algarve.",
    overview_en: "Wild west coast — Odeceixe, Zambujeira and cliffs without Algarve crowds.",
    stay_hint_pl: "Odeceixe lub Vila Nova de Milfontes — małe wioski nad oceanem.",
    stay_hint_en: "Odeceixe or Vila Nova de Milfontes — small ocean villages.",
    center_lat: 37.43,
    center_lon: -8.77,
    picks: [
      { day_theme: "beach_relax", name_pl: "Praia de Odeceixe", name_en: "Odeceixe beach", why_pl: "Plaża przy ujściu rzeki — unikalny kształt.", why_en: "River-mouth beach — unique shape.", activity_slugs: ["sandy_beaches", "viewpoints"], rank: 1 },
      { day_theme: "nature", name_pl: "Trilho dos Pescadores", name_en: "Fishermen's trail", why_pl: "Szlak Rota Vicentina — fragment wędrówki.", why_en: "Rota Vicentina section — hiking fragment.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Praia do Tonel", name_en: "Tonel beach", why_pl: "Sagres nearby — dziki klif i surf.", why_en: "Near Sagres — wild cliff and surf.", activity_slugs: ["rocky_beaches"], rank: 2 },
    ],
  },
  {
    id: "pt-guarda-estrela",
    destination_keys: ["guarda", "serra da estrela", "portugalia", "portugal"],
    slug: "guarda-estrela",
    name_pl: "Guarda i Serra da Estrela",
    name_en: "Guarda & Serra da Estrela",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Najwyższe góry kontynentalnej Portugalii, ser queijo da Serra i zimowe stoki.",
    overview_en: "Mainland Portugal's highest mountains, queijo da Serra cheese and winter slopes.",
    stay_hint_pl: "Manteigas lub Guarda — baza pod Torre i szlaki.",
    stay_hint_en: "Manteigas or Guarda — base for Torre and trails.",
    center_lat: 40.54,
    center_lon: -7.27,
    picks: [
      { day_theme: "nature", name_pl: "Torre — szczyt", name_en: "Torre summit", why_pl: "1993 m n.p.m. — widok na całą Serra.", why_en: "1993 m — whole Serra panorama.", activity_slugs: ["viewpoints", "hiking_trails"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Guarda — katedra", name_en: "Guarda cathedral", why_pl: "Gotycka katedra granitowa — spacer po mieście.", why_en: "Granite Gothic cathedral — town stroll.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Ski Serra da Estrela", name_en: "Serra da Estrela ski", why_pl: "Sezon zimowy — nartostrada dla początkujących.", why_en: "Winter season — beginner ski slope.", activity_slugs: ["hiking_trails"], rank: 2 },
    ],
  },
  {
    id: "pt-azores-pico",
    destination_keys: ["pico", "azory", "azores", "portugalia", "portugal"],
    slug: "azores-pico",
    name_pl: "Azory — Pico",
    name_en: "Azores — Pico",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Wulkan Pico (2351 m), winnice lavowe i wieloryby — najdziksza wyspa Azorów.",
    overview_en: "Pico volcano (2351 m), lava vineyards and whales — wildest Azorean island.",
    stay_hint_pl: "Madalena lub São Roque — baza pod wspinaczkę i rejsy.",
    stay_hint_en: "Madalena or São Roque — base for climb and whale trips.",
    center_lat: 38.47,
    center_lon: -28.2,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Wspinaczka Pico", name_en: "Pico summit hike", why_pl: "2351 m — rezerwacja przewodnika obowiązkowa.", why_en: "2351 m — guide booking required.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
      { day_theme: "nature", name_pl: "Rejs wieloryby", name_en: "Whale watching", why_pl: "Faial Channel — wieloryby i delfiny.", why_en: "Faial Channel — whales and dolphins.", activity_slugs: ["boat_tour"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Winnice lavowe", name_en: "Lava vineyards", why_pl: "UNESCO — degustacja wina verdelho.", why_en: "UNESCO — verdelho wine tasting.", activity_slugs: ["old_towns"], rank: 2 },
    ],
  },
  {
    id: "pt-monsaraz-alentejo",
    destination_keys: ["monsaraz", "reguengos", "alentejo", "portugalia", "portugal"],
    slug: "monsaraz-alentejo",
    name_pl: "Monsaraz i jezioro Alqueva",
    name_en: "Monsaraz & Lake Alqueva",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Średniowieczna wioska na wzgórzu nad największym sztucznym jeziorem Europy.",
    overview_en: "Medieval hill village above Europe's largest artificial lake.",
    stay_hint_pl: "Monsaraz — nocleg z widokiem na Alqueva.",
    stay_hint_en: "Monsaraz — stay with Alqueva views.",
    center_lat: 38.44,
    center_lon: -7.38,
    picks: [
      { day_theme: "city_culture", name_pl: "Monsaraz — wioska", name_en: "Monsaraz village", why_pl: "Mury, kościół i panorama jeziora — spacer wieczorem.", why_en: "Walls, church and lake panorama — evening stroll.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Alqueva — rejs", name_en: "Alqueva lake cruise", why_pl: "Największe sztuczne jezioro UE — rejs o zachodzie.", why_en: "EU's largest artificial lake — sunset cruise.", activity_slugs: ["boat_tour", "viewpoints"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Reguengos — wino", name_en: "Reguengos wine", why_pl: "Degustacja Alentejo — krótki dojazd.", why_en: "Alentejo tasting — short drive.", activity_slugs: ["old_towns"], rank: 2 },
    ],
  },
  {
    id: "pt-viseu-dao",
    destination_keys: ["viseu", "dao", "portugalia", "portugal"],
    slug: "viseu-dao",
    name_pl: "Viseu i wino Dão",
    name_en: "Viseu & Dão wine",
    character: "mixed",
    vibe: "offbeat",
    overview_pl: "Stare Miasto Viseu, katedra i winnice Dão — spokojna centralna Portugalia.",
    overview_en: "Viseu Old Town, cathedral and Dão vineyards — quiet central Portugal.",
    stay_hint_pl: "Centrum Viseu — blisko katedry i restauracji.",
    stay_hint_en: "Viseu centre — near cathedral and restaurants.",
    center_lat: 40.66,
    center_lon: -7.91,
    picks: [
      { day_theme: "city_culture", name_pl: "Katedra Viseu", name_en: "Viseu Cathedral", why_pl: "Gotyk i azulejos — serce miasta.", why_en: "Gothic and azulejos — city heart.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Trasy winne Dão", name_en: "Dão wine routes", why_pl: "Pagórkowate drogi między winnicami — wypad samochodem.", why_en: "Rolling roads between vineyards — car trip.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Cava de Viriato", name_en: "Cava de Viriato", why_pl: "Ruiny rzymskie — krótka wizyta.", why_en: "Roman ruins — short visit.", activity_slugs: ["archaeology"], rank: 2 },
    ],
  }];
