import type { TouristRegion } from "./tourist-regions";

/** Nadmorskie regiony rodzinne — Włochy, Francja, Grecja, Chorwacja i inne. */
export const SEED_TOURIST_REGIONS_COASTAL: TouristRegion[] = [
  // --- Włochy: wybrzeże ---
  {
    id: "it-amalfi-coast",
    destination_keys: ["amalfi", "positano", "sorrento", "ravello", "wlochy", "italy", "campania"],
    slug: "amalfi-coast",
    name_pl: "Wybrzeże Amalfitańskie",
    name_en: "Amalfi Coast",
    character: "historic",
    vibe: "popular",
    overview_pl: "Positano, Amalfi i Sorrento — klifowe miejscowości, łodzie i plaże z płytkim zejściem.",
    overview_en: "Positano, Amalfi and Sorrento — cliff villages, boat trips and shallow beach access.",
    stay_hint_pl: "Praiano lub Maiori na spokój z dziećmi; Positano na widoki (drożej, schody).",
    stay_hint_en: "Praiano or Maiori for quieter family stays; Positano for views (pricier, stairs).",
    center_lat: 40.634,
    center_lon: 14.602,
    picks: [
      { day_theme: "beach_relax", name_pl: "Marina di Praia", name_en: "Marina di Praia", why_pl: "Mała zatoczka z łodziami — płytkie zejście, mniej tłumów niż Positano.", why_en: "Small cove with boats — gentle entry, less crowded than Positano.", activity_slugs: ["rocky_beaches", "boat_tour"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Maiori", name_en: "Maiori beach", why_pl: "Najdłuższa piaszczysta plaża na wybrzeżu — dobra z małymi dziećmi.", why_en: "Longest sandy beach on the coast — good with small kids.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "active_outdoor", name_pl: "Rejs do Capri", name_en: "Capri boat trip", why_pl: "Błękitna grota i skały Faraglioni — całodniowy rejs z portu.", why_en: "Blue Grotto and Faraglioni — full-day boat from harbour.", activity_slugs: ["boat_tour"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Ravello — ogrody", name_en: "Ravello gardens", why_pl: "Willa Rufolo z widokiem na morze — spokojne popołudnie poza plażą.", why_en: "Villa Rufolo sea views — calm afternoon away from the beach.", activity_slugs: ["viewpoints", "museums"], rank: 1 },
    ],
  },
  {
    id: "it-puglia-salento",
    destination_keys: ["puglia", "apulia", "otranto", "gallipoli", "lecce", "salento", "wlochy", "italy"],
    slug: "puglia-salento",
    name_pl: "Salento — Otranto i Gallipoli",
    name_en: "Salento — Otranto & Gallipoli",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Turkus Adriatyku i Jonii — piaszczyste zatoki, trulli i lokalna kuchnia.",
    overview_en: "Adriatic and Ionian turquoise — sandy coves, trulli and local food.",
    stay_hint_pl: "Gallipoli na plażę i nocne życie rodzinne; Otranto na spokój i historyczne centrum.",
    stay_hint_en: "Gallipoli for beach and family evenings; Otranto for quiet historic centre.",
    center_lat: 40.056,
    center_lon: 18.12,
    picks: [
      { day_theme: "beach_relax", name_pl: "Baia Verde (Gallipoli)", name_en: "Baia Verde", why_pl: "Piaszczysta, płytka woda — ulubiona plaża rodzin z południa Italii.", why_en: "Sandy, shallow — southern Italy family favourite.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Torre dell'Orso", name_en: "Torre dell'Orso", why_pl: "Dwie skalne wieże w morzu — płytkie zejście i kąpiel.", why_en: "Twin sea stacks — shallow entry and swim.", activity_slugs: ["rocky_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Otranto — katedra", name_en: "Otranto cathedral", why_pl: "Mozaikowa posadzka i port — krótki spacer z plaży.", why_en: "Mosaic floor and harbour — short walk from beach.", activity_slugs: ["old_towns", "castles"], rank: 1 },
      { day_theme: "kids", name_pl: "Park wodny (Gallipoli okolice)", name_en: "Water park (near Gallipoli)", why_pl: "Aquaparki w regionie — dzień przerwy od morza w upał.", why_en: "Regional aquaparks — break from the beach on hot days.", activity_slugs: ["water_parks"], rank: 1 },
    ],
  },
  {
    id: "it-puglia-gargano",
    destination_keys: ["gargano", "vieste", "peschici", "puglia", "wlochy", "italy"],
    slug: "puglia-gargano",
    name_pl: "Gargano — Vieste i Peschici",
    name_en: "Gargano — Vieste & Peschici",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Białe klify nad Adriatykiem — groty, rejsy łodzią i lasy nadmorskie.",
    overview_en: "White Adriatic cliffs — sea caves, boat tours and coastal forest.",
    stay_hint_pl: "Vieste lub Peschici — wynajem auta na Tremiti i plaże zatoki.",
    stay_hint_en: "Vieste or Peschici — car for Tremiti and bay beaches.",
    center_lat: 41.882,
    center_lon: 16.178,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Pizzomunno (Vieste)", name_en: "Pizzomunno beach", why_pl: "Monolit na plaży i długi piasek — ikona Gargano.", why_en: "Beach monolith and long sand — Gargano icon.", activity_slugs: ["sandy_beaches", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs po groty", name_en: "Sea cave boat tour", why_pl: "Białe klify i ukryte zatoczki — łodzie z portu Vieste.", why_en: "White cliffs and hidden coves — boats from Vieste.", activity_slugs: ["boat_tour"], rank: 1 },
      { day_theme: "nature", name_pl: "Wyspy Tremiti", name_en: "Tremiti islands", why_pl: "Rejs promem — krystaliczna woda i snorkeling.", why_en: "Ferry hop — crystal water and snorkelling.", activity_slugs: ["boat_tour", "snorkeling"], rank: 1 },
    ],
  },
  {
    id: "it-rimini-riviera",
    destination_keys: ["rimini", "riccione", "cattolica", "emilia romagna", "wlochy", "italy"],
    slug: "rimini-riviera",
    name_pl: "Rimini i Riviera Romagnola",
    name_en: "Rimini & Romagna Riviera",
    character: "resort",
    vibe: "popular",
    overview_pl: "Kilometry piaszczystej plaży, parki rozrywki i aquaparki — klasyk rodzinnych wyjazdów nad morze.",
    overview_en: "Miles of sandy beach, theme parks and aquaparks — classic family seaside holidays.",
    stay_hint_pl: "Riccione lub Cattolica — spokojniej niż centrum Rimini, blisko aquaparków.",
    stay_hint_en: "Riccione or Cattolica — quieter than central Rimini, near aquaparks.",
    center_lat: 44.067,
    center_lon: 12.569,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaże Rimini", name_en: "Rimini beaches", why_pl: "Piaszczyste, płytkie, pełna infrastruktura — leżaki i bary.", why_en: "Sandy, shallow, full facilities — sunbeds and bars.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "kids", name_pl: "Aquafan / Oltremare", name_en: "Aquafan / Oltremare", why_pl: "Aquapark i delfinaria — cały dzień z dziećmi w Riccione.", why_en: "Water park and marine park — full day with kids in Riccione.", activity_slugs: ["water_parks", "aquarium"], rank: 1 },
      { day_theme: "city_culture", name_pl: "San Marino (wycieczka)", name_en: "San Marino day trip", why_pl: "Mikropaństwo w górach — 1 h jazdy, widoki i lody.", why_en: "Mountain microstate — 1 h drive, views and gelato.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "it-liguria-cinque-terre",
    destination_keys: ["cinque terre", "la spezia", "monterosso", "vernazza", "liguria", "wlochy", "italy"],
    slug: "liguria-cinque-terre",
    name_pl: "Cinque Terre i La Spezia",
    name_en: "Cinque Terre & La Spezia",
    character: "wild",
    vibe: "popular",
    overview_pl: "Kolorowe wioski na klifach, pociąg między miejscowościami i małe plaże z kamieniami.",
    overview_en: "Colourful cliff villages, train links and small pebble beaches.",
    stay_hint_pl: "La Spezia jako baza (taniej) — pociąg do Monterosso i Vernazza; unikaj walizek.",
    stay_hint_en: "La Spezia as base (cheaper) — train to Monterosso and Vernazza; avoid suitcases.",
    center_lat: 44.146,
    center_lon: 9.655,
    picks: [
      { day_theme: "beach_relax", name_pl: "Monterosso — plaża", name_en: "Monterosso beach", why_pl: "Jedyna większa piaszczysta plaża Cinque Terre — dobra z dziećmi.", why_en: "Only larger sandy beach in Cinque Terre — kid-friendly.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Pociąg Cinque Terre", name_en: "Cinque Terre train", why_pl: "Jeden bilet — Vernazza, Manarola, Riomaggiore bez auta.", why_en: "One pass — Vernazza, Manarola, Riomaggiore without a car.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "nature", name_pl: "Szlak Blue Trail", name_en: "Blue Trail hike", why_pl: "Łatwy odcinek Monterosso–Vernazza — widoki, sprawdź czy otwarty.", why_en: "Easy Monterosso–Vernazza section — views, check if open.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "it-liguria-portofino",
    destination_keys: ["portofino", "santa margherita", "rapallo", "camogli", "liguria", "wlochy", "italy", "genoa", "genua"],
    slug: "liguria-portofino",
    name_pl: "Portofino i zatoka Genui",
    name_en: "Portofino & Genoa bay",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Camogli, Portofino i Santa Margherita — mniejsze plaże, rejsy i pesto liguryjskie.",
    overview_en: "Camogli, Portofino and Santa Margherita — small beaches, boat trips and Ligurian pesto.",
    stay_hint_pl: "Camogli na rodzinny klimat; Rapallo na dłuższą plażę i pociąg do Genui.",
    stay_hint_en: "Camogli for family vibe; Rapallo for longer beach and Genoa train.",
    center_lat: 44.303,
    center_lon: 9.209,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Camogli", name_en: "Camogli beach", why_pl: "Kameralna zatoka, kolorowe domy — płytkie zejście przy molo.", why_en: "Intimate bay, colourful houses — shallow entry by pier.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs do San Fruttuoso", name_en: "San Fruttuoso boat", why_pl: "Opactwo nad zatoką — łodzie z Camogli lub Portofino.", why_en: "Abbey bay — boats from Camogli or Portofino.", activity_slugs: ["boat_tour", "old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Genua — akwarium", name_en: "Genoa aquarium", why_pl: "Jedno z największych w Europie — deszczowy dzień z dziećmi.", why_en: "One of Europe's largest — rainy day with kids.", activity_slugs: ["aquarium"], rank: 1 },
    ],
  },
  {
    id: "it-calabria-tropea",
    destination_keys: ["tropea", "calabria", "pizzo", "capo vaticano", "wlochy", "italy"],
    slug: "calabria-tropea",
    name_pl: "Tropea i Tyrrhenian Calabria",
    name_en: "Tropea & Tyrrhenian Calabria",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Tropea na klifie, biały piasek i turkus — tańsza alternatywa dla Sycylii.",
    overview_en: "Clifftop Tropea, white sand and turquoise — cheaper Sicily alternative.",
    stay_hint_pl: "Tropea centrum lub Capo Vaticano — auto na ukryte plaże.",
    stay_hint_en: "Tropea centre or Capo Vaticano — car for hidden beaches.",
    center_lat: 38.675,
    center_lon: 15.896,
    picks: [
      { day_theme: "beach_relax", name_pl: "Spiaggia Rotonda (Tropea)", name_en: "Rotonda beach", why_pl: "Plaża pod klifem z widokiem na kościół — płytkie morze.", why_en: "Beach below cliff with church view — shallow sea.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Capo Vaticano", name_en: "Capo Vaticano", why_pl: "Widokowe klify i kilka zatoczek — mniej zatłoczone niż Tropea.", why_en: "Scenic cliffs and coves — less crowded than Tropea.", activity_slugs: ["rocky_beaches", "viewpoints"], rank: 2 },
      { day_theme: "kids", name_pl: "Tartufo di Pizzo (lody)", name_en: "Pizzo gelato", why_pl: "Rodzinny Pizzo — słynne lody tartufo nad morzem.", why_en: "Family-friendly Pizzo — famous tartufo gelato by the sea.", activity_slugs: ["old_towns"], rank: 1 },
    ],
  },
  {
    id: "it-elba-island",
    destination_keys: ["elba", "isola d elba", "portoferraio", "toscana", "wlochy", "italy"],
    slug: "elba-island",
    name_pl: "Wyspa Elba",
    name_en: "Elba island",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Toskańska wyspa — dzikie zatoczki, prom z Piombino i historia Napoleona.",
    overview_en: "Tuscan island — wild coves, Piombino ferry and Napoleon's exile.",
    stay_hint_pl: "Marina di Campo na długą plażę; Portoferraio na zwiedzanie.",
    stay_hint_en: "Marina di Campo for long beach; Portoferraio for sightseeing.",
    center_lat: 42.762,
    center_lon: 10.241,
    picks: [
      { day_theme: "beach_relax", name_pl: "Marina di Campo", name_en: "Marina di Campo", why_pl: "Najdłuższa piaszczysta plaża Elby — płytkie morze, wypożyczalnie.", why_en: "Elba's longest sandy beach — shallow sea, rentals.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs wokół wyspy", name_en: "Island boat tour", why_pl: "Błękitne zatoczki niedostępne drogą — półdniowy rejs.", why_en: "Roadless blue coves — half-day cruise.", activity_slugs: ["boat_tour", "snorkeling"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Portoferraio — fortece", name_en: "Portoferraio fortresses", why_pl: "Napoleon i port — spacer po południu plażowania.", why_en: "Napoleon and harbour — post-beach afternoon walk.", activity_slugs: ["castles", "old_towns"], rank: 1 },
    ],
  },
  {
    id: "it-garda-sirmione",
    destination_keys: ["garda", "sirmione", "desenzano", "lazise", "wlochy", "italy", "lago di garda"],
    slug: "garda-sirmione",
    name_pl: "Jezioro Garda — Sirmione",
    name_en: "Lake Garda — Sirmione",
    character: "resort",
    vibe: "popular",
    overview_pl: "Nie morze, ale jak morze dla dzieci — płytkie zejścia, termy i Gardaland w zasięgu.",
    overview_en: "Not the sea but sea-like for kids — gentle entry, thermal baths and Gardaland nearby.",
    stay_hint_pl: "Sirmione na klimat półwyspu; Desenzano na komunikację i plaże.",
    stay_hint_en: "Sirmione for peninsula charm; Desenzano for transport and beaches.",
    center_lat: 45.492,
    center_lon: 10.608,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaże Desenzano", name_en: "Desenzano beaches", why_pl: "Piaszczyste zejścia do jeziora — ciepła, płytka woda latem.", why_en: "Sandy lake access — warm, shallow water in summer.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "kids", name_pl: "Gardaland", name_en: "Gardaland", why_pl: "Park rozrywki nad jeziorem — cały dzień z dziećmi.", why_en: "Theme park by the lake — full day with kids.", activity_slugs: ["theme_parks"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Scaligero (Sirmione)", name_en: "Scaligero castle", why_pl: "Zamek w wodzie i termy — krótki spacer z plaży.", why_en: "Waterside castle and thermal baths — short walk from beach.", activity_slugs: ["castles", "old_towns"], rank: 1 },
    ],
  },
  {
    id: "it-abruzzo-giulianova",
    destination_keys: ["abruzzo", "giulianova", "pescara", "roseto", "wlochy", "italy"],
    slug: "abruzzo-adriatic",
    name_pl: "Giulianova i Abruzzo nad morzem",
    name_en: "Giulianova & Abruzzo coast",
    character: "resort",
    vibe: "offbeat",
    overview_pl: "Tańsze Adriatyckie wybrzeże — długie plaże, mniej tłumów niż na południu.",
    overview_en: "Cheaper Adriatic coast — long beaches, fewer crowds than the south.",
    stay_hint_pl: "Giulianova lub Roseto — spokojne kurorty, blisko Pescary (lotnisko).",
    stay_hint_en: "Giulianova or Roseto — quiet resorts, near Pescara airport.",
    center_lat: 42.753,
    center_lon: 13.965,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Giulianova", name_en: "Giulianova beach", why_pl: "Szeroka, piaszczysta, płytka — idealna na leniwe dni z dziećmi.", why_en: "Wide sandy shallow beach — lazy days with kids.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "nature", name_pl: "Gran Sasso (wycieczka)", name_en: "Gran Sasso day trip", why_pl: "Góry w 1,5 h jazdy — chłód i widoki w upalny dzień.", why_en: "Mountains 1.5 h away — cool air on hot days.", activity_slugs: ["viewpoints", "hiking_trails"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Pescara — promenada", name_en: "Pescara promenade", why_pl: "Nadmorskie miasto z mostem nad rzeką — kolacja nad wodą.", why_en: "Seaside city with river bridge — dinner by the water.", activity_slugs: ["old_towns"], rank: 1 },
    ],
  },

  // --- Francja: wybrzeże ---
  {
    id: "fr-marseille-cassis",
    destination_keys: ["marsylia", "marseille", "cassis", "la ciotat", "francja", "france", "provence"],
    slug: "marseille-cassis",
    name_pl: "Marsylia i Cassis",
    name_en: "Marseille & Cassis",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Calanques, port w Cassis i plaże Prado w Marsylii — południe Francji z dziećmi.",
    overview_en: "Calanques, Cassis harbour and Prado beaches — family-friendly southern France.",
    stay_hint_pl: "Cassis na spokój i rejsy; Marsylia Prado na dłuższe miejskie plaże.",
    stay_hint_en: "Cassis for calm and boat trips; Marseille Prado for longer city beaches.",
    center_lat: 43.215,
    center_lon: 5.538,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plage du Bestouan (Cassis)", name_en: "Bestouan beach", why_pl: "Kamienista zatoczka w centrum — płytkie zejście, blisko portu.", why_en: "Central pebble cove — shallow entry, near harbour.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs Calanques", name_en: "Calanques boat tour", why_pl: "Białe klify i turkus — łodzie z Cassis, dzieci kochają rejs.", why_en: "White cliffs and turquoise — Cassis boats, kids love the ride.", activity_slugs: ["boat_tour"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plages du Prado (Marsylia)", name_en: "Prado beaches", why_pl: "Miejskie piaszczyste plaże z infrastrukturą — tramwaj z centrum.", why_en: "Urban sandy beaches with facilities — tram from centre.", activity_slugs: ["sandy_beaches"], rank: 2 },
    ],
  },
];