import type { TouristRegion } from "./tourist-regions";

/** 50 kolarskich „mek” — legendarne wjazdy, trasy wyścigów i bazy pro teamów. */
export const SEED_TOURIST_REGIONS_CYCLING_MECCA: TouristRegion[] = [
  {
    id: "cy-mk-fr-turini",
    destination_keys: ["turini", "col de turini", "nice", "francja", "france"],
    slug: "col-de-turini-cycling",
    name_pl: "Col de Turini — Nice",
    name_en: "Col de Turini — Nice",
    character: "wild",
    vibe: "popular",
    overview_pl: "34 serpentyny z Menton — legenda Paryż–Nice i Monte Carlo Rally.",
    overview_en: "34 hairpins from Menton — Paris–Nice and Monte Carlo Rally legend.",
    stay_hint_pl: "Sospel lub Lantosque — baza pod Turini i Madone.",
    stay_hint_en: "Sospel or Lantosque — base for Turini and Madone.",
    center_lat: 43.98,
    center_lon: 7.4,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Col de Turini", name_en: "Col de Turini", why_pl: "1607 m — jeden z najsłynniejszych wjazdów Alp Maritimes.", why_en: "1607 m — one of the Maritime Alps' most famous climbs.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-fr-loze",
    destination_keys: ["loze", "meribel", "francja", "france", "alp"],
    slug: "col-de-la-loze-cycling",
    name_pl: "Col de la Loze — Méribel",
    name_en: "Col de la Loze — Méribel",
    character: "wild",
    vibe: "popular",
    overview_pl: "2304 m — nowy klasyk Tour de France z Meribel, widok na Mont Blanc.",
    overview_en: "2304 m — modern Tour de France classic from Méribel, Mont Blanc views.",
    stay_hint_pl: "Méribel lub Brides-les-Bains — baza w Trzech Dolinach.",
    stay_hint_en: "Méribel or Brides-les-Bains — Three Valleys base.",
    center_lat: 45.39,
    center_lon: 6.59,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Col de la Loze", name_en: "Col de la Loze", why_pl: "Najwyższy finisz Tour 2020 — e-bike lub pro legs.", why_en: "Tour 2020's highest finish — e-bike or pro legs.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-fr-beille",
    destination_keys: ["beille", "plateau de beille", "ariege", "francja", "france"],
    slug: "plateau-de-beille-cycling",
    name_pl: "Plateau de Beille",
    name_en: "Plateau de Beille",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Brutalny wjazd w Pireneje Ariège — etap decydujący Tour de France.",
    overview_en: "Brutal Ariège Pyrenees climb — Tour de France decider stage.",
    stay_hint_pl: "Ax-les-Thermes lub Tarascon — blisko foot of climb.",
    stay_hint_en: "Ax-les-Thermes or Tarascon — near climb foot.",
    center_lat: 42.76,
    center_lon: 1.67,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Plateau de Beille", name_en: "Plateau de Beille", why_pl: "1790 m — stały gradient 8%.", why_en: "1790 m — steady 8% gradient.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-fr-madone",
    destination_keys: ["madone", "col de la madone", "nice", "francja", "france"],
    slug: "col-de-la-madone-cycling",
    name_pl: "Col de la Madone — Nice",
    name_en: "Col de la Madone — Nice",
    character: "wild",
    vibe: "popular",
    overview_pl: "Testowy wjazd pro teamów nad Menton — Armstrong i Ullrich mierzyli tu moc.",
    overview_en: "Pro teams' test climb above Menton — Armstrong and Ullrich benchmarked here.",
    stay_hint_pl: "Menton lub Monaco — start z wybrzeża.",
    stay_hint_en: "Menton or Monaco — start from coast.",
    center_lat: 43.77,
    center_lon: 7.34,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Col de la Madone", name_en: "Col de la Madone", why_pl: "925 m — krótki ale stromy benchmark.", why_en: "925 m — short but steep benchmark.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-fr-granon",
    destination_keys: ["granon", "col du granon", "francja", "france", "alp"],
    slug: "col-du-granon-cycling",
    name_pl: "Col du Granon",
    name_en: "Col du Granon",
    character: "wild",
    vibe: "balanced",
    overview_pl: "2413 m — scena legendarny atak Induraina vs Bernard (1986).",
    overview_en: "2413 m — scene of Indurain vs Bernard's legendary 1986 attack.",
    stay_hint_pl: "Briançon — krótki dojazd do foot of Granon.",
    stay_hint_en: "Briançon — short drive to Granon foot.",
    center_lat: 45.06,
    center_lon: 6.42,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Col du Granon", name_en: "Col du Granon", why_pl: "Jeden z najtrudniejszych wjazdów Alp — często zamknięty, sprawdź.", why_en: "One of the Alps' hardest climbs — often closed, check first.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-fr-aigoual",
    destination_keys: ["aigoual", "mont aigoual", "cevennes", "francja", "france"],
    slug: "mont-aigoual-cycling",
    name_pl: "Mont Aigoual — Cévennes",
    name_en: "Mont Aigoual — Cévennes",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "1567 m — wjazd przez Cévennes, często wiatr i mgła.",
    overview_en: "1567 m — climb through Cévennes, often windy and misty.",
    stay_hint_pl: "Valleraugue lub Le Vigan — baza w Cévennes.",
    stay_hint_en: "Valleraugue or Le Vigan — Cévennes base.",
    center_lat: 44.1,
    center_lon: 3.58,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Mont Aigoual", name_en: "Mont Aigoual", why_pl: "Radar na szczycie — panorama na południe Francji.", why_en: "Summit radar — southern France panorama.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-fr-iseran",
    destination_keys: ["iseran", "col de l'iseran", "val d'isere", "francja", "france"],
    slug: "col-de-l-iseran-cycling",
    name_pl: "Col de l'Iseran",
    name_en: "Col de l'Iseran",
    character: "wild",
    vibe: "popular",
    overview_pl: "2770 m — najwyższy asfaltowy przewód Alp, łączy Tarentaise z Maurienne.",
    overview_en: "2770 m — Alps' highest paved pass, links Tarentaise and Maurienne.",
    stay_hint_pl: "Val d'Isère lub Bonneval-sur-Arc — sezon letni krótki.",
    stay_hint_en: "Val d'Isère or Bonneval-sur-Arc — short summer season.",
    center_lat: 45.42,
    center_lon: 7.03,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Col de l'Iseran", name_en: "Col de l'Iseran", why_pl: "Najwyższy przewód — otwarty tylko latem.", why_en: "Highest pass — open summer only.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-fr-montvernier",
    destination_keys: ["montvernier", "lacets", "francja", "france"],
    slug: "lacets-de-montvernier-cycling",
    name_pl: "Lacets de Montvernier",
    name_en: "Lacets de Montvernier",
    character: "wild",
    vibe: "popular",
    overview_pl: "18 tight hairpins w 3 km — viralne serpentyny Tour de France 2015.",
    overview_en: "18 tight hairpins in 3 km — viral Tour de France 2015 hairpins.",
    stay_hint_pl: "Saint-Jean-de-Maurienne — start pętli przez lacets.",
    stay_hint_en: "Saint-Jean-de-Maurienne — lacets loop start.",
    center_lat: 45.3,
    center_lon: 6.36,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Lacets de Montvernier", name_en: "Lacets de Montvernier", why_pl: "Fotogeniczne serpentyny — wczesny poranek mniej ruchu.", why_en: "Photogenic hairpins — early morning less traffic.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-fr-portet",
    destination_keys: ["portet", "col du portet", "pyrenees", "francja", "france"],
    slug: "col-du-portet-cycling",
    name_pl: "Col du Portet",
    name_en: "Col du Portet",
    character: "wild",
    vibe: "balanced",
    overview_pl: "2215 m — nowy ulubieniec Tour de France w Hautes-Pyrénées.",
    overview_en: "2215 m — modern Tour de France favourite in Hautes-Pyrénées.",
    stay_hint_pl: "Saint-Lary-Soulan — stacja narciarska jako baza.",
    stay_hint_en: "Saint-Lary-Soulan — ski resort base.",
    center_lat: 42.83,
    center_lon: 0.15,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Col du Portet", name_en: "Col du Portet", why_pl: "Połączenie z Col de Port — podwójny finisz.", why_en: "Linked with Col de Port — double summit.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-fr-eze",
    destination_keys: ["eze", "col d'eze", "nice", "francja", "france"],
    slug: "col-d-eze-cycling",
    name_pl: "Col d'Eze — Paryż–Nice",
    name_en: "Col d'Eze — Paris–Nice",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Klasyczny finisz Paryż–Nice — krótki stromy wjazd nad Niceą.",
    overview_en: "Classic Paris–Nice finish — short steep climb above Nice.",
    stay_hint_pl: "Nice lub Èze village — start z wybrzeża.",
    stay_hint_en: "Nice or Èze village — start from coast.",
    center_lat: 43.73,
    center_lon: 7.32,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Col d'Eze", name_en: "Col d'Eze", why_pl: "507 m — często w programie Paris–Nice.", why_en: "507 m — often on Paris–Nice route.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-it-gavia",
    destination_keys: ["gavia", "passo gavia", "bormio", "wlochy", "italy", "dolomity"],
    slug: "passo-gavia-cycling",
    name_pl: "Passo di Gavia",
    name_en: "Passo di Gavia",
    character: "wild",
    vibe: "popular",
    overview_pl: "2618 m — legendarny etap Giro 1988 w śniegu, jeden z najtrudniejszych przewodów.",
    overview_en: "2618 m — legendary snowy Giro 1988 stage, one of the hardest passes.",
    stay_hint_pl: "Bormio lub Ponte di Legno — dwie strony wjazdu.",
    stay_hint_en: "Bormio or Ponte di Legno — two ascent sides.",
    center_lat: 46.34,
    center_lon: 10.49,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Passo di Gavia", name_en: "Passo di Gavia", why_pl: "2618 m — sprawdź pogodę przed startem.", why_en: "2618 m — check weather before start.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-it-zoncolan",
    destination_keys: ["zoncolan", "monte zoncolan", "wlochy", "italy", "giro"],
    slug: "monte-zoncolan-cycling",
    name_pl: "Monte Zoncolan",
    name_en: "Monte Zoncolan",
    character: "wild",
    vibe: "popular",
    overview_pl: "1730 m — najtrudniejszy finisz Giro, średnie nachylenie ponad 11%.",
    overview_en: "1730 m — Giro's hardest finish, average gradient over 11%.",
    stay_hint_pl: "Ovaro lub Sutrio — foot of the beast.",
    stay_hint_en: "Ovaro or Sutrio — foot of the beast.",
    center_lat: 46.4,
    center_lon: 12.93,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Monte Zoncolan", name_en: "Monte Zoncolan", why_pl: "Brutalny wjazd — e-bike lub hero mode.", why_en: "Brutal climb — e-bike or hero mode.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-it-blockhaus",
    destination_keys: ["blockhaus", "abruzzo", "wlochy", "italy", "giro"],
    slug: "blockhaus-cycling",
    name_pl: "Blockhaus — Abruzzo",
    name_en: "Blockhaus — Abruzzo",
    character: "wild",
    vibe: "balanced",
    overview_pl: "2142 m — ikoniczny finisz Giro w Parku Majella, widok na Adriatyku.",
    overview_en: "2142 m — iconic Giro finish in Majella Park, Adriatic views.",
    stay_hint_pl: "Pescara lub Sulmona — dojazd do foot of climb.",
    stay_hint_en: "Pescara or Sulmona — drive to climb foot.",
    center_lat: 42.12,
    center_lon: 14.08,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Blockhaus", name_en: "Blockhaus", why_pl: "Finisz etapu Giro — długi wjazd z Roccamorice.", why_en: "Giro stage finish — long climb from Roccamorice.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-it-spluga",
    destination_keys: ["spluga", "passo dello spluga", "wlochy", "italy", "switzerland"],
    slug: "passo-spluga-cycling",
    name_pl: "Passo dello Spluga",
    name_en: "Passo dello Spluga",
    character: "wild",
    vibe: "balanced",
    overview_pl: "2115 m — granica Włochy–Szwajcaria, tunel i serpentyny.",
    overview_en: "2115 m — Italy–Switzerland border, tunnel and hairpins.",
    stay_hint_pl: "Chiavenna lub Splügen — baza po obu stronach.",
    stay_hint_en: "Chiavenna or Splügen — base on both sides.",
    center_lat: 46.55,
    center_lon: 9.33,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Passo dello Spluga", name_en: "Passo dello Spluga", why_pl: "Klasyczny alpejski przewód — mniej tłumów niż Stelvio.", why_en: "Classic Alpine pass — fewer crowds than Stelvio.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-it-tonale",
    destination_keys: ["tonale", "passo del tonale", "wlochy", "italy"],
    slug: "passo-tonale-cycling",
    name_pl: "Passo del Tonale",
    name_en: "Passo del Tonale",
    character: "wild",
    vibe: "balanced",
    overview_pl: "1883 m — łączy Val di Sole z Lombardią, Giro regular.",
    overview_en: "1883 m — links Val di Sole and Lombardy, Giro regular.",
    stay_hint_pl: "Passo Tonale lub Ponte di Legno — stacja narciarska.",
    stay_hint_en: "Passo Tonale or Ponte di Legno — ski resort.",
    center_lat: 46.26,
    center_lon: 10.58,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Passo del Tonale", name_en: "Passo del Tonale", why_pl: "Łagodniejszy przewód — idealny na drugi dzień.", why_en: "Gentler pass — ideal second day.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-it-stelvio-prato",
    destination_keys: ["prato", "stelvio", "bormio", "wlochy", "italy"],
    slug: "stelvio-prato-side-cycling",
    name_pl: "Stelvio — strona Prato",
    name_en: "Stelvio — Prato side",
    character: "wild",
    vibe: "popular",
    overview_pl: "48 zakrętów od Prato — druga strona ikony, mniej ruchu niż Bormio.",
    overview_en: "48 hairpins from Prato — the icon's other side, less traffic than Bormio.",
    stay_hint_pl: "Prato allo Stelvio — bezpośrednio u podnóża.",
    stay_hint_en: "Prato allo Stelvio — directly at the foot.",
    center_lat: 46.47,
    center_lon: 10.48,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Stelvio od Prato", name_en: "Stelvio from Prato", why_pl: "2758 m — 48 hairpins, start wcześnie.", why_en: "2758 m — 48 hairpins, start early.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-it-falzarego-ext",
    destination_keys: ["falzarego", "cortina", "wlochy", "italy", "dolomity"],
    slug: "falzarego-cycling-mecca",
    name_pl: "Passo Falzarego — mekka",
    name_en: "Passo Falzarego — mecca",
    character: "wild",
    vibe: "popular",
    overview_pl: "2105 m — punkt centralny Dolomitów, Giro i Maratona co roku.",
    overview_en: "2105 m — Dolomites hub, Giro and Maratona every year.",
    stay_hint_pl: "Cortina lub Arabba — hub przewodów.",
    stay_hint_en: "Cortina or Arabba — pass hub.",
    center_lat: 46.52,
    center_lon: 12.01,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Passo Falzarego", name_en: "Passo Falzarego", why_pl: "Połączenie z Val Badia i Giau — triple pass day.", why_en: "Links Val Badia and Giau — triple pass day.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-it-aprica",
    destination_keys: ["aprica", "valtellina", "wlochy", "italy", "giro"],
    slug: "aprica-cycling",
    name_pl: "Aprica — Valtellina",
    name_en: "Aprica — Valtellina",
    character: "wild",
    vibe: "balanced",
    overview_pl: "1172 m — brama do Mortirolo i Tonale, regularny Giro.",
    overview_en: "1172 m — gateway to Mortirolo and Tonale, regular Giro.",
    stay_hint_pl: "Tirano lub Bormio — Valtellina base.",
    stay_hint_en: "Tirano or Bormio — Valtellina base.",
    center_lat: 46.15,
    center_lon: 10.15,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Aprica climb", name_en: "Aprica climb", why_pl: "Przewód przed Mortirolo — rozgrzewka lub finisz.", why_en: "Pass before Mortirolo — warm-up or finish.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-it-san-marco",
    destination_keys: ["san marco", "passo san marco", "wlochy", "italy", "dolomity"],
    slug: "passo-san-marco-cycling",
    name_pl: "Passo San Marco",
    name_en: "Passo San Marco",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "1992 m — dziki przewód między Bergamo a Valtellina.",
    overview_en: "1992 m — wild pass between Bergamo and Valtellina.",
    stay_hint_pl: "Valbondione lub Morbegno — małe miasta u podnóża.",
    stay_hint_en: "Valbondione or Morbegno — small foothill towns.",
    center_lat: 46.05,
    center_lon: 9.65,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Passo San Marco", name_en: "Passo San Marco", why_pl: "Mało ruchu — idealny na spokojny dzień w górach.", why_en: "Little traffic — ideal quiet mountain day.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-es-angliru",
    destination_keys: ["angliru", "asturias", "hiszpania", "spain", "vuelta"],
    slug: "alto-de-l-angliru-cycling",
    name_pl: "Alto de l'Angliru",
    name_en: "Alto de l'Angliru",
    character: "wild",
    vibe: "popular",
    overview_pl: "1569 m — najtrudniejszy finisz Vuelta, odcinki 23% nachylenia.",
    overview_en: "1569 m — Vuelta's hardest finish, sections at 23% gradient.",
    stay_hint_pl: "La Vega de Riosa — u podnóża legendarnego wjazdu.",
    stay_hint_en: "La Vega de Riosa — foot of legendary climb.",
    center_lat: 43.25,
    center_lon: -5.98,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Alto de l'Angliru", name_en: "Alto de l'Angliru", why_pl: "Coto Bello — odcinki 23%, compact 32T obowiązkowy.", why_en: "Coto Bello — 23% sections, compact 32T essential.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-es-pandera",
    destination_keys: ["pandera", "la pandera", "jaen", "andaluzja", "hiszpania"],
    slug: "la-pandera-cycling",
    name_pl: "La Pandera — Jaén",
    name_en: "La Pandera — Jaén",
    character: "wild",
    vibe: "balanced",
    overview_pl: "1830 m — słynny finisz Vuelta w Sierra de la Pandera.",
    overview_en: "1830 m — famous Vuelta finish in Sierra de la Pandera.",
    stay_hint_pl: "Jaén — baza w Andaluzji, 30 min do foot.",
    stay_hint_en: "Jaén — Andalusia base, 30 min to foot.",
    center_lat: 37.72,
    center_lon: -3.67,
    picks: [
      { day_theme: "active_outdoor", name_pl: "La Pandera", name_en: "La Pandera", why_pl: "Stromy wjazd przez oliwne gaje — upał latem.", why_en: "Steep climb through olive groves — summer heat.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-es-cumbre-verde",
    destination_keys: ["cumbre verde", "gran canaria", "hiszpania", "spain"],
    slug: "cumbre-verde-cycling",
    name_pl: "Cumbre Verde — Gran Canaria",
    name_en: "Cumbre Verde — Gran Canaria",
    character: "wild",
    vibe: "popular",
    overview_pl: "Trening pro teamów zimą — stromy wjazd w centrum wyspy.",
    overview_en: "Pro winter training ground — steep climb in island centre.",
    stay_hint_pl: "Tejeda lub Ayacata — blisko foot of climb.",
    stay_hint_en: "Tejeda or Ayacata — near climb foot.",
    center_lat: 27.96,
    center_lon: -15.57,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Cumbre Verde", name_en: "Cumbre Verde", why_pl: "Klasyk zimowego obozu — powtarzalny trening.", why_en: "Winter camp classic — repeatable training.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-es-xorret-cati",
    destination_keys: [
      "xorret",
      "xorret de cati",
      "castalla",
      "alicante",
      "alikante",
      "costa blanca",
      "hiszpania",
      "spain",
    ],
    slug: "xorret-de-cati-cycling",
    name_pl: "Xorret de Catí — Costa Blanca",
    name_en: "Xorret de Catí — Costa Blanca",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Krótki brutalny wjazd — trening WorldTour na Costa Blanca.",
    overview_en: "Short brutal climb — WorldTour Costa Blanca training.",
    stay_hint_pl: "Castalla lub Alicante — baza kolarska Costa Blanca.",
    stay_hint_en: "Castalla or Alicante — Costa Blanca cycling base.",
    center_lat: 38.45,
    center_lon: -0.45,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Xorret de Catí", name_en: "Xorret de Catí", why_pl: "586 m w 5 km — idealny test mocy.", why_en: "586 m in 5 km — ideal power test.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-es-alto-campoo",
    destination_keys: ["campoo", "alto campoo", "cantabria", "hiszpania", "spain"],
    slug: "alto-campoo-cycling",
    name_pl: "Alto de Campoo",
    name_en: "Alto de Campoo",
    character: "wild",
    vibe: "balanced",
    overview_pl: "1650 m — stacja narciarska Cantabrii, Vuelta i treningi.",
    overview_en: "1650 m — Cantabria ski station, Vuelta and training.",
    stay_hint_pl: "Campoo de Yuso — u podnóża wjazdu.",
    stay_hint_en: "Campoo de Yuso — at climb foot.",
    center_lat: 43.03,
    center_lon: -4.38,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Alto de Campoo", name_en: "Alto de Campoo", why_pl: "Długi wjazd z Cantabrii — chłodniejsze lato.", why_en: "Long Cantabria climb — cooler summer.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-es-collada-bonita",
    destination_keys: ["tenerife", "teide", "bonita", "hiszpania", "spain"],
    slug: "tenerife-teide-south-cycling",
    name_pl: "Teide — południowy wjazd",
    name_en: "Teide — south ascent",
    character: "wild",
    vibe: "popular",
    overview_pl: "Adeje–Teide — alternatywna strona wulkanu, trening pro zimą.",
    overview_en: "Adeje–Teide — alternative volcano side, pro winter training.",
    stay_hint_pl: "Adeje lub Arona — start z południa wyspy.",
    stay_hint_en: "Adeje or Arona — south island start.",
    center_lat: 28.16,
    center_lon: -16.63,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Teide od Adeje", name_en: "Teide from Adeje", why_pl: "Ponad 2300 m przewyższenia — całodzienny wjazd.", why_en: "2300 m+ gain — full-day climb.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-be-koppenberg",
    destination_keys: ["koppenberg", "flanders", "belgia", "belgium", "ronde"],
    slug: "koppenberg-cycling",
    name_pl: "Koppenberg — Flandria",
    name_en: "Koppenberg — Flanders",
    character: "mixed",
    vibe: "popular",
    overview_pl: "Najsłynniejszy kopiec Ronde van Vlaanderen — 22% na bruk.",
    overview_en: "Ronde van Vlaanderen's most famous cobbled climb — 22% gradient.",
    stay_hint_pl: "Oudenaarde — baza na pętlę Flandria klasyków.",
    stay_hint_en: "Oudenaarde — Flanders classics loop base.",
    center_lat: 50.79,
    center_lon: 3.59,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Koppenberg", name_en: "Koppenberg", why_pl: "600 m bruku — 22%, compact i technika.", why_en: "600 m cobbles — 22%, compact and technique.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-be-paterberg",
    destination_keys: ["paterberg", "flanders", "belgia", "belgium"],
    slug: "paterberg-cycling",
    name_pl: "Paterberg — Flandria",
    name_en: "Paterberg — Flanders",
    character: "mixed",
    vibe: "popular",
    overview_pl: "Ostatni kopiec przed finiszem Ronde — 20% bruk.",
    overview_en: "Last Ronde climb before finish — 20% cobbles.",
    stay_hint_pl: "Kluisbergen area — blisko serca trasy Ronde.",
    stay_hint_en: "Kluisbergen area — near Ronde route heart.",
    center_lat: 50.78,
    center_lon: 3.55,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Paterberg", name_en: "Paterberg", why_pl: "360 m — często decydujący punkt wyścigu.", why_en: "360 m — often race-deciding spot.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-be-la-redoute",
    destination_keys: ["redoute", "la redoute", "liege", "belgia", "belgium"],
    slug: "la-redoute-cycling",
    name_pl: "Côte de la Redoute — Liège",
    name_en: "Côte de la Redoute — Liège",
    character: "wild",
    vibe: "popular",
    overview_pl: "Kluczowy kopiec Liège–Bastogne–Liège — decydujący atak.",
    overview_en: "Key Liège–Bastogne–Liège climb — decisive attack spot.",
    stay_hint_pl: "Spa lub Aywaille — baza Ardennes.",
    stay_hint_en: "Spa or Aywaille — Ardennes base.",
    center_lat: 50.47,
    center_lon: 5.76,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Côte de la Redoute", name_en: "Côte de la Redoute", why_pl: "2 km w górę — LBL classic.", why_en: "2 km uphill — LBL classic.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-be-muurr-kapel",
    destination_keys: ["muur", "muur van geraardsbergen", "belgia", "belgium"],
    slug: "muur-van-geraardsbergen-cycling",
    name_pl: "Muur van Geraardsbergen",
    name_en: "Muur van Geraardsbergen",
    character: "mixed",
    vibe: "popular",
    overview_pl: "Kapelmuur — ikona Tour of Flanders, bruk i 19% pod kościołem.",
    overview_en: "Kapelmuur — Tour of Flanders icon, cobbles and 19% at church.",
    stay_hint_pl: "Geraardsbergen — start u foot of Muur.",
    stay_hint_en: "Geraardsbergen — start at Muur foot.",
    center_lat: 50.77,
    center_lon: 3.88,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Muur van Geraardsbergen", name_en: "Muur van Geraardsbergen", why_pl: "1075 m — kościół na szczycie, emocje gwarantowane.", why_en: "1075 m — church at top, emotions guaranteed.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-nl-cauberg",
    destination_keys: ["cauberg", "amstel gold", "holandia", "netherlands"],
    slug: "cauberg-cycling",
    name_pl: "Cauberg — Amstel Gold",
    name_en: "Cauberg — Amstel Gold Race",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Finisz Amstel Gold Race — krótki stromy wjazd w Limburgii.",
    overview_en: "Amstel Gold Race finish — short steep Limburg climb.",
    stay_hint_pl: "Valkenburg — serce holenderskiego kolarstwa górskiego.",
    stay_hint_en: "Valkenburg — Dutch hill cycling heart.",
    center_lat: 50.86,
    center_lon: 5.98,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Cauberg", name_en: "Cauberg", why_pl: "Finisz Amstel Gold — wielokrotne podjazdy w wyścigu.", why_en: "Amstel Gold finish — repeated race ascents.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-ch-klausen",
    destination_keys: ["klausen", "klausenpass", "szwajcaria", "switzerland"],
    slug: "klausen-pass-cycling",
    name_pl: "Klausen Pass",
    name_en: "Klausen Pass",
    character: "wild",
    vibe: "balanced",
    overview_pl: "1948 m — historyczny przewód, serpentyny i widoki na Uri.",
    overview_en: "1948 m — historic pass, hairpins and Uri views.",
    stay_hint_pl: "Altdorf lub Linthal — baza po obu stronach.",
    stay_hint_en: "Altdorf or Linthal — base on both sides.",
    center_lat: 46.87,
    center_lon: 8.86,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Klausen Pass", name_en: "Klausen Pass", why_pl: "1948 m — otwarty latem, sprawdź status drogi.", why_en: "1948 m — open in summer, check road status.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-ch-susten",
    destination_keys: ["susten", "sustenpass", "szwajcaria", "switzerland"],
    slug: "susten-pass-cycling",
    name_pl: "Susten Pass",
    name_en: "Susten Pass",
    character: "wild",
    vibe: "balanced",
    overview_pl: "2224 m — jeden z najpiękniejszych przewodów Szwajcarii.",
    overview_en: "2224 m — one of Switzerland's most beautiful passes.",
    stay_hint_pl: "Innertkirchen — centralna baza pod Susten i Grimsel.",
    stay_hint_en: "Innertkirchen — central base for Susten and Grimsel.",
    center_lat: 46.73,
    center_lon: 8.45,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Susten Pass", name_en: "Susten Pass", why_pl: "2224 m — pętla z Grimsel i Furka możliwa.", why_en: "2224 m — loop with Grimsel and Furka possible.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-ch-san-bernardino",
    destination_keys: ["san bernardino", "san bernardino pass", "szwajcaria", "switzerland"],
    slug: "san-bernardino-pass-cycling",
    name_pl: "San Bernardino Pass",
    name_en: "San Bernardino Pass",
    character: "wild",
    vibe: "balanced",
    overview_pl: "2065 m — łączy Graubünden z Ticino, spokojniejszy niż St. Gotthard.",
    overview_en: "2065 m — links Graubünden and Ticino, quieter than St. Gotthard.",
    stay_hint_pl: "Thusis lub Bellinzona — baza po obu stronach.",
    stay_hint_en: "Thusis or Bellinzona — base on both sides.",
    center_lat: 46.62,
    center_lon: 9.17,
    picks: [
      { day_theme: "active_outdoor", name_pl: "San Bernardino Pass", name_en: "San Bernardino Pass", why_pl: "2065 m — idealny dzień pass hunting.", why_en: "2065 m — ideal pass-hunting day.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-ch-gotthard-old",
    destination_keys: ["gotthard", "tremola", "szwajcaria", "switzerland"],
    slug: "gotthard-tremola-cycling",
    name_pl: "Gotthard — Tremola",
    name_en: "Gotthard — Tremola",
    character: "wild",
    vibe: "popular",
    overview_pl: "Stara droka Tremola — brukowane serpentyny UNESCO nad tunelem.",
    overview_en: "Old Tremola road — UNESCO cobbled hairpins above tunnel.",
    stay_hint_pl: "Airolo lub Hospental — start z północy lub południa.",
    stay_hint_en: "Airolo or Hospental — north or south start.",
    center_lat: 46.56,
    center_lon: 8.56,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Tremola serpentyny", name_en: "Tremola hairpins", why_pl: "Brukowane serpentyny — techniczny zjazd i wjazd.", why_en: "Cobbled hairpins — technical descent and climb.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-ch-fluela-ext",
    destination_keys: ["fluela", "fluelapass", "davos", "szwajcaria", "switzerland"],
    slug: "fluela-pass-mecca-cycling",
    name_pl: "Flüela Pass — mekka",
    name_en: "Flüela Pass — mecca",
    character: "wild",
    vibe: "balanced",
    overview_pl: "2383 m — Davos–Engadin, regularny w Tour de Suisse.",
    overview_en: "2383 m — Davos–Engadin, Tour de Suisse regular.",
    stay_hint_pl: "Davos — baza pro teamów i amatorów.",
    stay_hint_en: "Davos — pro and amateur base.",
    center_lat: 46.74,
    center_lon: 9.94,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Flüela Pass", name_en: "Flüela Pass", why_pl: "2383 m — połączenie z Engadinem.", why_en: "2383 m — Engadin link.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-at-kaiserkrone",
    destination_keys: ["kaiserkrone", "kitzbuhel", "austria", "austria"],
    slug: "kaiserkrone-cycling",
    name_pl: "Kaiserkrone — Tyrol",
    name_en: "Kaiserkrone — Tyrol",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Pętla 7 przełęczy wokół Wilder Kaiser — 60 km, 2500 m+. ",
    overview_en: "7-pass loop around Wilder Kaiser — 60 km, 2500 m+.",
    stay_hint_pl: "Kitzbühel lub St. Johann — baza Kaiserkrone.",
    stay_hint_en: "Kitzbühel or St. Johann — Kaiserkrone base.",
    center_lat: 47.48,
    center_lon: 12.35,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Kaiserkrone loop", name_en: "Kaiserkrone loop", why_pl: "7 cols w jednej pętli — całodzienna epicka trasa.", why_en: "7 cols in one loop — full-day epic.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-at-grossglockner-ext",
    destination_keys: ["grossglockner", "fusch", "austria", "austria"],
    slug: "grossglockner-edelweiss-cycling",
    name_pl: "Grossglockner — Edelweissspitze",
    name_en: "Grossglockner — Edelweiss peak",
    character: "wild",
    vibe: "popular",
    overview_pl: "2571 m Edelweissspitze — panorama na Grossglockner i Pasterze.",
    overview_en: "2571 m Edelweissspitze — Grossglockner and Pasterze panorama.",
    stay_hint_pl: "Fusch — start od południa na Hochalpenstrasse.",
    stay_hint_en: "Fusch — south start on Hochalpenstrasse.",
    center_lat: 47.07,
    center_lon: 12.73,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Edelweissspitze", name_en: "Edelweissspitze", why_pl: "2571 m — punkt widokowy na lodowiec.", why_en: "2571 m — glacier viewpoint.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-at-hochtor",
    destination_keys: ["hochtor", "hohe tauern", "grossglockner", "austria"],
    slug: "hochtor-cycling",
    name_pl: "Hochtor — Hohe Tauern",
    name_en: "Hochtor — Hohe Tauern",
    character: "wild",
    vibe: "balanced",
    overview_pl: "2504 m — najwyższy punkt Grossglockner Hochalpenstrasse.",
    overview_en: "2504 m — highest point of Grossglockner High Alpine Road.",
    stay_hint_pl: "Heiligenblut — północna brama Grossglockner.",
    stay_hint_en: "Heiligenblut — northern Grossglockner gate.",
    center_lat: 47.08,
    center_lon: 12.85,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Hochtor", name_en: "Hochtor", why_pl: "2504 m — szczyt drogi, płatny wstęp.", why_en: "2504 m — road summit, toll entry.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-de-feldberg",
    destination_keys: ["feldberg", "schwarzwald", "niemcy", "germany"],
    slug: "feldberg-cycling",
    name_pl: "Feldberg — Schwarzwald",
    name_en: "Feldberg — Black Forest",
    character: "wild",
    vibe: "balanced",
    overview_pl: "1493 m — najwyższy szczyt Schwarzwald, niemiecki klasyk wjazdów.",
    overview_en: "1493 m — Black Forest's highest peak, German climb classic.",
    stay_hint_pl: "Titisee lub Feldberg — baza w Schwarzwald.",
    stay_hint_en: "Titisee or Feldberg — Black Forest base.",
    center_lat: 47.87,
    center_lon: 8,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Feldberg climb", name_en: "Feldberg climb", why_pl: "1493 m — najwyższy punkt Schwarzwald.", why_en: "1493 m — Black Forest highest point.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-de-schauinsland-ext",
    destination_keys: ["schauinsland", "freiburg", "niemcy", "germany"],
    slug: "schauinsland-mecca-cycling",
    name_pl: "Schauinsland — mekka",
    name_en: "Schauinsland — mecca",
    character: "wild",
    vibe: "balanced",
    overview_pl: "1284 m — klasyczny wjazd z Freiburg, niemiecki benchmark.",
    overview_en: "1284 m — classic climb from Freiburg, German benchmark.",
    stay_hint_pl: "Freiburg — wypożyczalnie i start z miasta.",
    stay_hint_en: "Freiburg — rentals and city start.",
    center_lat: 47.91,
    center_lon: 7.9,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Schauinsland", name_en: "Schauinsland", why_pl: "1284 m — 1400 m przewyższenia z Freiburg.", why_en: "1284 m — 1400 m gain from Freiburg.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-gb-bealach",
    destination_keys: ["bealach", "bealach na ba", "scotland", "uk", "applecross"],
    slug: "bealach-na-ba-cycling",
    name_pl: "Bealach na Bà — Szkocja",
    name_en: "Bealach na Bà — Scotland",
    character: "wild",
    vibe: "popular",
    overview_pl: "626 m — najsłynniejszy wjazd Szkocji, 20% i widoki na Applecross.",
    overview_en: "626 m — Scotland's most famous climb, 20% and Applecross views.",
    stay_hint_pl: "Applecross lub Lochcarron — baza północno-zachodniej Szkocji.",
    stay_hint_en: "Applecross or Lochcarron — northwest Scotland base.",
    center_lat: 57.42,
    center_lon: -5.71,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Bealach na Bà", name_en: "Bealach na Bà", why_pl: "626 m — wiatr i 20%, compact obowiązkowy.", why_en: "626 m — wind and 20%, compact essential.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-gb-hartside",
    destination_keys: ["hartside", "pennine", "uk", "england"],
    slug: "hartside-pass-cycling",
    name_pl: "Hartside Pass — Pennines",
    name_en: "Hartside Pass — Pennines",
    character: "wild",
    vibe: "balanced",
    overview_pl: "590 m — Pennine classic, używany w Tour of Britain.",
    overview_en: "590 m — Pennine classic, used in Tour of Britain.",
    stay_hint_pl: "Alston lub Penrith — baza Pennines.",
    stay_hint_en: "Alston or Penrith — Pennines base.",
    center_lat: 54.78,
    center_lon: -2.45,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Hartside Pass", name_en: "Hartside Pass", why_pl: "590 m — długi wjazd z Cumbrii.", why_en: "590 m — long climb from Cumbria.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-gb-isle-man",
    destination_keys: ["isle of man", "tt", "uk", "man"],
    slug: "isle-of-man-tt-cycling",
    name_pl: "Isle of Man — TT Course",
    name_en: "Isle of Man — TT Course",
    character: "mixed",
    vibe: "popular",
    overview_pl: "60 km Mountain Course — TT i Tourist Trophy, mecca moto i rower.",
    overview_en: "60 km Mountain Course — TT and Tourist Trophy, moto and cycling mecca.",
    stay_hint_pl: "Douglas — wypożyczalnie, jedź poza sezonem TT.",
    stay_hint_en: "Douglas — rentals, ride outside TT season.",
    center_lat: 54.15,
    center_lon: -4.48,
    picks: [
      { day_theme: "active_outdoor", name_pl: "TT Mountain Course", name_en: "TT Mountain Course", why_pl: "60 km pętla — Snaefell Mountain i bruk.", why_en: "60 km loop — Snaefell Mountain and cobbles.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-no-geiranger",
    destination_keys: ["geiranger", "norwegia", "norway", "dalsnibba"],
    slug: "geiranger-cycling",
    name_pl: "Geiranger — Dalsnibba",
    name_en: "Geiranger — Dalsnibba",
    character: "wild",
    vibe: "popular",
    overview_pl: "1500 m przewyższenia do Dalsnibba — jeden z najpiękniejszych wjazdów Norwegii.",
    overview_en: "1500 m gain to Dalsnibba — one of Norway's finest climbs.",
    stay_hint_pl: "Geiranger — sezon letni krótki, rezerwuj nocleg.",
    stay_hint_en: "Geiranger — short summer season, book stay.",
    center_lat: 62.1,
    center_lon: 7.21,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Dalsnibba climb", name_en: "Dalsnibba climb", why_pl: "1500 m gain — widok na fiord Geiranger.", why_en: "1500 m gain — Geiranger fjord views.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-pl-koscielec",
    destination_keys: ["zakopane", "gubalowka", "polska", "poland", "tatry"],
    slug: "zakopane-climbs-cycling",
    name_pl: "Zakopane — wjazdy",
    name_en: "Zakopane — climbs",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Gubałówka i drogi pod Tatry — polski klasyk treningów górskich.",
    overview_en: "Gubałówka and Tatra foothill roads — Polish mountain training classic.",
    stay_hint_pl: "Zakopane centro — wypożyczalnie rowerów.",
    stay_hint_en: "Zakopane centre — bike rentals.",
    center_lat: 49.3,
    center_lon: 19.95,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Gubałówka climb", name_en: "Gubałówka climb", why_pl: "1126 m — widok na Tatry z roweru.", why_en: "1126 m — Tatra views from bike.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-cz-snezka",
    destination_keys: ["sněžka", "snezka", "krkonose", "czechy", "czech"],
    slug: "snezka-cycling",
    name_pl: "Śnieżka — Karkonosze",
    name_en: "Sněžka — Giant Mountains",
    character: "wild",
    vibe: "balanced",
    overview_pl: "1603 m — najwyższy szczyt Czech, wjazd pod Śnieżkę.",
    overview_en: "1603 m — Czech Republic's highest peak, climb toward Sněžka.",
    stay_hint_pl: "Pec pod Sněžkou — baza w Karkonoszach.",
    stay_hint_en: "Pec pod Sněžkou — Giant Mountains base.",
    center_lat: 50.74,
    center_lon: 15.74,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Śnieżka approach", name_en: "Sněžka approach", why_pl: "Wjazd pod szczyt — granica PL/CZ.", why_en: "Climb toward summit — PL/CZ border.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-pt-volta-serra",
    destination_keys: ["volta", "volta a portugal", "serra estrela", "portugalia", "portugal"],
    slug: "volta-portugal-serra-cycling",
    name_pl: "Volta a Portugal — Serra",
    name_en: "Volta a Portugal — Serra",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Etapy Volta a Portugal w Serra da Estrela — Torre i puste serpentyny.",
    overview_en: "Volta a Portugal stages in Serra da Estrela — Torre and empty hairpins.",
    stay_hint_pl: "Manteigas — baza na Torre i pętle Estrela.",
    stay_hint_en: "Manteigas — Torre and Estrela loop base.",
    center_lat: 40.32,
    center_lon: -7.6,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Torre — Volta stage", name_en: "Torre — Volta stage", why_pl: "1993 m — finisz etapu Volta.", why_en: "1993 m — Volta stage finish.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-pt-algarve-monchique-ext",
    destination_keys: ["monchique", "foia", "algarve", "portugalia", "portugal", "volta"],
    slug: "algarve-monchique-mecca-cycling",
    name_pl: "Monchique — mekka Algarve",
    name_en: "Monchique — Algarve mecca",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Foia (902 m) — finisz Volta ao Algarve, trening zimowy pro teamów.",
    overview_en: "Foia (902 m) — Volta ao Algarve finish, pro winter training.",
    stay_hint_pl: "Monchique — baza w górach za Algarve.",
    stay_hint_en: "Monchique — mountains behind Algarve base.",
    center_lat: 37.32,
    center_lon: -8.56,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Foia — Volta finish", name_en: "Foia — Volta finish", why_pl: "902 m — najwyższy punkt Algarve.", why_en: "902 m — Algarve's highest point.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-pt-arrabida-climb",
    destination_keys: ["arrabida", "portela arrabida", "portugalia", "portugal", "lisbon"],
    slug: "arrabida-climb-cycling",
    name_pl: "Arrábida — Portela",
    name_en: "Arrábida — Portela",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Portela da Arrábida — krótki stromy wjazd 30 min od Lizbony.",
    overview_en: "Portela da Arrábida — short steep climb 30 min from Lisbon.",
    stay_hint_pl: "Setúbal — start z miasta lub Sesimbra.",
    stay_hint_en: "Setúbal — start from town or Sesimbra.",
    center_lat: 38.48,
    center_lon: -8.98,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Portela da Arrábida", name_en: "Portela da Arrábida", why_pl: "499 m — klasyk lizbońskich treningów.", why_en: "499 m — Lisbon training classic.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-si-vrsic-north",
    destination_keys: ["vrsic", "kranjska gora", "słowenia", "slovenia"],
    slug: "vrsic-north-side-cycling",
    name_pl: "Vršič — strona północna",
    name_en: "Vršič — north side",
    character: "wild",
    vibe: "popular",
    overview_pl: "50 serpentyn od Kranjska Gora — północna strona legendarnego Vršič.",
    overview_en: "50 hairpins from Kranjska Gora — legendary Vršič north side.",
    stay_hint_pl: "Kranjska Gora — bezpośrednio u podnóża.",
    stay_hint_en: "Kranjska Gora — directly at the foot.",
    center_lat: 46.43,
    center_lon: 13.74,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Vršič od Kranjska Gora", name_en: "Vršič from Kranjska Gora", why_pl: "1611 m — 50 hairpins, start wcześnie.", why_en: "1611 m — 50 hairpins, start early.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  }];
