import type { TouristRegion } from "./tourist-regions";

/** Nadmorskie regiony rodzinne — Francja, Hiszpania, Grecja, Chorwacja i inne (part 2). */
export const SEED_TOURIST_REGIONS_COASTAL_2: TouristRegion[] = [
  // --- Francja: wybrzeże ---
  {
    id: "fr-cannes-antibes",
    destination_keys: ["cannes", "antibes", "juan les pins", "cote d azur", "francja", "france"],
    slug: "cannes-antibes",
    name_pl: "Cannes i Antibes",
    name_en: "Cannes & Antibes",
    character: "resort",
    vibe: "popular",
    overview_pl: "Lazurowe Wybrzeże między Niceą a Cannes — piaszczyste zatoczki, port w Antibes i spokojniejsze plaże niż w centrum Nicei.",
    overview_en: "French Riviera between Nice and Cannes — sandy coves, Antibes harbour and quieter beaches than central Nice.",
    stay_hint_pl: "Antibes — rodzinny klimat i plaże; Juan-les-Pins na dłuższą promenadę — pociąg TER do Nicei.",
    stay_hint_en: "Antibes for family vibe and beaches; Juan-les-Pins for longer promenade — TER train to Nice.",
    center_lat: 43.58,
    center_lon: 7.12,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plage de la Garoupe (Antibes)", name_en: "Garoupe beach", why_pl: "Kameralna zatoczka z płytkim zejściem — ulubiona plaża wśród rodzin w Antibes.", why_en: "Intimate cove with gentle entry — Antibes family favourite.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plage de la Croisette (Cannes)", name_en: "Croisette beach", why_pl: "Miejska plaża przy promenadzie — leżaki i kąpiel w centrum kurortu.", why_en: "City beach on the promenade — sunbeds and swim in resort centre.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Stary port Antibes", name_en: "Antibes old port", why_pl: "Fort Carré i rynek rybny — spacer po południu plażowania.", why_en: "Fort Carré and fish market — post-beach afternoon walk.", activity_slugs: ["old_towns", "castles"], rank: 1 },
      { day_theme: "kids", name_pl: "Marineland (Antibes okolice)", name_en: "Marineland (near Antibes)", why_pl: "Delfinaria i akwarium — deszczowy dzień z dziećmi na Lazurowym Wybrzeżu.", why_en: "Dolphinarium and aquarium — rainy day with kids on the Riviera.", activity_slugs: ["aquarium"], rank: 1 },
    ],
  },
  {
    id: "fr-biarritz-basque",
    destination_keys: ["biarritz", "saint jean de luz", "basque", "baskonia", "francja", "france"],
    slug: "biarritz-basque",
    name_pl: "Biarritz i Baskonia",
    name_en: "Biarritz & Basque coast",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Oceaniczne fale, Grande Plage i Saint-Jean-de-Luz — baskijska kuchnia i spokojniejsze zatoczki na południe.",
    overview_en: "Atlantic surf, Grande Plage and Saint-Jean-de-Luz — Basque food and quieter coves to the south.",
    stay_hint_pl: "Biarritz na plażę i infrastrukturę; Saint-Jean-de-Luz na spokój i port z dziećmi.",
    stay_hint_en: "Biarritz for beach and facilities; Saint-Jean-de-Luz for calm harbour stays with kids.",
    center_lat: 43.48,
    center_lon: -1.56,
    picks: [
      { day_theme: "beach_relax", name_pl: "Grande Plage (Biarritz)", name_en: "Grande Plage", why_pl: "Szeroka plaża w centrum — płytkie zejście przy molo, pełna infrastruktura.", why_en: "Wide central beach — shallow entry by pier, full facilities.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plage de la Côte des Basques", name_en: "Côte des Basques", why_pl: "Ikoniczna plaża surfingowa — obserwacja z klifu, kąpiel przy spokojnym morzu.", why_en: "Iconic surf beach — cliff views, swim when calm.", activity_slugs: ["rocky_beaches", "viewpoints"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Saint-Jean-de-Luz — port", name_en: "Saint-Jean-de-Luz harbour", why_pl: "Kolorowe domy nad zatoką — krótki spacer i pintxos z dziećmi.", why_en: "Colourful houses on the bay — short walk and pintxos with kids.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs do San Sebastián", name_en: "San Sebastián day trip", why_pl: "Hiszpańska Baskonia w zasięgu autobusu — plaża La Concha i stary port.", why_en: "Spanish Basque Country by bus — La Concha beach and old port.", activity_slugs: ["old_towns", "sandy_beaches"], rank: 1 },
    ],
  },
  {
    id: "fr-la-rochelle",
    destination_keys: ["la rochelle", "ile de re", "charente", "francja", "france"],
    slug: "la-rochelle",
    name_pl: "La Rochelle i Île de Ré",
    name_en: "La Rochelle & Île de Ré",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Port z wieżami, prom na Île de Ré i piaszczyste plaże Atlantyku — idealne na rodzinny tydzień nad morzem.",
    overview_en: "Towered harbour, ferry to Île de Ré and Atlantic sandy beaches — ideal family seaside week.",
    stay_hint_pl: "Centrum La Rochelle na zwiedzanie; Sainte-Marie-de-Ré na plażę i rowery po wyspie.",
    stay_hint_en: "Central La Rochelle for sights; Sainte-Marie-de-Ré for beach and island cycling.",
    center_lat: 46.16,
    center_lon: -1.15,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plage des Minimes", name_en: "Minimes beach", why_pl: "Miejska piaszczysta plaża z mariną — płytkie morze, dobra z małymi dziećmi.", why_en: "Urban sandy beach by marina — shallow sea, good with toddlers.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plage de la Conche (Île de Ré)", name_en: "La Conche beach", why_pl: "Długa plaża na wyspie — rower z portu, mniej tłumów niż w centrum.", why_en: "Long island beach — cycle from harbour, less crowded.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Stary port La Rochelle", name_en: "La Rochelle old port", why_pl: "Wieże łańcuchowe i akwarium — klasyczny spacer rodzinny.", why_en: "Chain towers and aquarium — classic family stroll.", activity_slugs: ["old_towns", "aquarium"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rowery po Île de Ré", name_en: "Île de Ré cycling", why_pl: "Płaskie ścieżki między plażami i solankami — wypożyczalnie przy porcie.", why_en: "Flat paths between beaches and salt pans — rentals at harbour.", activity_slugs: ["hiking_trails"], rank: 1 },
    ],
  },
  {
    id: "fr-bretagne-dinard",
    destination_keys: ["dinard", "saint malo", "bretania", "brittany", "francja", "france"],
    slug: "bretagne-dinard",
    name_pl: "Dinard i północna Bretania",
    name_en: "Dinard & north Brittany",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Eleganckie wille nad zatoką, plaże przy pływach i Saint-Malo w zasięgu promu — chłodniejsze morze, ale piękne krajobrazy.",
    overview_en: "Elegant bay villas, tidal beaches and Saint-Malo by ferry — cooler sea, beautiful scenery.",
    stay_hint_pl: "Dinard na plaże i spokój; Saint-Malo na twierdzę — prom lub most łatwy z dziećmi.",
    stay_hint_en: "Dinard for beaches and calm; Saint-Malo for fortress — easy ferry or bridge with kids.",
    center_lat: 48.63,
    center_lon: -2.06,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plage de l'Écluse (Dinard)", name_en: "Écluse beach", why_pl: "Piaszczysta plaża przy promenadzie — płytkie zejście o pływie.", why_en: "Sandy promenade beach — shallow at high tide.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plage du Sillon (Saint-Malo)", name_en: "Sillon beach", why_pl: "Długa plaża przed murami miasta — kąpiel i spacer po twierdzy.", why_en: "Long beach below city walls — swim and fortress walk.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Intra-muros Saint-Malo", name_en: "Saint-Malo walled city", why_pl: "Spacer po murach i port — miejsca na crêpes z widokiem na morze.", why_en: "Rampart walk and harbour — crêpe stops with sea views.", activity_slugs: ["old_towns", "castles"], rank: 1 },
      { day_theme: "nature", name_pl: "Mont Saint-Michel (wycieczka)", name_en: "Mont Saint-Michel day trip", why_pl: "Opactwo na wyspie — rezerwuj parking z wyprzedzeniem, dzieci kochają most.", why_en: "Island abbey — book parking early, kids love the causeway.", activity_slugs: ["viewpoints", "old_towns"], rank: 1 },
    ],
  },
  {
    id: "fr-collioure-vermeille",
    destination_keys: ["collioure", "cote vermeille", "perpignan", "francja", "france"],
    slug: "collioure-vermeille",
    name_pl: "Collioure i Côte Vermeille",
    name_en: "Collioure & Vermeille coast",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Kolorowe domy, zatoka z zamkiem i małe plaże nad Morzem Śródziemnym — spokojniejsza alternatywa dla Costa Bravy po francuskiej stronie.",
    overview_en: "Colourful houses, castle bay and small Mediterranean beaches — quieter Costa Brava alternative on the French side.",
    stay_hint_pl: "Collioure centrum — wszystko pieszo; auto na ukryte zatoczki w kierunku Banyuls.",
    stay_hint_en: "Central Collioure — walkable; car for hidden coves toward Banyuls.",
    center_lat: 42.53,
    center_lon: 3.08,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plage de la Port d'Avall", name_en: "Port d'Avall beach", why_pl: "Mała plaża pod zamkiem — płytkie zejście, idealna na popołudnie z dziećmi.", why_en: "Small beach below castle — shallow entry, ideal afternoon with kids.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plage de la Ribère", name_en: "Ribère beach", why_pl: "Piaszczysta zatoczka w centrum — leżaki i kąpiel tuż przy promenadzie.", why_en: "Sandy central cove — sunbeds and swim by the promenade.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Zamek Króla Wschodu", name_en: "Château Royal", why_pl: "Forteca nad portem — krótki spacer i widoki na zatokę.", why_en: "Harbour fortress — short walk and bay views.", activity_slugs: ["castles", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Szlak nad morzem do Port-Vendres", name_en: "Coastal walk to Port-Vendres", why_pl: "Łatwy spacer wzdłuż wybrzeża — lody i powrót autobusem.", why_en: "Easy coastal walk — gelato and bus back.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "fr-arcachon-dune",
    destination_keys: ["arcachon", "dune du pilat", "cap ferret", "gironde", "francja", "france"],
    slug: "arcachon-dune",
    name_pl: "Arcachon i Dune du Pilat",
    name_en: "Arcachon & Dune du Pilat",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Najwyższa wydma Europy, laguna z ostrygami i plaże Oceanu Atlantyckiego — wyjątkowy region do rodzinnego wypoczynku.",
    overview_en: "Europe's tallest dune, oyster lagoon and Atlantic beaches — unique family seaside region.",
    stay_hint_pl: "Ville d'Arcachon na plażę i promenadę; Cap Ferret na spokój i lagunę.",
    stay_hint_en: "Ville d'Arcachon for beach and promenade; Cap Ferret for calm lagoon stays.",
    center_lat: 44.65,
    center_lon: -1.21,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plage Pereire (Arcachon)", name_en: "Pereire beach", why_pl: "Szeroka piaszczysta plaża z promenadą — płytkie morze, dobra z dziećmi.", why_en: "Wide sandy promenade beach — shallow sea, kid-friendly.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "nature", name_pl: "Dune du Pilat", name_en: "Dune du Pilat", why_pl: "Wspinaczka po wydmie — widok na las i ocean, dzieci uwielbiają zbieganie w dół.", why_en: "Dune climb — forest and ocean views, kids love running down.", activity_slugs: ["viewpoints", "hiking_trails"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs po lagunie Arcachon", name_en: "Arcachon lagoon boat", why_pl: "Ostrygi i ptaki — krótki rejs z portu, spokojna woda dla małych.", why_en: "Oysters and birds — short harbour cruise, calm water for little ones.", activity_slugs: ["boat_tour"], rank: 1 },
      { day_theme: "kids", name_pl: "Cap Ferret — rowery i plaża", name_en: "Cap Ferret cycling & beach", why_pl: "Wąski półwysep z płytkimi zatokami — rower między plażami Atlantyku i laguny.", why_en: "Narrow peninsula with shallow pools — cycle between Atlantic and lagoon beaches.", activity_slugs: ["sandy_beaches"], rank: 1 },
    ],
  },
  {
    id: "fr-la-baule",
    destination_keys: ["la baule", "pornichet", "loire atlantique", "francja", "france"],
    slug: "la-baule",
    name_pl: "La Baule i zatoka Loary",
    name_en: "La Baule & Loire bay",
    character: "resort",
    vibe: "popular",
    overview_pl: "Jedna z najdłuższych plaż piaskowych we Francji — elegancka promenada, płytkie morze i blisko Nantes.",
    overview_en: "One of France's longest sandy beaches — elegant promenade, shallow sea and near Nantes.",
    stay_hint_pl: "La Baule-les-Pins na centrum plaży; Pornichet na spokojniejszy odcinek zatoki.",
    stay_hint_en: "La Baule-les-Pins for central beach; Pornichet for quieter bay section.",
    center_lat: 47.29,
    center_lon: -2.51,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plage de La Baule", name_en: "La Baule beach", why_pl: "Kilometry piasku z płytkim morzem — klasyczny francuski kurort rodzinny.", why_en: "Miles of sand with shallow sea — classic French family resort.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plage de Pornichet", name_en: "Pornichet beach", why_pl: "Spokojniejszy fragment zatoki — mniej tłumów, ta sama piaszczysta woda.", why_en: "Quieter bay section — fewer crowds, same sandy water.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "active_outdoor", name_pl: "Windsurfing / żeglarstwo", name_en: "Windsurf & sailing", why_pl: "Laguna i zatoka sprzyjają lekcjom dla początkujących — szkoły przy plaży.", why_en: "Bay and lagoon suit beginner lessons — schools on the beach.", activity_slugs: ["kayaking"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Guérande (wycieczka)", name_en: "Guérande day trip", why_pl: "Średniowieczne miasto i słona — lody słony karmel i spacer po murach.", why_en: "Medieval town and salt pans — salted caramel and rampart walk.", activity_slugs: ["old_towns"], rank: 1 },
    ],
  },

  // --- Hiszpania: wybrzeże ---
  {
    id: "es-costa-del-sol",
    destination_keys: ["marbella", "malaga", "costa del sol", "torremolinos", "benalmadena", "hiszpania", "spain"],
    slug: "costa-del-sol",
    name_pl: "Costa del Sol — Marbella i Málaga",
    name_en: "Costa del Sol — Marbella & Málaga",
    character: "resort",
    vibe: "popular",
    overview_pl: "Słoneczne południe Andaluzji — długie plaże, parki wodne i Alcazaba w Málaga na przerwę od morza.",
    overview_en: "Sunny Andalusia — long beaches, water parks and Málaga's Alcazaba for a break from the sea.",
    stay_hint_pl: "Benalmádena dla rodzin i aquapark; Marbella na dłuższe plaże i promenadę.",
    stay_hint_en: "Benalmádena for families and aquapark; Marbella for longer beaches and promenade.",
    center_lat: 36.51,
    center_lon: -4.88,
    picks: [
      { day_theme: "beach_relax", name_pl: "Playa de la Malagueta", name_en: "Malagueta beach", why_pl: "Miejska plaża Málagi — piaszczysta, pełna infrastruktury, blisko centrum.", why_en: "Málaga city beach — sandy, full facilities, near centre.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Playa de Cabopino (Marbella)", name_en: "Cabopino beach", why_pl: "Spokojniejsza plaża z pinami — płytkie morze, dobra z małymi dziećmi.", why_en: "Quieter pine-backed beach — shallow sea, good with toddlers.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "kids", name_pl: "Aqualand Torremolinos", name_en: "Aqualand Torremolinos", why_pl: "Duży aquapark — cały dzień z dziećmi w upalne popołudnie.", why_en: "Large water park — full day with kids on hot afternoons.", activity_slugs: ["water_parks"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Alcazaba i centrum Málagi", name_en: "Alcazaba & Málaga centre", why_pl: "Forteca nad miastem i muzeum Picassa — pół dnia poza plażą.", why_en: "Hilltop fortress and Picasso museum — half day away from beach.", activity_slugs: ["castles", "museums"], rank: 1 },
    ],
  },
  {
    id: "es-costa-brava",
    destination_keys: ["lloret de mar", "tossa de mar", "costa brava", "blanes", "hiszpania", "spain"],
    slug: "costa-brava",
    name_pl: "Costa Brava — Lloret i Tossa",
    name_en: "Costa Brava — Lloret & Tossa",
    character: "resort",
    vibe: "popular",
    overview_pl: "Katalońskie wybrzeże — plaże Lloret, średniowieczne Tossa i rejsy po ukrytych zatoczkach.",
    overview_en: "Catalan coast — Lloret beaches, medieval Tossa and boat trips to hidden coves.",
    stay_hint_pl: "Tossa de Mar na spokój i zamek; Lloret na nocne życie i dłuższe plaże.",
    stay_hint_en: "Tossa de Mar for calm and castle; Lloret for nightlife and longer beaches.",
    center_lat: 41.7,
    center_lon: 2.85,
    picks: [
      { day_theme: "beach_relax", name_pl: "Playa de Lloret", name_en: "Lloret beach", why_pl: "Główna piaszczysta plaża kurortu — leżaki, bary i promenada.", why_en: "Main resort sandy beach — sunbeds, bars and promenade.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Platja Gran (Tossa de Mar)", name_en: "Platja Gran", why_pl: "Plaża pod murami zamku — mniej hałasu niż Lloret, płytkie zejście.", why_en: "Beach below castle walls — quieter than Lloret, gentle entry.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Vila Vella (Tossa)", name_en: "Vila Vella", why_pl: "Średniowieczne miasto na klifie — spacer i widoki na zatokę.", why_en: "Medieval clifftop quarter — walk and bay views.", activity_slugs: ["old_towns", "castles"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs po calas", name_en: "Cove boat tour", why_pl: "Łodzie z portu Lloret — turkusowe zatoczki niedostępne drogą.", why_en: "Harbour boats from Lloret — turquoise roadless coves.", activity_slugs: ["boat_tour"], rank: 1 },
    ],
  },
  {
    id: "es-menorca",
    destination_keys: ["menorca", "minorca", "mahon", "ciutadella", "baleares", "hiszpania", "spain"],
    slug: "menorca-calas",
    name_pl: "Menorca — calas",
    name_en: "Menorca — coves",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Najspokojniejsza z Balearów — dziesiątki calas, biosfera UNESCO i mniej imprez niż na Majorce czy Ibizie.",
    overview_en: "Quietest Balearic island — dozens of coves, UNESCO biosphere and less party than Mallorca or Ibiza.",
    stay_hint_pl: "Cala Galdana lub Son Bou na plażę; wynajem auta praktycznie konieczny na calas.",
    stay_hint_en: "Cala Galdana or Son Bou for beach base; car essential for cove hopping.",
    center_lat: 39.94,
    center_lon: 4.08,
    picks: [
      { day_theme: "beach_relax", name_pl: "Cala Macarella", name_en: "Macarella cove", why_pl: "Ikoniczna turkusowa zatoczka — przyjedź wcześnie, parking ograniczony.", why_en: "Iconic turquoise cove — arrive early, limited parking.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Son Bou", name_en: "Son Bou", why_pl: "Najdłuższa piaszczysta plaża wyspy — dobra baza z dziećmi.", why_en: "Island's longest sandy beach — good family base.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "nature", name_pl: "Camí de Cavalls (fragment)", name_en: "Camí de Cavalls section", why_pl: "Szlak wokół wyspy — łatwy odcinek nad morzem z widokiem na calas.", why_en: "Island coastal path — easy sea section with cove views.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Ciutadella — port", name_en: "Ciutadella harbour", why_pl: "Stare miasto i kolacja nad wodą — wieczór poza plażą.", why_en: "Old town and harbour dinner — evening away from beach.", activity_slugs: ["old_towns"], rank: 1 },
    ],
  },
  {
    id: "es-ibiza-sant-antoni",
    destination_keys: ["ibiza", "sant antoni", "san antonio", "baleares", "hiszpania", "spain"],
    slug: "ibiza-sant-antoni",
    name_pl: "Ibiza — Sant Antoni i calas",
    name_en: "Ibiza — Sant Antoni & coves",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Zachód wyspy — rodzinne calas, zachody w San Antonio i Dalt Vila w zasięgu autobusu.",
    overview_en: "West Ibiza — family coves, San Antonio sunsets and Dalt Vila by bus.",
    stay_hint_pl: "Sant Antoni de Portmany na zachody i plaże; Santa Eulària spokojniej z dziećmi.",
    stay_hint_en: "Sant Antoni for sunsets and beaches; Santa Eulària quieter with kids.",
    center_lat: 38.98,
    center_lon: 1.3,
    picks: [
      { day_theme: "beach_relax", name_pl: "Cala Salada", name_en: "Cala Salada", why_pl: "Piaszczysta zatoczka z płytką wodą — ulubiona plaża wśród rodzin na zachodzie.", why_en: "Sandy cove with shallow water — west coast family favourite.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Cala Gració", name_en: "Cala Gració", why_pl: "Blisko San Antonio — krótki dojazd, spokojna kąpiel z małymi.", why_en: "Near San Antonio — short ride, calm swim with little ones.", activity_slugs: ["rocky_beaches"], rank: 2 },
      { day_theme: "kids", name_pl: "Aquarium Cap Blanc", name_en: "Cap Blanc aquarium", why_pl: "Jaskinia z rekinami i płaszczkami — ciekawa alternatywa na deszczowy dzień.", why_en: "Cave aquarium with rays — rainy day alternative.", activity_slugs: ["aquarium"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Dalt Vila (Ibiza Town)", name_en: "Dalt Vila", why_pl: "UNESCO — forteca i uliczki, autobus z zachodu wyspy.", why_en: "UNESCO fortress and lanes — bus from west coast.", activity_slugs: ["old_towns", "castles"], rank: 1 },
    ],
  },
  {
    id: "es-cadiz-conil",
    destination_keys: ["cadiz", "conil", "vejer", "andaluzja", "hiszpania", "spain"],
    slug: "cadiz-conil",
    name_pl: "Cádiz i Conil de la Frontera",
    name_en: "Cádiz & Conil de la Frontera",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Najstarsze miasto Europy nad morzem i białe wioski z długimi plażami — autentyczna Andaluzja bez masowej turystyki Costa del Sol.",
    overview_en: "Europe's oldest seaside city and white villages with long beaches — authentic Andalusia without Costa del Sol crowds.",
    stay_hint_pl: "Conil na plażę i spokój; Cádiz centrum na historię — oba dobre z dziećmi.",
    stay_hint_en: "Conil for beach and calm; Cádiz centre for history — both kid-friendly.",
    center_lat: 36.28,
    center_lon: -6.09,
    picks: [
      { day_theme: "beach_relax", name_pl: "Playa de la Fontanilla (Conil)", name_en: "Fontanilla beach", why_pl: "Szeroka piaszczysta plaża — płytkie morze Atlantyku, idealna z dziećmi.", why_en: "Wide sandy beach — shallow Atlantic, ideal with kids.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Playa de la Caleta (Cádiz)", name_en: "La Caleta beach", why_pl: "Kameralna plaża w centrum miasta — kąpiel z widokiem na katedrę.", why_en: "Intimate city-centre beach — swim with cathedral views.", activity_slugs: ["rocky_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Stare miasto Cádiz", name_en: "Cádiz old town", why_pl: "Wieża Tavira i katedra — spacer po południu plażowania.", why_en: "Tavira tower and cathedral — post-beach afternoon walk.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Vejer de la Frontera (wycieczka)", name_en: "Vejer day trip", why_pl: "Biała wioska na wzgórzu — lody i widoki, 20 min jazdy od Conil.", why_en: "White hill village — gelato and views, 20 min from Conil.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "es-costa-dorada",
    destination_keys: ["salou", "cambrils", "tarragona", "costa dorada", "port aventura", "hiszpania", "spain"],
    slug: "costa-dorada",
    name_pl: "Costa Dorada — Salou",
    name_en: "Costa Dorada — Salou",
    character: "resort",
    vibe: "popular",
    overview_pl: "Katalońska Costa Dorada — długie plaże Salou, PortAventura i rzymskie Tarragona w zasięgu autobusu.",
    overview_en: "Catalan Costa Dorada — Salou's long beaches, PortAventura and Roman Tarragona by bus.",
    stay_hint_pl: "Salou na plażę i parki; Cambrils na spokojniejszą promenadę i owoce morza.",
    stay_hint_en: "Salou for beach and parks; Cambrils for quieter promenade and seafood.",
    center_lat: 41.08,
    center_lon: 1.14,
    picks: [
      { day_theme: "beach_relax", name_pl: "Platja de Llevant (Salou)", name_en: "Llevant beach", why_pl: "Główna piaszczysta plaża — płytkie morze, pełna infrastruktura rodzinna.", why_en: "Main sandy beach — shallow sea, full family facilities.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "kids", name_pl: "PortAventura World", name_en: "PortAventura World", why_pl: "Park rozrywki i Caribe Aquatic — cały dzień lub dwa z dziećmi.", why_en: "Theme park and Caribe Aquatic — one or two full days with kids.", activity_slugs: ["theme_parks", "water_parks"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Tarragona — amfiteatr", name_en: "Tarragona amphitheatre", why_pl: "Rzymskie ruiny nad morzem — krótka wycieczka z Salou.", why_en: "Roman ruins by the sea — short trip from Salou.", activity_slugs: ["archaeology", "old_towns"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Platja de Cambrils", name_en: "Cambrils beach", why_pl: "Spokojniejsza sąsiadka Salou — promenada i taverny nad brzegiem.", why_en: "Quieter Salou neighbour — promenade and shore tavernas.", activity_slugs: ["sandy_beaches"], rank: 2 },
    ],
  },
  {
    id: "es-mallorca-palma-south",
    destination_keys: ["palma", "mallorca", "majorka", "majorca", "playa de palma", "baleares", "hiszpania", "spain"],
    slug: "mallorca-palma-south",
    name_pl: "Majorka — Palma i południe",
    name_en: "Mallorca — Palma & south",
    character: "mixed",
    vibe: "popular",
    overview_pl: "Stolica wyspy, długa Playa de Palma i łatwy dostęp do calas — dobra baza na pierwszą wizytę na Baleary.",
    overview_en: "Island capital, long Playa de Palma and easy cove access — good first Balearics base.",
    stay_hint_pl: "Playa de Palma na plażę; centrum Palma na zwiedzanie katedry i portu.",
    stay_hint_en: "Playa de Palma for beach; central Palma for cathedral and harbour.",
    center_lat: 39.57,
    center_lon: 2.65,
    picks: [
      { day_theme: "beach_relax", name_pl: "Playa de Palma", name_en: "Playa de Palma", why_pl: "Kilometry piasku z tramwajem z centrum — płytkie morze, dobra z dziećmi.", why_en: "Miles of sand with tram from centre — shallow sea, kid-friendly.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Katedra La Seu (Palma)", name_en: "La Seu cathedral", why_pl: "Gotycka katedra nad portem — pół dnia w stolicy wyspy.", why_en: "Gothic cathedral over harbour — half day in island capital.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Cala Major", name_en: "Cala Major", why_pl: "Miejska zatoczka z autobusem — mniej tłumów niż główna plaża.", why_en: "Urban cove by bus — less crowded than main beach.", activity_slugs: ["rocky_beaches"], rank: 2 },
      { day_theme: "active_outdoor", name_pl: "Rejs do Drach (wycieczka)", name_en: "Drach caves trip", why_pl: "Jaskinie i koncert — autobus ze wschodniej części wyspy.", why_en: "Caves and concert — bus from eastern Mallorca.", activity_slugs: ["boat_tour"], rank: 1 },
    ],
  },
  {
    id: "es-mallorca-cala-millor",
    destination_keys: ["cala millor", "cala bona", "porto cristo", "mallorca", "majorka", "majorca", "baleares", "hiszpania", "spain"],
    slug: "mallorca-cala-millor",
    name_pl: "Majorka — Cala Millor",
    name_en: "Mallorca — Cala Millor",
    character: "resort",
    vibe: "popular",
    overview_pl: "Wschodnie wybrzeże Majorca — szerokie piaszczyste plaże, spokojne morze i blisko jaskiń Porto Cristo.",
    overview_en: "East Mallorca coast — wide sandy beaches, calm sea and Porto Cristo caves nearby.",
    stay_hint_pl: "Cala Millor na długą plażę; Cala Bona na spokojniejszą promenadę.",
    stay_hint_en: "Cala Millor for long beach; Cala Bona for quieter promenade.",
    center_lat: 39.6,
    center_lon: 3.38,
    picks: [
      { day_theme: "beach_relax", name_pl: "Playa de Cala Millor", name_en: "Cala Millor beach", why_pl: "Szeroka piaszczysta plaża — płytkie morze, pełna infrastruktura rodzinna.", why_en: "Wide sandy beach — shallow sea, full family facilities.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Sa Coma", name_en: "Sa Coma", why_pl: "Sąsiednia zatoka z łagodnym zejściem — mniej zatłoczona niż centrum Millor.", why_en: "Neighbouring bay with gentle entry — less busy than central Millor.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "kids", name_pl: "Coves del Drach", name_en: "Drach caves", why_pl: "Podziemne jezioro i muzyka — dzieci fascynują się łodziami w jaskini.", why_en: "Underground lake and music — kids love the cave boats.", activity_slugs: ["boat_tour"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Snorkeling w Cala Varques", name_en: "Cala Varques snorkel", why_pl: "Dzika zatoczka w zasięgu auta — czysta woda, wcześnie rano mniej ludzi.", why_en: "Wild cove by car — clear water, fewer people early morning.", activity_slugs: ["snorkeling", "rocky_beaches"], rank: 1 },
    ],
  },

  // --- Grecja ---
  {
    id: "gr-crete-rethymno",
    destination_keys: ["rethymno", "rethimno", "kreta", "crete", "grecja", "greece"],
    slug: "crete-rethymno",
    name_pl: "Rethymno i północna Kreta",
    name_en: "Rethymno & north Crete",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Wenecki port, długa plaża miejska i taverny w starym mieście — rodzinna baza między Chaníą a Heraklionem.",
    overview_en: "Venetian harbour, long city beach and old-town tavernas — family base between Chania and Heraklion.",
    stay_hint_pl: "Stare miasto Rethymno na klimat; plaże na wschód od portu na spokojniejsze odcinki.",
    stay_hint_en: "Old Rethymno for atmosphere; beaches east of harbour for quieter sections.",
    center_lat: 35.37,
    center_lon: 24.47,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Rethymno", name_en: "Rethymno beach", why_pl: "Kilometry piasku przed miastem — płytkie morze, leżaki i bary.", why_en: "Miles of sand before town — shallow sea, sunbeds and bars.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Stare miasto i forteca", name_en: "Old town & fortress", why_pl: "Labirynt uliczek nad portem — kolacja z widokiem na morze.", why_en: "Harbour lane maze — dinner with sea views.", activity_slugs: ["old_towns", "castles"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Przegląd wąwozu Kourtaliotiko", name_en: "Kourtaliotiko gorge", why_pl: "Wodospady i widoki — krótka wycieczka autem na południe.", why_en: "Waterfalls and views — short drive south.", activity_slugs: ["viewpoints", "hiking_trails"], rank: 1 },
      { day_theme: "kids", name_pl: "Plaża z placem zabaw (east strip)", name_en: "Beach with playground", why_pl: "Wschodni odcinek plaży ma place zabaw przy brzegu — wygodne z małymi.", why_en: "East beach strip has shore playgrounds — handy with toddlers.", activity_slugs: ["sandy_beaches"], rank: 1 },
    ],
  },
  {
    id: "gr-crete-matala",
    destination_keys: ["matala", "agia galini", "kreta", "crete", "grecja", "greece"],
    slug: "crete-matala",
    name_pl: "Matala i południowa Kreta",
    name_en: "Matala & south Crete",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Klifowe plaże, jaskinie hippisów i spokojniejsze południe Krety — mniej tłumów niż na północy wyspy.",
    overview_en: "Cliff beaches, hippie caves and quieter south Crete — fewer crowds than the north.",
    stay_hint_pl: "Matala na plażę pod klifem; Agia Galini na spokojniejszy port z dziećmi.",
    stay_hint_en: "Matala for cliff beach; Agia Galini for quieter harbour with kids.",
    center_lat: 35.0,
    center_lon: 24.75,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Matala", name_en: "Matala beach", why_pl: "Piaszczysta zatoka z jaskiniami w skale — unikalny klimat południa.", why_en: "Sandy bay with cliff caves — unique south-coast vibe.", activity_slugs: ["sandy_beaches", "viewpoints"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Agia Galini", name_en: "Agia Galini", why_pl: "Port w zatce z płytką wodą — spokojniejsza alternatywa dla Matala.", why_en: "Harbour cove with shallow water — calmer Matala alternative.", activity_slugs: ["rocky_beaches"], rank: 2 },
      { day_theme: "nature", name_pl: "Plaża Kommos", name_en: "Kommos beach", why_pl: "Długa dzika plaża z żółwiami — szanuj strefy ochronne latem.", why_en: "Long wild beach with turtles — respect protected zones in summer.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Pałac Faistos (wycieczka)", name_en: "Phaistos palace", why_pl: "Minojska ruina w górach — pół dnia poza plażą, blisko Matala.", why_en: "Minoan hilltop ruins — half day away from beach, near Matala.", activity_slugs: ["archaeology"], rank: 1 },
    ],
  },
  {
    id: "gr-naxos-agios-prokopios",
    destination_keys: ["naxos", "agios prokopios", "prokopios", "kyklady", "cyclades", "grecja", "greece"],
    slug: "naxos-agios-prokopios",
    name_pl: "Naksos — Agios Prokopios",
    name_en: "Naxos — Agios Prokopios",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Najpiękniejsza plaża wyspy, port Naksos z Portarą i tańsze Cyklady niż Santorini czy Mykonos.",
    overview_en: "Island's best beach, Naxos port with Portara and cheaper Cyclades than Santorini or Mykonos.",
    stay_hint_pl: "Agios Prokopios na plażę; Chora (Naxos Town) na wieczorne porty i promy.",
    stay_hint_en: "Agios Prokopios for beach; Chora for evening harbour and ferries.",
    center_lat: 37.09,
    center_lon: 25.34,
    picks: [
      { day_theme: "beach_relax", name_pl: "Agios Prokopios", name_en: "Agios Prokopios", why_pl: "Biały piasek i płytkie morze — najlepsza plaża na Cykladach dla rodzin.", why_en: "White sand and shallow sea — top Cycladic family beach.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Agia Anna", name_en: "Agia Anna", why_pl: "Sąsiednia zatoczka z tavernami — krótki spacer z Prokopios.", why_en: "Neighbouring cove with tavernas — short walk from Prokopios.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Portara (Chora)", name_en: "Portara gate", why_pl: "Ikoniczna brama przy zachodzie słońca — autobus z plaży.", why_en: "Iconic gate at sunset — bus from beach.", activity_slugs: ["archaeology", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Wioski w górach (Chalki / Apiranthos)", name_en: "Mountain villages", why_pl: "Tradycyjne wioski i lokalny ser — wynajem auta na pół dnia.", why_en: "Traditional villages and local cheese — half-day by car.", activity_slugs: ["old_towns"], rank: 1 },
    ],
  },
  {
    id: "gr-paros-naoussa",
    destination_keys: ["paros", "naoussa", "parikia", "kyklady", "cyclades", "grecja", "greece"],
    slug: "paros-naoussa",
    name_pl: "Paros — Naoussa",
    name_en: "Paros — Naoussa",
    character: "mixed",
    vibe: "popular",
    overview_pl: "Urokliwy port Naoussa, plaże Golden Beach i Kolymbithres — idealne Cyklady dla rodzin z dziećmi.",
    overview_en: "Pretty Naoussa harbour, Golden Beach and Kolymbithres — ideal family Cyclades.",
    stay_hint_pl: "Naoussa na klimat i kolacje; Golden Beach na długą piaszczystą plażę.",
    stay_hint_en: "Naoussa for atmosphere and dinners; Golden Beach for long sandy stretch.",
    center_lat: 37.12,
    center_lon: 25.24,
    picks: [
      { day_theme: "beach_relax", name_pl: "Kolymbithres", name_en: "Kolymbithres", why_pl: "Granitowe formacje i płytkie zatoczki — dzieci kochają skakanie po skałach.", why_en: "Granite formations and shallow pools — kids love rock hopping.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Golden Beach (Chrissi Akti)", name_en: "Golden Beach", why_pl: "Długa piaszczysta plaża — szkoły windsurfu dla starszych dzieci.", why_en: "Long sandy beach — windsurf schools for older kids.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Port Naoussa", name_en: "Naoussa harbour", why_pl: "Wąskie uliczki i kolacje nad wodą — wieczór po plaży.", why_en: "Narrow lanes and waterfront dinner — post-beach evening.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs na Antiparos", name_en: "Antiparos day trip", why_pl: "Krótki prom — jaskinia i spokojne plaże mniejszej wyspy.", why_en: "Short ferry — cave and quiet beaches on smaller island.", activity_slugs: ["boat_tour"], rank: 1 },
    ],
  },
  {
    id: "gr-mykonos-ornos",
    destination_keys: ["mykonos", "ornos", "platis gialos", "kyklady", "cyclades", "grecja", "greece"],
    slug: "mykonos-ornos",
    name_pl: "Mykonos — Ornos",
    name_en: "Mykonos — Ornos",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Spokojniejsza zachodnia Mykonos — Ornos i Platis Gialos z płytkim morzem, bez nocnego hałasu Mykonos Town.",
    overview_en: "Quieter west Mykonos — Ornos and Platis Gialos with shallow sea, away from town nightlife.",
    stay_hint_pl: "Ornos — rodzinny kurort; bus do Mykonos Town na zwiedzanie wiatraków.",
    stay_hint_en: "Ornos for family resort; bus to town for windmill sightseeing.",
    center_lat: 37.42,
    center_lon: 25.33,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Ornos", name_en: "Ornos beach", why_pl: "Chroniona zatoka z płytką wodą — taverny tuż przy piasku.", why_en: "Sheltered bay with shallow water — tavernas on the sand.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Platis Gialos", name_en: "Platis Gialos", why_pl: "Szeroka piaszczysta plaża z łagodnym zejściem — dobra z małymi.", why_en: "Wide sandy beach with gentle entry — good with toddlers.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Mykonos Town — wiatraki", name_en: "Mykonos windmills", why_pl: "Little Venice i wiatraki — popołudniowy spacer poza plażą.", why_en: "Little Venice and windmills — afternoon walk away from beach.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs na Delos", name_en: "Delos day trip", why_pl: "UNESCO — łodzie z portu, starsze dzieci docenią ruiny.", why_en: "UNESCO site — boats from harbour, older kids enjoy ruins.", activity_slugs: ["archaeology", "boat_tour"], rank: 1 },
    ],
  },
  {
    id: "gr-lefkada-nidri",
    destination_keys: ["lefkada", "lefkas", "nidri", "vasiliki", "wyspy jonskie", "ionian", "grecja", "greece"],
    slug: "lefkada-nidri",
    name_pl: "Lefkada — Nidri",
    name_en: "Lefkada — Nidri",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Mostem z kontynentu — turkusowe plaże Porto Katsiki i rejsy na okoliczne wysepki z Nidri.",
    overview_en: "Bridge-linked to mainland — turquoise Porto Katsiki and islet cruises from Nidri.",
    stay_hint_pl: "Nidri na rejsy i promenadę; Agios Nikitas na zachodnie plaże klifowe.",
    stay_hint_en: "Nidri for cruises and promenade; Agios Nikitas for west cliff beaches.",
    center_lat: 38.71,
    center_lon: 20.71,
    picks: [
      { day_theme: "beach_relax", name_pl: "Porto Katsiki", name_en: "Porto Katsiki", why_pl: "Słynna plaża pod klifem — przyjedź wcześnie, schody w dół i w górę.", why_en: "Famous cliff beach — arrive early, stairs down and up.", activity_slugs: ["rocky_beaches", "viewpoints"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Nidri", name_en: "Nidri beach", why_pl: "Miejska plaża z promenadą — płytkie morce, dobra baza z dziećmi.", why_en: "Town beach with promenade — shallow sea, good kid base.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "active_outdoor", name_pl: "Rejs na Skorpios / Meganisi", name_en: "Skorpios / Meganisi cruise", why_pl: "Wycieczki łodzią z Nidri — pływanie w zatokach i lanch na pokładzie.", why_en: "Boat tours from Nidri — bay swimming and onboard lunch.", activity_slugs: ["boat_tour", "snorkeling"], rank: 1 },
      { day_theme: "nature", name_pl: "Wodospady w Nydri", name_en: "Nidri waterfalls", why_pl: "Krótki szlak do kaskad — chłodna alternatywa w upał.", why_en: "Short trail to cascades — cool alternative in heat.", activity_slugs: ["hiking_trails"], rank: 1 },
    ],
  },
  {
    id: "gr-kefalonia-lassi",
    destination_keys: ["kefalonia", "cephalonia", "lassi", "argostoli", "wyspy jonskie", "ionian", "grecja", "greece"],
    slug: "kefalonia-lassi",
    name_pl: "Kefalonia — Lassi",
    name_en: "Kefalonia — Lassi",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Plaże Lassi koło Argostoli, żółwie w zatoce i Myrtos w zasięgu auta — zielona wyspa Jonii.",
    overview_en: "Lassi beaches near Argostoli, turtle bay and Myrtos by car — green Ionian island.",
    stay_hint_pl: "Lassi na plaże i taverny; wynajem auta na Myrtos i Fiskardo.",
    stay_hint_en: "Lassi for beaches and tavernas; car for Myrtos and Fiskardo.",
    center_lat: 38.17,
    center_lon: 20.51,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaże Lassi (Makris / Platis)", name_en: "Lassi beaches", why_pl: "Długie piaszczyste odcinki — płytkie morze, pełna infrastruktura.", why_en: "Long sandy stretches — shallow sea, full facilities.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "nature", name_pl: "Zatoka żółwi (Koutavouno)", name_en: "Turtle bay", why_pl: "Obserwacja carett-carett wieczorem — nie używaj latarni na plaży.", why_en: "Evening loggerhead watching — no torches on beach.", activity_slugs: ["viewpoints"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Myrtos", name_en: "Myrtos beach", why_pl: "Biały piasek i turkus — widok z drogi, schody w dół na kąpiel.", why_en: "White sand and turquoise — viewpoint from road, stairs to swim.", activity_slugs: ["rocky_beaches", "viewpoints"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Argostoli — promenada", name_en: "Argostoli promenade", why_pl: "Port stolicy wyspy — kolacja i most De Bosset o zmierzchu.", why_en: "Island capital harbour — dinner and De Bosset bridge at dusk.", activity_slugs: ["old_towns"], rank: 1 },
    ],
  },
  {
    id: "gr-thasos-golden-beach",
    destination_keys: ["thasos", "thassos", "potos", "limenaria", "grecja", "greece"],
    slug: "thasos-golden-beach",
    name_pl: "Tasos — Golden Beach",
    name_en: "Thasos — Golden Beach",
    character: "resort",
    vibe: "offbeat",
    overview_pl: "Zielona wyspa przy Macedonii — Golden Beach, tańsze Grecja i mniej tłumów niż na południu.",
    overview_en: "Green island off Macedonia — Golden Beach, cheaper Greece and fewer crowds than the south.",
    stay_hint_pl: "Skala Potamias na Golden Beach; Limenaria na zachód wyspy i zachody.",
    stay_hint_en: "Skala Potamias for Golden Beach; Limenaria for west coast sunsets.",
    center_lat: 40.75,
    center_lon: 24.71,
    picks: [
      { day_theme: "beach_relax", name_pl: "Golden Beach (Chrysi Ammos)", name_en: "Golden Beach", why_pl: "Kilometry piasku i płytkie morze — jedna z najlepszych plaż północnej Grecji.", why_en: "Miles of sand and shallow sea — one of north Greece's best beaches.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Potos", name_en: "Potos beach", why_pl: "Uroczy port z plażą — taverny i łodzie na ukryte zatoczki.", why_en: "Pretty harbour beach — tavernas and boats to hidden coves.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "active_outdoor", name_pl: "Rejs wokół wyspy", name_en: "Island boat tour", why_pl: "Całodniowy rejs — pływanie i grill na pokładzie.", why_en: "Full-day cruise — swimming and onboard barbecue.", activity_slugs: ["boat_tour", "snorkeling"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Limenas — stolica", name_en: "Limenas (Thasos Town)", why_pl: "Stare ruiny i port — krótki spacer z parkingu przy plaży.", why_en: "Ancient ruins and harbour — short walk from beach parking.", activity_slugs: ["archaeology", "old_towns"], rank: 1 },
    ],
  },

  // --- Chorwacja ---
  {
    id: "hr-zadar-region",
    destination_keys: ["zadar", "nin", "biograd", "dalmacja", "dalmatia", "chorwacja", "croatia"],
    slug: "zadar-region",
    name_pl: "Zadar i region",
    name_en: "Zadar region",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Organy Morskie, historyczne centrum i plaże Nin — północna Dalmacja z dobrym dostępem do parków Kornati.",
    overview_en: "Sea Organ, historic centre and Nin beaches — north Dalmatia with Kornati park access.",
    stay_hint_pl: "Centrum Zadar na zwiedzanie; Borik na plażę; Nin na piaszczyste zatoki z dziećmi.",
    stay_hint_en: "Central Zadar for sights; Borik for beach; Nin for sandy kid-friendly coves.",
    center_lat: 44.12,
    center_lon: 15.23,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Nin (Ždrijac)", name_en: "Nin Ždrijac beach", why_pl: "Piaszczysta laguna z płytką wodą — idealna z małymi dziećmi.", why_en: "Sandy lagoon with shallow water — ideal with toddlers.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Organy Morskie i Forum", name_en: "Sea Organ & Forum", why_pl: "Dźwięki fal i rzymskie ruiny — wieczorny spacer nad morzem.", why_en: "Wave music and Roman forum — evening seaside stroll.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Borik", name_en: "Borik beach", why_pl: "Miejska plaża z infrastrukturą — tramwaj wodny z centrum.", why_en: "City beach with facilities — water taxi from centre.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "active_outdoor", name_pl: "Rejs Kornati", name_en: "Kornati cruise", why_pl: "Park narodowy wysp — całodniowy rejs z pływaniem.", why_en: "Island national park — full-day cruise with swimming.", activity_slugs: ["boat_tour", "national_parks"], rank: 1 },
    ],
  },
  {
    id: "hr-istria-rovinj",
    destination_keys: ["rovinj", "porec", "pula", "istria", "istra", "chorwacja", "croatia"],
    slug: "istria-rovinj",
    name_pl: "Istria — Rovinj",
    name_en: "Istria — Rovinj",
    character: "historic",
    vibe: "popular",
    overview_pl: "Wenecja nad Adriatykiem — stary Rovinj, plaże Zlatni Rt i blisko Poreč z aquaparkiem.",
    overview_en: "Adriatic Venice — old Rovinj, Zlatni Rt beaches and Poreč aquapark nearby.",
    stay_hint_pl: "Rovinj centrum na klimat; Valalta / Lone na plaże z infrastrukturą.",
    stay_hint_en: "Central Rovinj for atmosphere; Valalta / Lone for equipped beaches.",
    center_lat: 45.08,
    center_lon: 13.64,
    picks: [
      { day_theme: "beach_relax", name_pl: "Zlatni Rt (Golden Cape)", name_en: "Golden Cape", why_pl: "Leśny półwysep z kamienistymi zatoczkami — naturę i kąpiel w jednym.", why_en: "Forest peninsula with pebble coves — nature and swim combined.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Stary Rovinj", name_en: "Old Rovinj", why_pl: "Wąskie uliczki i latarnia — kolacja z widokiem na archipelag.", why_en: "Narrow lanes and lighthouse — dinner with archipelago views.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "kids", name_pl: "Aquapark Aquacolors (Poreč)", name_en: "Aquacolors Poreč", why_pl: "Duży park wodny — 30 min jazdy, cały dzień z dziećmi.", why_en: "Large water park — 30 min drive, full day with kids.", activity_slugs: ["water_parks"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Lone", name_en: "Lone beach", why_pl: "Piaszczysta plaża z leżakami — blisko centrum, dobra dla rodzin.", why_en: "Sandy beach with sunbeds — near centre, family-friendly.", activity_slugs: ["sandy_beaches"], rank: 2 },
    ],
  },
  {
    id: "hr-makarska-riviera",
    destination_keys: ["makarska", "brela", "baska voda", "dalmacja", "dalmatia", "chorwacja", "croatia"],
    slug: "makarska-riviera",
    name_pl: "Riwiera Makarska",
    name_en: "Makarska Riviera",
    character: "resort",
    vibe: "popular",
    overview_pl: "Brela, Makarska i Biokovo — jedne z najpiękniejszych plaż Dalmacji u stóp gór.",
    overview_en: "Brela, Makarska and Biokovo — among Dalmatia's finest beaches below the mountains.",
    stay_hint_pl: "Brela na najlepszą plażę; Makarska na promenadę i wypożyczalnie łodzi.",
    stay_hint_en: "Brela for top beach; Makarska for promenade and boat rentals.",
    center_lat: 43.3,
    center_lon: 17.02,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Punta Rata (Brela)", name_en: "Punta Rata beach", why_pl: "Słynna plaża z głazem — turkus wody i płytkie zejście.", why_en: "Famous boulder beach — turquoise water and gentle entry.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Makarska", name_en: "Makarska beach", why_pl: "Długa promenada i pełna infrastruktura — dobra baza rodzinna.", why_en: "Long promenade and full facilities — solid family base.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "nature", name_pl: "Biokovo (Sveti Jure)", name_en: "Biokovo viewpoint", why_pl: "Widok z gór na wyspy — wspinaczka lub wycieczka szosą.", why_en: "Mountain view over islands — hike or scenic road trip.", activity_slugs: ["viewpoints", "hiking_trails"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs na Hvar / Brač", name_en: "Hvar / Brač ferry", why_pl: "Prom z Makarskiej — dzień na sąsiedniej wyspie.", why_en: "Ferry from Makarska — day on neighbouring island.", activity_slugs: ["boat_tour"], rank: 1 },
    ],
  },
  {
    id: "hr-bol-brac",
    destination_keys: ["bol", "brac", "split", "dalmacja", "dalmatia", "chorwacja", "croatia"],
    slug: "bol-brac",
    name_pl: "Bol — Brač",
    name_en: "Bol — Brač",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Złoty Róg (Zlatni Rat) — najsłynniejsza plaża Chorwacji, wiatr i kitesurf latem.",
    overview_en: "Zlatni Rat — Croatia's most famous beach, wind and kitesurf in summer.",
    stay_hint_pl: "Bol centrum — wszystko pieszo do plaży i promu ze Splitu.",
    stay_hint_en: "Central Bol — walkable to beach and Split ferry.",
    center_lat: 43.26,
    center_lon: 16.66,
    picks: [
      { day_theme: "beach_relax", name_pl: "Zlatni Rat", name_en: "Zlatni Rat", why_pl: "Ruchomy język piasku — płytkie morze po obu stronach, ikona regionu.", why_en: "Shifting sand spit — shallow sea both sides, regional icon.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża w centrum Bol", name_en: "Central Bol beach", why_pl: "Kameralna zatoczka w porcie — spokojniejsza niż Zlatni Rat.", why_en: "Intimate harbour cove — calmer than Zlatni Rat.", activity_slugs: ["rocky_beaches"], rank: 2 },
      { day_theme: "active_outdoor", name_pl: "Windsurf / paddle", name_en: "Windsurf & paddle", why_pl: "Maestral wieje popołudniami — szkoły przy Zlatni Rat.", why_en: "Maestral blows afternoons — schools at Zlatni Rat.", activity_slugs: ["kayaking"], rank: 1 },
      { day_theme: "nature", name_pl: "Vidova Gora", name_en: "Vidova Gora", why_pl: "Najwyższy szczyt wyspy — panorama na Zlatni Rat z góry.", why_en: "Island's highest peak — Zlatni Rat panorama from above.", activity_slugs: ["viewpoints", "hiking_trails"], rank: 1 },
    ],
  },

  // --- Inne ---
  {
    id: "me-budva-riviera",
    destination_keys: ["budva", "becici", "petrovac", "czarnogora", "montenegro"],
    slug: "budva-riviera",
    name_pl: "Riwiera Budva",
    name_en: "Budva Riviera",
    character: "resort",
    vibe: "popular",
    overview_pl: "Stare miasto Budva, plaże Bečići i Jaz — najpopularniejszy odcinek wybrzeża Czarnogóry.",
    overview_en: "Old Budva, Bečići and Jaz beaches — Montenegro's most popular coast.",
    stay_hint_pl: "Bečići na długą plażę z dziećmi; Petrovac spokojniej na południe.",
    stay_hint_en: "Bečići for long kid-friendly beach; Petrovac quieter to the south.",
    center_lat: 42.29,
    center_lon: 18.84,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Bečići", name_en: "Bečići beach", why_pl: "Długi piasek i płytkie morze — ulubiona plaża wśród rodzin w regionie.", why_en: "Long sand and shallow sea — regional family favourite.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Jaz", name_en: "Jaz beach", why_pl: "Szeroka plaża z infrastrukturą — koncerty latem, dobra z dziećmi.", why_en: "Wide equipped beach — summer events, good with kids.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Stare miasto Budva", name_en: "Budva old town", why_pl: "Mur miejski i uliczki — kolacja po plażowaniu.", why_en: "Town walls and lanes — post-beach dinner.", activity_slugs: ["old_towns", "castles"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs do Sveti Stefan", name_en: "Sveti Stefan boat", why_pl: "Ikoniczna wysepka — łodzie z Budvy, zdjęcia i kąpiel.", why_en: "Iconic islet — boats from Budva, photos and swim.", activity_slugs: ["boat_tour", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "me-kotor-bay",
    destination_keys: ["kotor", "perast", "tivat", "czarnogora", "montenegro"],
    slug: "kotor-bay",
    name_pl: "Zatoka Kotorska",
    name_en: "Bay of Kotor",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Fiord Adriatyku — Kotor UNESCO, Perast i plaże Dobrota — dramatyczne krajobrazy nad spokojną wodą.",
    overview_en: "Adriatic fjord — UNESCO Kotor, Perast and Dobrota beaches — dramatic scenery on calm water.",
    stay_hint_pl: "Dobrota / Kotor na zwiedzanie; Herceg Novi na północ zatoki i plaże.",
    stay_hint_en: "Dobrota / Kotor for sights; Herceg Novi for north bay beaches.",
    center_lat: 42.42,
    center_lon: 18.77,
    picks: [
      { day_theme: "city_culture", name_pl: "Stare miasto Kotor", name_en: "Kotor old town", why_pl: "Forteca i labirynt ulic — wspinaczka na mury z widokiem na zatokę.", why_en: "Fortress and lane maze — rampart climb with bay views.", activity_slugs: ["old_towns", "castles"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Dobrota", name_en: "Dobrota beach", why_pl: "Kamienista plaża w zatoce — spokojna woda, blisko Kotoru.", why_en: "Pebbly bay beach — calm water, near Kotor.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Perast i wysepki", name_en: "Perast islets", why_pl: "Barokowe Perast — łódka na Our Lady of the Rocks.", why_en: "Baroque Perast — boat to Our Lady of the Rocks.", activity_slugs: ["old_towns", "boat_tour"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs po zatoce", name_en: "Bay cruise", why_pl: "Całodniowy rejs — Blue Cave i pływanie w ukrytych zatokach.", why_en: "Full-day cruise — Blue Cave and hidden cove swimming.", activity_slugs: ["boat_tour", "snorkeling"], rank: 1 },
    ],
  },
  {
    id: "bg-sozopol-black-sea",
    destination_keys: ["sozopol", "nessebar", "burgas", "bulgaria", "bułgaria"],
    slug: "sozopol-black-sea",
    name_pl: "Sozopol — Morze Czarne",
    name_en: "Sozopol — Black Sea",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Stary Sozopol na półwyspie, złote plaże i Nesebar w zasięgu autobusu — tańsze Morze Czarne z dziećmi.",
    overview_en: "Peninsula old Sozopol, golden beaches and Nesebar by bus — affordable Black Sea with kids.",
    stay_hint_pl: "Stary Sozopol na klimat; nowy Sozopol na dłuższe plaże i hotele.",
    stay_hint_en: "Old Sozopol for charm; new Sozopol for longer beaches and hotels.",
    center_lat: 42.42,
    center_lon: 27.69,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Harmanite", name_en: "Harmanite beach", why_pl: "Piaszczysta plaża w nowym Sozopolu — płytkie morze, pełna infrastruktura.", why_en: "Sandy new Sozopol beach — shallow sea, full facilities.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża na półwyspie", name_en: "Peninsula beach", why_pl: "Małe zatoczki przy starym mieście — kąpiel z widokiem na domy w drewnie.", why_en: "Small coves by old town — swim with wooden-house views.", activity_slugs: ["rocky_beaches"], rank: 2 },
      { day_theme: "city_culture", name_pl: "Stary Sozopol", name_en: "Old Sozopol", why_pl: "Drewniane domy i ruiny — wieczorny spacer po kolacji rybnej.", why_en: "Wooden houses and ruins — evening walk after fish dinner.", activity_slugs: ["old_towns", "archaeology"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Nesebar (wycieczka)", name_en: "Nesebar day trip", why_pl: "UNESCO na wyspie — kościoły i promenada, autobus z Sozopolu.", why_en: "UNESCO island — churches and promenade, bus from Sozopol.", activity_slugs: ["old_towns"], rank: 1 },
    ],
  },
];
