import type { TouristRegion } from "./tourist-regions";

const CZ_KEYS = ["czechy", "czech", "czechia", "cesko", "czech republic"] as const;

/** Czechy — ~30 regionów turystycznych; promień bazowy skaluje się automatycznie dla kraju. */
export const SEED_TOURIST_REGIONS_CZECH: TouristRegion[] = [
  {
    id: "cz-prague-centre",
    destination_keys: ["praga", "prague", "praha", ...CZ_KEYS],
    slug: "prague-centre",
    name_pl: "Praga — centrum",
    name_en: "Prague — city centre",
    character: "historic",
    vibe: "popular",
    overview_pl: "Most Karola, Zamek i Stare Miasto — baśniowa stolica Europy Środkowej.",
    overview_en: "Charles Bridge, Castle and Old Town — fairytale Central European capital.",
    stay_hint_pl: "Malá Strana lub Stare Miasto — metro i tramwaje.",
    stay_hint_en: "Malá Strana or Old Town — metro and trams.",
    center_lat: 50.08,
    center_lon: 14.44,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Most Karola", name_en: "Charles Bridge", why_pl: "Rzeźby o świcie — najmniej tłumów.", why_en: "Statues at dawn — fewest crowds.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Praski Zamek", name_en: "Prague Castle", why_pl: "Katedra św. Wita — największy kompleks zamkowy świata.", why_en: "St Vitus Cathedral — world's largest castle complex.", activity_slugs: ["castles", "old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Trasa Vltava — centrum", name_en: "Vltava riverside ride", why_pl: "Płaska ścieżka wzdłuż rzeki — idealna na rozgrzewkę.", why_en: "Flat riverside path — ideal warmup ride.", activity_slugs: ["bike_rental"], rank: 1 },
    ],
  },
  {
    id: "cz-karlstejn-berounka",
    destination_keys: ["karlstejn", "karlštejn", "beroun", ...CZ_KEYS],
    slug: "karlstejn-berounka",
    name_pl: "Karlštejn i dolina Berounky",
    name_en: "Karlštejn & Berounka valley",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Zamek Karla IV i spokojne trasy wzdłuż Berounky — wypad z Pragi w 40 min.",
    overview_en: "Charles IV castle and quiet Berounka valley routes — 40 min from Prague.",
    stay_hint_pl: "Karlštejn lub Beroun — baza na pętle w dolinie.",
    stay_hint_en: "Karlštejn or Beroun — valley loop base.",
    center_lat: 49.94,
    center_lon: 14.18,
    radius_km: 14,
    picks: [
      { day_theme: "city_culture", name_pl: "Zamek Karlštejn", name_en: "Karlštejn Castle", why_pl: "Gotycki klejnot Czech — rezerwuj bilety z wyprzedzeniem.", why_en: "Gothic Czech gem — book tickets ahead.", activity_slugs: ["castles", "old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Pętla doliny Berounky", name_en: "Berounka valley loop", why_pl: "Łagodna trasa rowerowa wzdłuż rzeki.", why_en: "Gentle riverside cycling loop.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
      { day_theme: "nature", name_pl: "Český kras — jaskinie", name_en: "Bohemian Karst caves", why_pl: "Koněprusy lub jaskinie w okolicy — chłodna alternatywa.", why_en: "Koněprusy or nearby caves — cool alternative.", activity_slugs: ["caves"], rank: 2 },
    ],
  },
  {
    id: "cz-kutna-hora",
    destination_keys: ["kutna hora", "kutná hora", ...CZ_KEYS],
    slug: "kutna-hora",
    name_pl: "Kutná Hora",
    name_en: "Kutná Hora",
    character: "historic",
    vibe: "balanced",
    overview_pl: "UNESCO — kościół św. Barbary i Kaplica Czaszek, dawne srebrne kopalnie.",
    overview_en: "UNESCO — St Barbara's church, Bone Chapel and former silver mines.",
    stay_hint_pl: "Centrum Kutnej Hory — spacer do kościołów.",
    stay_hint_en: "Kutná Hora centre — walk to churches.",
    center_lat: 49.95,
    center_lon: 15.28,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Kościół św. Barbary", name_en: "St Barbara's Church", why_pl: "Gotycka perła — widok na dolinę.", why_en: "Gothic pearl — valley views.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Sedlec — Kaplica Czaszek", name_en: "Sedlec Ossuary", why_pl: "Unikalna dekoracja z kości — 10 min od centrum.", why_en: "Unique bone decoration — 10 min from centre.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Trasy wokół miasta", name_en: "Surrounding bike routes", why_pl: "Spokojne drogi między winnicami i polami.", why_en: "Quiet roads between vineyards and fields.", activity_slugs: ["bike_rental"], rank: 1 },
    ],
  },
  {
    id: "cz-jicin-cesky-raj",
    destination_keys: ["jicin", "jičín", "cesky raj", "český ráj", ...CZ_KEYS],
    slug: "jicin-cesky-raj",
    name_pl: "Jičín i Český ráj",
    name_en: "Jičín & Bohemian Paradise",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Piaskowcowe skały, zamki Valdštejn i Prachovské skály — raj dla wędrówek i roweru.",
    overview_en: "Sandstone rocks, Valdštejn castle and Prachov rocks — hiking and cycling paradise.",
    stay_hint_pl: "Jičín lub Turnov — baza na skały i zamki.",
    stay_hint_en: "Jičín or Turnov — rocks and castles base.",
    center_lat: 50.35,
    center_lon: 15.35,
    radius_km: 16,
    picks: [
      { day_theme: "nature", name_pl: "Prachovské skály", name_en: "Prachov Rocks", why_pl: "Wąskie przejścia między skałami — 2–3 h spaceru.", why_en: "Narrow rock passages — 2–3 h walk.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Zamek Valdštejn", name_en: "Valdštejn Castle", why_pl: "Ruiny w skałach — krótki dojazd z Jičína.", why_en: "Cliff-top ruins — short drive from Jičín.", activity_slugs: ["castles"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Trasy Český ráj", name_en: "Bohemian Paradise routes", why_pl: "Pagórkowate pętle między zamkami.", why_en: "Rolling loops between castles.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cz-liberec-jizera",
    destination_keys: ["liberec", "jizera", "jizerske hory", ...CZ_KEYS],
    slug: "liberec-jizera",
    name_pl: "Liberec i Góry Izerskie",
    name_en: "Liberec & Jizera Mountains",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Ještěd, zoo i łagodne trasy w Górach Izerskich — blisko granicy z Polską.",
    overview_en: "Ještěd tower, zoo and gentle Jizera Mountains routes — near the Polish border.",
    stay_hint_pl: "Liberec centrum — tramwaj na Ještěd.",
    stay_hint_en: "Liberec centre — tram to Ještěd.",
    center_lat: 50.77,
    center_lon: 15.06,
    radius_km: 14,
    picks: [
      { day_theme: "city_culture", name_pl: "Ještěd", name_en: "Ještěd tower", why_pl: "Ikoniczna wieża nad miastem — widok 360°.", why_en: "Iconic tower above town — 360° views.", activity_slugs: ["viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Jizera trail", name_en: "Jizera trail", why_pl: "Łagodne leśne trasy rowerowe na płaskowyżu.", why_en: "Gentle forest bike trails on the plateau.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
      { day_theme: "nature", name_pl: "Jeziora Izerskie", name_en: "Jizera lakes", why_pl: "Spokojne szlaki między stawami — idealne na pół dnia.", why_en: "Calm trails between ponds — half-day outing.", activity_slugs: ["hiking_trails"], rank: 2 },
    ],
  },
  {
    id: "cz-adrspach-rocks",
    destination_keys: ["adrspach", "adršpach", "nachod", ...CZ_KEYS],
    slug: "adrspach-rocks",
    name_pl: "Adršpach — skalne miasto",
    name_en: "Adršpach rock town",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Wąskie kaniony i monumentalne słupy piaskowca — jeden z najbardziej fotogenicznych rejonów Czech.",
    overview_en: "Narrow gorges and monumental sandstone pillars — one of Czechia's most photogenic areas.",
    stay_hint_pl: "Adršpach lub Broumov — wcześnie rano mniej tłumów.",
    stay_hint_en: "Adršpach or Broumov — go early to avoid crowds.",
    center_lat: 50.62,
    center_lon: 16.12,
    radius_km: 14,
    picks: [
      { day_theme: "nature", name_pl: "Skalne miasto Adršpach", name_en: "Adršpach rock city", why_pl: "Szlak między skałami — rezerwuj wejście online.", why_en: "Trail between rocks — book entry online.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Trasy do Broumova", name_en: "Routes toward Broumov", why_pl: "Spokojne drogi wzdłuż granicy PL/CZ.", why_en: "Quiet roads along the PL/CZ border.", activity_slugs: ["bike_rental"], rank: 1 },
      { day_theme: "nature", name_pl: "Stołowe Góry (okolica)", name_en: "Table Mountains area", why_pl: "Krótka wycieczka do szczytów stołowych.", why_en: "Short trip to table-top summits.", activity_slugs: ["hiking_trails"], rank: 2 },
    ],
  },
  {
    id: "cz-hradec-kralove",
    destination_keys: ["hradec kralove", "hradec králové", ...CZ_KEYS],
    slug: "hradec-kralove",
    name_pl: "Hradec Králové",
    name_en: "Hradec Králové",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Salon Czech — modernistyczna architektura nad Łabą i brama do Karkonoszy.",
    overview_en: "Salon of Czechia — modernist architecture on the Elbe and gateway to the Giant Mountains.",
    stay_hint_pl: "Centrum nad rzeką — blisko dworca i deptaka.",
    stay_hint_en: "Riverside centre — near station and promenade.",
    center_lat: 50.21,
    center_lon: 15.83,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Stare miasto nad Łabą", name_en: "Old town on the Elbe", why_pl: "Biała wieża i katedra — spacer 2 h.", why_en: "White Tower and cathedral — 2 h walk.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Ścieżka nad Łabą", name_en: "Elbe riverside path", why_pl: "Płaska trasa rowerowa wzdłuż rzeki.", why_en: "Flat cycling along the Elbe.", activity_slugs: ["bike_rental"], rank: 1 },
      { day_theme: "nature", name_pl: "Kuks — szpital barokowy", name_en: "Kuks Baroque hospital", why_pl: "Unikalny kompleks w dolinie — 30 min jazdy.", why_en: "Unique valley complex — 30 min drive.", activity_slugs: ["old_towns"], rank: 2 },
    ],
  },
  {
    id: "cz-karlovy-vary",
    destination_keys: ["karlovy vary", "carlsbad", ...CZ_KEYS],
    slug: "karlovy-vary",
    name_pl: "Karlowe Wary",
    name_en: "Karlovy Vary",
    character: "historic",
    vibe: "popular",
    overview_pl: "Kolonady, źródła termalne i filmowy festiwal — klasyczne uzdrowisko z widokami na Teplą.",
    overview_en: "Colonnades, thermal springs and film festival — classic spa town on the Teplá.",
    stay_hint_pl: "Centrum kolonad — spacer między źródłami.",
    stay_hint_en: "Colonnade centre — stroll between springs.",
    center_lat: 50.23,
    center_lon: 12.87,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Mill Colonnade", name_en: "Mill Colonnade", why_pl: "Serce kurortu — degustacja wód mineralnych.", why_en: "Spa heart — mineral water tasting.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Diana — wjazd rowerem", name_en: "Diana lookout ride", why_pl: "Krótki wjazd na punkt widokowy nad miastem.", why_en: "Short climb to lookout above town.", activity_slugs: ["bike_rental"], rank: 1 },
      { day_theme: "nature", name_pl: "Loket — zamek nad Ohří", name_en: "Loket castle", why_pl: "Średniowieczne miasto w meandzie rzeki — 15 min.", why_en: "Medieval town in river bend — 15 min.", activity_slugs: ["castles", "old_towns"], rank: 2 },
    ],
  },
  {
    id: "cz-jachymov-ore-mountains",
    destination_keys: ["jachymov", "jáchymov", "krusne hory", "krušné hory", ...CZ_KEYS],
    slug: "jachymov-ore-mountains",
    name_pl: "Jáchymov i Krušné hory",
    name_en: "Jáchymov & Ore Mountains",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Górnicza historia, termy i pagórkowate trasy w Krušných horách.",
    overview_en: "Mining history, spas and rolling routes in the Ore Mountains.",
    stay_hint_pl: "Jáchymov lub Ostrov — baza na pętle w górach.",
    stay_hint_en: "Jáchymov or Ostrov — mountain loop base.",
    center_lat: 50.36,
    center_lon: 12.94,
    radius_km: 16,
    picks: [
      { day_theme: "city_culture", name_pl: "Muzeum górnictwa uranu", name_en: "Uranium mining museum", why_pl: "Historia regionu — krótka wizyta przed trasą.", why_en: "Regional history — short visit before riding.", activity_slugs: ["museums"], rank: 2 },
      { day_theme: "active_outdoor", name_pl: "Trasy Krušných hor", name_en: "Ore Mountains routes", why_pl: "Łagodne wzniesienia i leśne drogi.", why_en: "Gentle climbs and forest roads.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
      { day_theme: "nature", name_pl: "Klínovec (widok)", name_en: "Klínovec viewpoint", why_pl: "Najwyższy szczyt Krušných hor — transfer na start.", why_en: "Highest Ore Mountains peak — transfer to start.", activity_slugs: ["viewpoints", "hiking_trails"], rank: 1 },
    ],
  },
  {
    id: "cz-plzen",
    destination_keys: ["plzen", "plzeň", "pilsen", ...CZ_KEYS],
    slug: "plzen",
    name_pl: "Plzeň",
    name_en: "Plzeň",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Pilsner Urquell, katedra św. Bartłomieja i brama do zachodnich Czech.",
    overview_en: "Pilsner Urquell, St Bartholomew's cathedral and gateway to western Bohemia.",
    stay_hint_pl: "Centrum — browar i rynek w zasięgu spaceru.",
    stay_hint_en: "Centre — brewery and square within walking distance.",
    center_lat: 49.75,
    center_lon: 13.38,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Browar Pilsner Urquell", name_en: "Pilsner Urquell brewery", why_pl: "Degustacja z piwnicy — rezerwuj z wyprzedzeniem.", why_en: "Cellar tasting — book ahead.", activity_slugs: ["museums", "old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Rynek i katedra", name_en: "Square & cathedral", why_pl: "Największy plac w Czechach — wieża z widokiem.", why_en: "Czechia's largest square — tower views.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rokytka i okolice", name_en: "Rokytka area rides", why_pl: "Spokojne trasy za miastem — łatwy dojazd.", why_en: "Quiet routes beyond the city — easy access.", activity_slugs: ["bike_rental"], rank: 1 },
    ],
  },
  {
    id: "cz-ceske-budejovice",
    destination_keys: ["ceske budejovice", "české budějovice", "budejovice", ...CZ_KEYS],
    slug: "ceske-budejovice",
    name_pl: "Czeskie Budziejowice",
    name_en: "České Budějovice",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Budvar, rynek Otakara II i baza na południowe Czechy i Austria.",
    overview_en: "Budvar beer, Otakar II square and base for south Bohemia and Austria.",
    stay_hint_pl: "Centrum przy rynku — tramwaje do okolicy.",
    stay_hint_en: "Square centre — trams to surroundings.",
    center_lat: 48.98,
    center_lon: 14.47,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Rynek Otakara II", name_en: "Otakar II square", why_pl: "Jeden z największych rynków — kolorowe kamienice.", why_en: "One of the largest squares — colourful façades.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Browar Budvar", name_en: "Budvar brewery", why_pl: "Wycieczka z degustacją — klasyk regionu.", why_en: "Tour with tasting — regional classic.", activity_slugs: ["museums"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Trasy nad Vltavou", name_en: "Vltava routes", why_pl: "Płaskie odcinki wzdłuż rzeki na południe.", why_en: "Flat riverside sections heading south.", activity_slugs: ["bike_rental"], rank: 1 },
    ],
  },
  {
    id: "cz-cesky-krumlov",
    destination_keys: ["cesky krumlov", "český krumlov", "krumlov", ...CZ_KEYS],
    slug: "cesky-krumlov",
    name_pl: "Český Krumlov",
    name_en: "Český Krumlov",
    character: "historic",
    vibe: "balanced",
    overview_pl: "UNESCO miasto nad meandrem Vltavy — zamek, teatr i spokojniejsza alternatywa dla Pragi.",
    overview_en: "UNESCO town on Vltava bend — castle, theatre and calmer Prague alternative.",
    stay_hint_pl: "Centrum w obrębie murów — 1–2 noce minimum.",
    stay_hint_en: "Centre within walls — 1–2 nights minimum.",
    center_lat: 48.81,
    center_lon: 14.32,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Zamek Krumlov", name_en: "Krumlov Castle", why_pl: "Barokowy teatr i ogrody — rezerwacja teatru.", why_en: "Baroque theatre and gardens — theatre booking.", activity_slugs: ["castles", "old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Stare Miasto", name_en: "Old Town", why_pl: "Wąskie uliczki nad rzeką — spacer wieczorem.", why_en: "Narrow riverside lanes — evening stroll.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Spływ i trasy Vltava", name_en: "Vltava rafting & rides", why_pl: "Spokojny spływ latem lub trasa rowerowa w dolinie.", why_en: "Gentle summer float or valley bike route.", activity_slugs: ["boat_tour", "bike_rental"], rank: 1 },
    ],
  },
  {
    id: "cz-pisek",
    destination_keys: ["pisek", "písek", ...CZ_KEYS],
    slug: "pisek",
    name_pl: "Písek — most kamienny",
    name_en: "Písek — stone bridge",
    character: "historic",
    vibe: "offbeat",
    overview_pl: "Najstarszy most w Czechach, Otava i spokojne południowe Czechy.",
    overview_en: "Czechia's oldest bridge, Otava river and quiet south Bohemia.",
    stay_hint_pl: "Centrum nad Otavą — kameralna baza.",
    stay_hint_en: "Otava riverside centre — intimate base.",
    center_lat: 49.31,
    center_lon: 14.15,
    radius_km: 14,
    picks: [
      { day_theme: "city_culture", name_pl: "Kamienny most", name_en: "Stone bridge", why_pl: "Gotycki most z XIII w. — symbol miasta.", why_en: "13th-century Gothic bridge — town symbol.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Dolina Otavy", name_en: "Otava valley ride", why_pl: "Łagodna trasa wzdłuż rzeki.", why_en: "Gentle route along the river.", activity_slugs: ["bike_rental"], rank: 1 },
      { day_theme: "nature", name_pl: "Zábělí — rezerwat", name_en: "Zábělí reserve", why_pl: "Spacer nad brzegiem Otavy.", why_en: "Riverside nature walk.", activity_slugs: ["hiking_trails"], rank: 2 },
    ],
  },
  {
    id: "cz-tabor",
    destination_keys: ["tabor", "tábor", ...CZ_KEYS],
    slug: "tabor",
    name_pl: "Tábor — miasto husytów",
    name_en: "Tábor — Hussite town",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Labirynt podziemi, jezioro Jordan i historia ruchu husyckiego.",
    overview_en: "Underground labyrinth, Jordan lake and Hussite movement history.",
    stay_hint_pl: "Stare miasto na wzgórzu — widok na okolicę.",
    stay_hint_en: "Hilltop old town — countryside views.",
    center_lat: 49.41,
    center_lon: 14.66,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Podziemia Tabora", name_en: "Tábor underground", why_pl: "Sieć tuneli pod miastem — wycieczka z przewodnikiem.", why_en: "Tunnel network under town — guided tour.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Jezioro Jordan — trasa", name_en: "Jordan lake loop", why_pl: "Krótka pętla wokół najstarszego sztucznego zbiornika.", why_en: "Short loop around the oldest artificial reservoir.", activity_slugs: ["bike_rental", "hiking_trails"], rank: 1 },
      { day_theme: "nature", name_pl: "Blatské rybníky", name_en: "Blatské ponds", why_pl: "Spokojne szlaki między stawami rybactwa.", why_en: "Calm trails between fish ponds.", activity_slugs: ["hiking_trails"], rank: 2 },
    ],
  },
  {
    id: "cz-jihlava",
    destination_keys: ["jihlava", ...CZ_KEYS],
    slug: "jihlava",
    name_pl: "Jihlava — Vysočina",
    name_en: "Jihlava — Vysočina",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Stare miasto na granicy Moraw i Czech, wieże bramne i pagórki Vysočiny.",
    overview_en: "Old town on Moravia-Bohemia border, gate towers and Vysočina hills.",
    stay_hint_pl: "Centrum — baza na Moravę i Telč.",
    stay_hint_en: "Centre — base for Moravia and Telč.",
    center_lat: 49.4,
    center_lon: 15.59,
    radius_km: 14,
    picks: [
      { day_theme: "city_culture", name_pl: "Stare miasto Jihlava", name_en: "Jihlava old town", why_pl: "Wieże bramne i podziemne korytarze.", why_en: "Gate towers and underground corridors.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Wzgórza Vysočiny", name_en: "Vysočina hills", why_pl: "Pagórkowate trasy między polami i lasami.", why_en: "Rolling routes between fields and forests.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
      { day_theme: "nature", name_pl: "Telč (wycieczka)", name_en: "Telč day trip", why_pl: "UNESCO rynek — 30 min jazdy.", why_en: "UNESCO square — 30 min drive.", activity_slugs: ["old_towns"], rank: 2 },
    ],
  },
  {
    id: "cz-telc",
    destination_keys: ["telc", "telč", ...CZ_KEYS],
    slug: "telc",
    name_pl: "Telč — UNESCO",
    name_en: "Telč — UNESCO",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Renesansowy rynek otoczony kolorowymi kamienicami i stawami — perła Vysočiny.",
    overview_en: "Renaissance square with colourful houses and ponds — Vysočina gem.",
    stay_hint_pl: "Nocleg przy rynku — wieczorny spacer bez tłumów.",
    stay_hint_en: "Stay on the square — evening stroll without crowds.",
    center_lat: 49.18,
    center_lon: 15.45,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Rynek Zachariasza", name_en: "Zacharias square", why_pl: "Jeden z najpiękniejszych rynków Czech.", why_en: "One of Czechia's most beautiful squares.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Zamek Telč", name_en: "Telč Castle", why_pl: "Renesansowy pałac z ogrodami.", why_en: "Renaissance palace with gardens.", activity_slugs: ["castles"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Trasy wokół stawów", name_en: "Pond loop rides", why_pl: "Płaskie pętle wokół renesansowych sadzawek.", why_en: "Flat loops around Renaissance ponds.", activity_slugs: ["bike_rental"], rank: 1 },
    ],
  },
  {
    id: "cz-trebic",
    destination_keys: ["trebic", "třebíč", ...CZ_KEYS],
    slug: "trebic",
    name_pl: "Třebíč — żydowska dzielnica",
    name_en: "Třebíč — Jewish quarter",
    character: "historic",
    vibe: "offbeat",
    overview_pl: "UNESCO — zachowana dzielnica żydowska i bazylika św. Prokopa.",
    overview_en: "UNESCO — preserved Jewish quarter and St Procopius basilica.",
    stay_hint_pl: "Centrum — wszystko w zasięgu spaceru.",
    stay_hint_en: "Centre — everything walkable.",
    center_lat: 49.21,
    center_lon: 15.88,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Dzielnica żydowska", name_en: "Jewish quarter", why_pl: "Labirynt uliczek i synagoga — unikalne UNESCO.", why_en: "Lane labyrinth and synagogue — unique UNESCO.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Bazylika św. Prokopa", name_en: "St Procopius basilica", why_pl: "Romańska architektura nad Jihlavou.", why_en: "Romanesque architecture above the Jihlava.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Dolina Jihlavy", name_en: "Jihlava valley ride", why_pl: "Spokojna trasa wzdłuż rzeki.", why_en: "Quiet riverside route.", activity_slugs: ["bike_rental"], rank: 1 },
    ],
  },
  {
    id: "cz-brno",
    destination_keys: ["brno", "moravia", "morawy", ...CZ_KEYS],
    slug: "brno",
    name_pl: "Brno — stolica Moraw",
    name_en: "Brno — Moravia capital",
    character: "historic",
    vibe: "popular",
    overview_pl: "Katedra św. Piotra i Pawła, willa Tugendhat (UNESCO) i życie studenckie.",
    overview_en: "Cathedral of St Peter and Paul, Tugendhat Villa (UNESCO) and student life.",
    stay_hint_pl: "Centrum lub Černá Pole — tramwaje wszędzie.",
    stay_hint_en: "Centre or Černá Pole — trams everywhere.",
    center_lat: 49.19,
    center_lon: 16.61,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Katedra na Petrovie", name_en: "Petrov cathedral", why_pl: "Ikona panoramy Brna — dzwony południowe.", why_en: "Brno skyline icon — noon bells.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Willa Tugendhat", name_en: "Tugendhat Villa", why_pl: "Modernizm UNESCO — bilety obowiązkowe z wyprzedzeniem.", why_en: "UNESCO modernism — tickets required in advance.", activity_slugs: ["museums"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Brno reservoir loop", name_en: "Brno reservoir loop", why_pl: "Popularna pętla wokół zbiornika — mix asfaltu i terenu.", why_en: "Popular reservoir loop — mixed tarmac and terrain.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cz-moravian-karst",
    destination_keys: ["moravian karst", "moravsky kras", "moravský kras", "blansko", ...CZ_KEYS],
    slug: "moravian-karst",
    name_pl: "Morawski Kras",
    name_en: "Moravian Karst",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Propast Macocha, jaskinie Punkevní i wąskotorówka — jeden z największych systemów krasowych Europy.",
    overview_en: "Macocha abyss, Punkevní caves and narrow-gauge railway — major European karst.",
    stay_hint_pl: "Blansko lub Adamov — blisko wejść do jaskiń.",
    stay_hint_en: "Blansko or Adamov — near cave entrances.",
    center_lat: 49.37,
    center_lon: 16.72,
    radius_km: 16,
    picks: [
      { day_theme: "nature", name_pl: "Propast Macocha", name_en: "Macocha abyss", why_pl: "138 m głębokości — platformy widokowe.", why_en: "138 m deep — viewing platforms.", activity_slugs: ["caves", "viewpoints"], rank: 1 },
      { day_theme: "nature", name_pl: "Jaskinie Punkevní", name_en: "Punkva caves", why_pl: "Rejs łodzią pod ziemią — rezerwuj online.", why_en: "Underground boat ride — book online.", activity_slugs: ["caves", "boat_tour"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Trasy nad krasem", name_en: "Karst area rides", why_pl: "Pagórkowate drogi między wąwozami.", why_en: "Rolling roads between gorges.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cz-olomouc",
    destination_keys: ["olomouc", "olomunec", ...CZ_KEYS],
    slug: "olomouc",
    name_pl: "Ołomuniec",
    name_en: "Olomouc",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Barokowa kolumna Trójcy Świętej (UNESCO), ratusz i słynne serki olomoucké.",
    overview_en: "Holy Trinity Column (UNESCO), town hall and famous Olomouc cheese.",
    stay_hint_pl: "Centrum historyczne — kompaktowe i kameralne.",
    stay_hint_en: "Historic centre — compact and intimate.",
    center_lat: 49.59,
    center_lon: 17.25,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Kolumna Trójcy Świętej", name_en: "Holy Trinity Column", why_pl: "Monumentalne barokowe UNESCO na rynku.", why_en: "Monumental baroque UNESCO on the square.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Ratusz z astronom. zegarem", name_en: "Astronomical clock town hall", why_pl: "Mniej znany niż praski — ale równie efektowny.", why_en: "Less famous than Prague's — equally striking.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Trasy Haná", name_en: "Haná region rides", why_pl: "Płaskie drogi na wschód od miasta.", why_en: "Flat roads east of the city.", activity_slugs: ["bike_rental"], rank: 1 },
    ],
  },
  {
    id: "cz-kromeriz",
    destination_keys: ["kromeriz", "kroměříž", ...CZ_KEYS],
    slug: "kromeriz",
    name_pl: "Kroměříž — ogrody UNESCO",
    name_en: "Kroměříž — UNESCO gardens",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Pałac arcybiskupów, Podwale Kwiatowe i barokowe ogrody — filmowa sceneria Amadeusza.",
    overview_en: "Archbishop's palace, Flower Garden and baroque grounds — Amadeus film set.",
    stay_hint_pl: "Centrum — blisko pałacu i ogrodów.",
    stay_hint_en: "Centre — near palace and gardens.",
    center_lat: 49.3,
    center_lon: 17.39,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Pałac i ogrody", name_en: "Palace & gardens", why_pl: "UNESCO kompleks — rezerwuj pałac z wyprzedzeniem.", why_en: "UNESCO complex — book palace ahead.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Podwale Kwiatowe", name_en: "Flower Garden", why_pl: "Symetryczne parterre — najlepsze wiosną.", why_en: "Symmetrical parterre — best in spring.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Dolina Morawy", name_en: "Morava valley ride", why_pl: "Płaska trasa wzdłuż rzeki na wschód.", why_en: "Flat route along the Morava eastward.", activity_slugs: ["bike_rental"], rank: 1 },
    ],
  },
  {
    id: "cz-litomysl",
    destination_keys: ["litomysl", "litomyšl", ...CZ_KEYS],
    slug: "litomysl",
    name_pl: "Litomyšl — zamek UNESCO",
    name_en: "Litomyšl — UNESCO castle",
    character: "historic",
    vibe: "offbeat",
    overview_pl: "Renesansowy zamek Smetany, kolorowe fasady i spokojne wschodnie Czechy.",
    overview_en: "Smetana's Renaissance castle, colourful façades and quiet eastern Bohemia.",
    stay_hint_pl: "Centrum — rynek i zamek w 10 min spaceru.",
    stay_hint_en: "Centre — square and castle within 10 min walk.",
    center_lat: 49.87,
    center_lon: 16.31,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Zamek Litomyšl", name_en: "Litomyšl Castle", why_pl: "Sgraffito i opera Smetany — UNESCO.", why_en: "Sgraffito and Smetana opera — UNESCO.", activity_slugs: ["castles", "museums"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Zabytkowe centrum", name_en: "Heritage centre", why_pl: "Zachowane kamienice i galerie.", why_en: "Preserved houses and galleries.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Trasy wokół Litomyšl", name_en: "Litomyšl area loops", why_pl: "Łagodne drogi przez pola i lasy.", why_en: "Gentle roads through fields and woods.", activity_slugs: ["bike_rental"], rank: 1 },
    ],
  },
  {
    id: "cz-ostrava",
    destination_keys: ["ostrava", "beskydy", ...CZ_KEYS],
    slug: "ostrava",
    name_pl: "Ostrawa i Beskidy",
    name_en: "Ostrava & Beskids",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Dolínek — industrialne dziedzictwo, Nowy Ratusz i brama do Beskidów.",
    overview_en: "Dolní Vítkovice heritage, New City Hall and gateway to the Beskids.",
    stay_hint_pl: "Centrum lub okolice Doliny Vitkovice — tramwaje i autobusy.",
    stay_hint_en: "Centre or Vítkovice area — trams and buses.",
    center_lat: 49.83,
    center_lon: 18.29,
    radius_km: 14,
    picks: [
      { day_theme: "city_culture", name_pl: "Dolínek (Vítkovice)", name_en: "Dolní Vítkovice", why_pl: "Huta przekształcona w kulturę — wieża widokowa.", why_en: "Steelworks turned culture — viewing tower.", activity_slugs: ["museums", "viewpoints"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Nowy Ratusz — taras", name_en: "New City Hall tower", why_pl: "Widok na aglomerację — najwyższa wieża w Czechach.", why_en: "Conurbation views — Czechia's tallest tower.", activity_slugs: ["viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Beskidy — wypad", name_en: "Beskids outing", why_pl: "Wjazdy w Beskidy na południe — mix asfaltu i szutru.", why_en: "Climbs into Beskids south — mixed surfaces.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
    ],
  },
  {
    id: "cz-znojmo",
    destination_keys: ["znojmo", ...CZ_KEYS],
    slug: "znojmo",
    name_pl: "Znojmo — winnice",
    name_en: "Znojmo — wine region",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Średniowieczne mury, podziemia i winnice nad Dyją — południowa Morawa.",
    overview_en: "Medieval walls, cellars and Dyje valley vineyards — south Moravia.",
    stay_hint_pl: "Stare miasto — degustacje w winiarniach podziemnych.",
    stay_hint_en: "Old town — tastings in underground wine cellars.",
    center_lat: 48.86,
    center_lon: 16.05,
    radius_km: 14,
    picks: [
      { day_theme: "city_culture", name_pl: "Podziemia Znojma", name_en: "Znojmo underground", why_pl: "Labirynt korytarzy pod miastem.", why_en: "Corridor labyrinth under the town.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Winnice nad Dyją", name_en: "Dyje valley vineyards", why_pl: "Pagórkowate trasy między winnicami.", why_en: "Rolling routes between vineyards.", activity_slugs: ["bike_rental"], rank: 1 },
      { day_theme: "nature", name_pl: "Podyjí — park narodowy", name_en: "Podyjí National Park", why_pl: "Wąwóz Dyje — widoki na Austrię.", why_en: "Dyje gorge — views into Austria.", activity_slugs: ["national_parks", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "cz-mikulov-palava",
    destination_keys: ["mikulov", "palava", "pálava", ...CZ_KEYS],
    slug: "mikulov-palava",
    name_pl: "Mikulov i Pálava",
    name_en: "Mikulov & Pálava",
    character: "mixed",
    vibe: "popular",
    overview_pl: "Zamek na wzgórzu, winne szlaki i wapienne wzgórza Pálavy — serce Moraw Południowych.",
    overview_en: "Hilltop castle, wine trails and Pálava limestone hills — south Moravia heart.",
    stay_hint_pl: "Mikulov centro — baza na degustacje i wspinaczkę na Pálavu.",
    stay_hint_en: "Mikulov centre — base for tastings and Pálava climbs.",
    center_lat: 48.81,
    center_lon: 16.64,
    radius_km: 14,
    picks: [
      { day_theme: "city_culture", name_pl: "Zamek Mikulov", name_en: "Mikulov Castle", why_pl: "Widok na winnice i Austrię.", why_en: "Views over vineyards and Austria.", activity_slugs: ["castles", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Winnica Pálava loop", name_en: "Pálava wine loop", why_pl: "Klasyczna pętla przez wzgórza i winnice.", why_en: "Classic loop through hills and vineyards.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
      { day_theme: "nature", name_pl: "Svatý kopek", name_en: "Svatý kopek", why_pl: "Punkt widokowy nad Mikulovem — krótki wjazd.", why_en: "Viewpoint above Mikulov — short climb.", activity_slugs: ["viewpoints", "hiking_trails"], rank: 2 },
    ],
  },
  {
    id: "cz-lednice-valtice",
    destination_keys: ["lednice", "valtice", "lednicko", ...CZ_KEYS],
    slug: "lednice-valtice",
    name_pl: "Lednice-Valtice",
    name_en: "Lednice-Valtice",
    character: "historic",
    vibe: "popular",
    overview_pl: "UNESCO kompleks pałacowo-parkowy Lichtensteinów — minaret, jeziora i setki kilometrów alei.",
    overview_en: "UNESCO Liechtenstein palace park — minaret, lakes and hundreds of km of avenues.",
    stay_hint_pl: "Lednice lub Valtice — wynajem roweru obowiązkowy.",
    stay_hint_en: "Lednice or Valtice — bike rental essential.",
    center_lat: 48.77,
    center_lon: 16.8,
    radius_km: 16,
    picks: [
      { day_theme: "city_culture", name_pl: "Pałac Lednice", name_en: "Lednice Palace", why_pl: "Neogotycki pałac w otoczeniu parku.", why_en: "Neo-Gothic palace in parkland.", activity_slugs: ["castles", "old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Szlak rowerowy Lichtenstein", name_en: "Liechtenstein bike trail", why_pl: "Płaska trasa między pałacami — idealna na cały dzień.", why_en: "Flat trail between palaces — ideal full day.", activity_slugs: ["bike_rental"], rank: 1 },
      { day_theme: "nature", name_pl: "Minaret w parku", name_en: "Park minaret", why_pl: "Orientalna wieża w środku Europy — widok z góry.", why_en: "Oriental tower in central Europe — top views.", activity_slugs: ["viewpoints"], rank: 2 },
    ],
  },
  {
    id: "cy-cz-bohemian-switzerland",
    destination_keys: ["bohemian switzerland", "ceske svycarsko", "české švýcarsko", "decin", "děčín", "hrensko", ...CZ_KEYS],
    slug: "bohemian-switzerland-cycling",
    name_pl: "Czeska Szwajcaria",
    name_en: "Bohemian Switzerland",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Piaskowcowe skały, Pravčicka brana i trasy rowerowe u granicy z Saksonią.",
    overview_en: "Sandstone rocks, Pravčická Gate and cycling routes on Saxon border.",
    stay_hint_pl: "Hřensko lub Děčín — baza nad Łabą.",
    stay_hint_en: "Hřensko or Děčín — Elbe base.",
    center_lat: 50.85,
    center_lon: 14.28,
    radius_km: 16,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Odcinek szlaku Łaby", name_en: "Elbe trail section", why_pl: "Płaska trasa wzdłuż rzeki.", why_en: "Flat riverside route.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
      { day_theme: "nature", name_pl: "Pravčicka brana", name_en: "Pravčická Gate walk", why_pl: "Krótka wędrówka do łuku skalnego.", why_en: "Short walk to rock arch.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 2 },
      { day_theme: "nature", name_pl: "Wąwóz Edmund", name_en: "Edmund Gorge", why_pl: "Rejs lub spacer między ścianami skał.", why_en: "Boat or walk between rock walls.", activity_slugs: ["boat_tour", "hiking_trails"], rank: 1 },
    ],
  },
  {
    id: "cy-cz-sumava",
    destination_keys: ["sumava", "šumava", "bohemian forest", "lipno", ...CZ_KEYS],
    slug: "sumava-cycling",
    name_pl: "Sumava",
    name_en: "Šumava",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Lasy Sumavy, Lipno i spokojne trasy — granica z Austrią i Niemcami.",
    overview_en: "Šumava forests, Lipno and quiet routes — Austrian and German border.",
    stay_hint_pl: "Klatovy lub Lipno — baza nad jeziorem.",
    stay_hint_en: "Klatovy or Lipno — lake base.",
    center_lat: 49,
    center_lon: 13.5,
    radius_km: 18,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Pętla wokół Lipna", name_en: "Lipno lake loop", why_pl: "Łagodna trasa wokół jeziora.", why_en: "Gentle lake loop.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Drogi leśne Boubín", name_en: "Boubín forest roads", why_pl: "Cieniste trasy w lesie — spokojne tempo.", why_en: "Shaded forest routes — easy pace.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 2 },
      { day_theme: "nature", name_pl: "Boubínský prales", name_en: "Boubín primeval forest", why_pl: "Rezerwat pierwotnego lasu — krótki szlak.", why_en: "Primeval forest reserve — short trail.", activity_slugs: ["national_parks", "hiking_trails"], rank: 1 },
    ],
  },
  {
    id: "cy-mk-cz-snezka",
    destination_keys: ["sněžka", "snezka", "sniezka", "krkonose", "krkonoše", ...CZ_KEYS],
    slug: "snezka-cycling",
    name_pl: "Śnieżka — Karkonosze",
    name_en: "Sněžka — Giant Mountains",
    character: "wild",
    vibe: "balanced",
    overview_pl: "1603 m — najwyższy szczyt Czech, wjazd pod Śnieżkę i trasy w Karkonoszach.",
    overview_en: "1603 m — Czechia's highest peak, climb toward Sněžka and Giant Mountains routes.",
    stay_hint_pl: "Pec pod Sněžkou — baza w Karkonoszach.",
    stay_hint_en: "Pec pod Sněžkou — Giant Mountains base.",
    center_lat: 50.74,
    center_lon: 15.74,
    radius_km: 16,
    picks: [
      { day_theme: "active_outdoor", name_pl: "Wjazd pod Śnieżkę", name_en: "Sněžka approach", why_pl: "Wjazd pod szczyt — granica PL/CZ.", why_en: "Climb toward summit — PL/CZ border.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 1 },
      { day_theme: "nature", name_pl: "Śnieżne Kotły", name_en: "Snow Cirques", why_pl: "Alpinijski krajobraz — spacer z Pecu.", why_en: "Alpine scenery — walk from Pec.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Trasy okolicę Karpacza", name_en: "Karpacz area routes", why_pl: "Pętle po obu stronach granicy.", why_en: "Loops on both sides of the border.", activity_slugs: ["bike_rental", "mountain_biking"], rank: 2 },
    ],
  },
  {
    id: "cz-usti-nad-labem",
    destination_keys: ["usti nad labem", "ústí nad labem", ...CZ_KEYS],
    slug: "usti-nad-labem",
    name_pl: "Ústí nad Labem",
    name_en: "Ústí nad Labem",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Střekov — zamek nad Łabą, most z okresu i brama do Czeskiej Szwajcarii.",
    overview_en: "Střekov castle above the Elbe, district bridge and gateway to Bohemian Switzerland.",
    stay_hint_pl: "Centrum nad rzeką — szybki dojazd do Hřenska.",
    stay_hint_en: "Riverside centre — quick access to Hřensko.",
    center_lat: 50.66,
    center_lon: 14.04,
    radius_km: 12,
    picks: [
      { day_theme: "city_culture", name_pl: "Zamek Střekov", name_en: "Střekov Castle", why_pl: "Ruiny nad Łabą — widok na most i dolinę.", why_en: "Ruins above the Elbe — bridge and valley views.", activity_slugs: ["castles", "viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Szlak Łaby — odcinek", name_en: "Elbe trail section", why_pl: "Płaska trasa w kierunku Děčína.", why_en: "Flat route toward Děčín.", activity_slugs: ["bike_rental"], rank: 1 },
      { day_theme: "nature", name_pl: "Vaňovský vodopád", name_en: "Vaňov waterfall", why_pl: "Wodospad w miejskiej dolinie — krótki spacer.", why_en: "Waterfall in urban gorge — short walk.", activity_slugs: ["waterfalls", "hiking_trails"], rank: 2 },
    ],
  },
];
