import type { TouristRegion } from "./tourist-regions";

/** Kuratorskie rejony Cypru — współrzędne centrum + promień na mapie (km). */
export const SEED_TOURIST_REGIONS_CYPRUS: TouristRegion[] = [
  {
    id: "cy-ayia-napa",
    destination_keys: [
      "ayia napa",
      "agia napa",
      "ajia napa",
      "protaras",
      "cypr",
      "cyprus",
    ],
    slug: "ayia-napa",
    name_pl: "Ayia Napa i Protaras",
    name_en: "Ayia Napa & Protaras",
    character: "resort",
    vibe: "popular",
    area_label_pl: "Wschodnie wybrzeże · ~45 min jazdy od lotniska Larnaca",
    area_label_en: "East coast · ~45 min drive from Larnaca airport",
    overview_pl:
      "Najsłynniejsze plaże wyspy — Nissi, Fig Tree Bay i turkusowa woda. Najlepsze, jeśli liczy się morze i atrakcje dla dzieci; wieczorem w Ayia Napa jest więcej ruchu niż w Protaras.",
    overview_en:
      "The island's most famous beaches — Nissi, Fig Tree Bay and turquoise water. Best if sea and family attractions matter; Ayia Napa is livelier at night than Protaras.",
    stay_hint_pl:
      "Protaras — spokojniej z rodziną i długa piaszczysta plaża; Ayia Napa — bliżej barów i wypożyczalni quadów.",
    stay_hint_en:
      "Protaras — quieter for families; Ayia Napa — closer to bars and quad rentals.",
    center_lat: 34.98,
    center_lon: 34.0,
    radius_km: 14,
    picks: [
      {
        day_theme: "beach_relax",
        name_pl: "Nissi Beach",
        name_en: "Nissi Beach",
        why_pl: "Płytka laguna i bary na plaży — klasyk Ayia Napa.",
        why_en: "Shallow lagoon and beach bars — Ayia Napa classic.",
        activity_slugs: ["sandy_beaches"],
        rank: 1,
      },
      {
        day_theme: "beach_relax",
        name_pl: "Fig Tree Bay (Protaras)",
        name_en: "Fig Tree Bay",
        why_pl: "Błękitna flaga, piaszczysta — idealna z dziećmi.",
        why_en: "Blue Flag sandy beach — ideal with kids.",
        activity_slugs: ["sandy_beaches"],
        rank: 2,
      },
      {
        day_theme: "nature",
        name_pl: "Cape Greco",
        name_en: "Cape Greco",
        why_pl: "Klifowe szlaki i jaskinie morskie — rower lub spacer.",
        why_en: "Cliff trails and sea caves — bike or walk.",
        activity_slugs: ["hiking_trails", "viewpoints"],
        rank: 1,
      },
    ],
  },
  {
    id: "cy-paphos",
    destination_keys: ["pafos", "paphos", "cyprus", "cypr"],
    slug: "paphos-coast",
    name_pl: "Pafos i zachodnie wybrzeże",
    name_en: "Paphos & west coast",
    character: "mixed",
    vibe: "balanced",
    area_label_pl: "Zachód wyspy · lotnisko Pafos (PFO) w regionie",
    area_label_en: "West coast · Paphos airport (PFO) in the area",
    overview_pl:
      "Plaże Coral Bay, ruiny rzymskie UNESCO i spokojniejsze tempo niż Ayia Napa. Dobry wybór na mix plażowania i zwiedzania — stąd blisko też na półwysep Akamas.",
    overview_en:
      "Coral Bay beaches, UNESCO Roman ruins and a slower pace than Ayia Napa. Good for mixing beach and culture — Akamas peninsula is nearby.",
    stay_hint_pl:
      "Kato Paphos przy promenadzie — ruiny i tawerny w zasięgu spaceru; Coral Bay bardziej „resortowo”.",
    stay_hint_en:
      "Kato Paphos on the promenade — ruins and tavernas within walking distance.",
    center_lat: 34.7571,
    center_lon: 32.4144,
    radius_km: 22,
    picks: [
      {
        day_theme: "beach_relax",
        name_pl: "Coral Bay",
        name_en: "Coral Bay",
        why_pl: "Piaszczysta zatoka na północ od centrum — dobra dla rodzin.",
        why_en: "Sandy bay north of centre — family-friendly.",
        activity_slugs: ["sandy_beaches"],
        rank: 1,
      },
      {
        day_theme: "city_culture",
        name_pl: "Park archeologiczny Pafos",
        name_en: "Paphos Archaeological Park",
        why_pl: "Mozaiki i ruiny rzymskie — UNESCO u wybrzeża.",
        why_en: "Roman mosaics and ruins — UNESCO by the sea.",
        activity_slugs: ["archaeology", "old_towns"],
        rank: 1,
      },
      {
        day_theme: "nature",
        name_pl: "Akamas — Blue Lagoon",
        name_en: "Akamas Blue Lagoon",
        why_pl: "Wycieczka łodzią lub jeep safari na półwysep.",
        why_en: "Boat trip or jeep safari to the peninsula.",
        activity_slugs: ["boat_tour", "viewpoints"],
        rank: 1,
      },
    ],
  },
  {
    id: "cy-larnaca",
    destination_keys: ["larnaka", "larnaca", "cypr", "cyprus"],
    slug: "larnaca-coast",
    name_pl: "Larnaka i okolice",
    name_en: "Larnaca & surrounds",
    character: "mixed",
    vibe: "balanced",
    area_label_pl: "Południowo-wschodni Cypr · główne lotnisko LCA",
    area_label_en: "South-east Cyprus · main LCA airport",
    overview_pl:
      "Najwygodniejszy start po locie — promenada, plaża Finikoudes i słone jezioro. Stąd krótki dojazd do Ayia Napa i Nikozji; mniej „picture postcard” niż Protaras, za to praktyczna baza.",
    overview_en:
      "Easiest start after your flight — promenade, Finikoudes beach and salt lake. Short drives to Ayia Napa and Nicosia; less postcard-perfect than Protaras but practical.",
    stay_hint_pl:
      "Centrum Larnaki — blisko plaży i portu; wyjazd na wschód (Protaras) lub zachód (Limassol) autem ~30–45 min.",
    stay_hint_en:
      "Central Larnaca — near beach and harbour; ~30–45 min drive east or west.",
    center_lat: 34.92,
    center_lon: 33.63,
    radius_km: 18,
    picks: [
      {
        day_theme: "beach_relax",
        name_pl: "Plaża Finikoudes",
        name_en: "Finikoudes beach",
        why_pl: "Miejska plaża z palmami — dobra na pierwsze kąpiele po locie.",
        why_en: "City beach with palms — good first swim after landing.",
        activity_slugs: ["sandy_beaches"],
        rank: 1,
      },
      {
        day_theme: "city_culture",
        name_pl: "Kościół św. Łazarza",
        name_en: "St Lazarus Church",
        why_pl: "Bizantyjska bazylika w centrum — spacer po starym mieście.",
        why_en: "Byzantine basilica in the centre — old town stroll.",
        activity_slugs: ["old_towns", "archaeology"],
        rank: 1,
      },
      {
        day_theme: "nature",
        name_pl: "Jezioro słone Larnaka",
        name_en: "Larnaca Salt Lake",
        why_pl: "Flamingi zimą, widok na meczety — 10 min od centrum.",
        why_en: "Winter flamingos, mosque views — 10 min from centre.",
        activity_slugs: ["viewpoints"],
        rank: 1,
      },
    ],
  },
  {
    id: "cy-limassol",
    destination_keys: ["limassol", "lemesos", "cypr", "cyprus"],
    slug: "limassol-coast",
    name_pl: "Limassol (Lemesos)",
    name_en: "Limassol",
    character: "mixed",
    vibe: "balanced",
    area_label_pl: "Południe wyspy · między oboma lotniskami",
    area_label_en: "South coast · between both airports",
    overview_pl:
      "Drugie co do wielkości miasto — długa promenada, marina i plaże. Dobre centrum wyspy: stąd ~40 min do Pafos, ~1 h do Ayia Napa, blisko winnice i góry Troodos.",
    overview_en:
      "Second-largest city — long promenade, marina and beaches. Good island hub: ~40 min to Paphos, ~1 h to Ayia Napa, close to wine villages and Troodos.",
    stay_hint_pl:
      "Centrum / marina — restauracje i życie miejskie; Germasogeia — spokojniejszy odcinek plaży na wschód od centrum.",
    stay_hint_en:
      "Centre / marina — restaurants and city life; Germasogeia — quieter beach stretch east of centre.",
    center_lat: 34.68,
    center_lon: 33.04,
    radius_km: 16,
    picks: [
      {
        day_theme: "beach_relax",
        name_pl: "Plaże Limassol / Germasogeia",
        name_en: "Limassol & Germasogeia beaches",
        why_pl: "Długa promenada i piaszczyste odcinki — dobre jako baza.",
        why_en: "Long promenade and sandy stretches — solid base.",
        activity_slugs: ["sandy_beaches"],
        rank: 1,
      },
      {
        day_theme: "city_culture",
        name_pl: "Stare miasto i zamek",
        name_en: "Old town & castle",
        why_pl: "Warownia nad portem i uliczki z kawiarniami.",
        why_en: "Harbour castle and café lanes.",
        activity_slugs: ["old_towns", "castles"],
        rank: 1,
      },
      {
        day_theme: "active_outdoor",
        name_pl: "Kourion (wycieczka)",
        name_en: "Kourion day trip",
        why_pl: "Teatr rzymski z widokiem na morze — 20 min jazdy na zachód.",
        why_en: "Roman theatre with sea views — 20 min drive west.",
        activity_slugs: ["archaeology", "viewpoints"],
        rank: 1,
      },
    ],
  },
  {
    id: "cy-troodos",
    destination_keys: ["troodos", "platania", "kykkos", "cypr", "cyprus"],
    slug: "troodos-mountains",
    name_pl: "Troodos — góry i wioski",
    name_en: "Troodos mountains",
    character: "wild",
    vibe: "offbeat",
    area_label_pl: "Centrum wyspy · chłodniej o 5–10°C niż nad morzem",
    area_label_en: "Island interior · 5–10°C cooler than the coast",
    overview_pl:
      "Sosnowe lasy, szlaki i klasztor Kykkos — ucieczka od upałów. Nie baza plażowa: jedziesz tu na 1–2 dni z Limassol/Pafos, nocleg w górskiej wiosce lub wracasz wieczorem.",
    overview_en:
      "Pine forests, trails and Kykkos monastery — escape the heat. Not a beach base: visit for 1–2 days from Limassol/Paphos or return in the evening.",
    stay_hint_pl:
      "Platres lub Kakopetria na nocleg w górach; w upalny tydzień warto zaplanować tu choć jeden dzień.",
    stay_hint_en:
      "Platres or Kakopetria for a mountain stay; worth at least one day in a hot week.",
    center_lat: 34.93,
    center_lon: 32.87,
    radius_km: 28,
    picks: [
      {
        day_theme: "nature",
        name_pl: "Szlak Artemis / Caledonia",
        name_en: "Artemis / Caledonia trails",
        why_pl: "Łagodne trasy w sosnowym lesie — chłód w sierpniu.",
        why_en: "Gentle pine-forest routes — cooler in August.",
        activity_slugs: ["hiking_trails"],
        rank: 1,
      },
      {
        day_theme: "city_culture",
        name_pl: "Klasztor Kykkos",
        name_en: "Kykkos Monastery",
        why_pl: "Najważniejszy klasztor Cypru — malowidła i ikony.",
        why_en: "Cyprus's foremost monastery — frescoes and icons.",
        activity_slugs: ["old_towns", "museums"],
        rank: 1,
      },
      {
        day_theme: "city_culture",
        name_pl: "Wioski winne (Omodos)",
        name_en: "Wine villages (Omodos)",
        why_pl: "Kamienne uliczki i degustacje — południe lub popołudnie.",
        why_en: "Stone lanes and tastings — lunch or afternoon.",
        activity_slugs: ["old_towns"],
        rank: 2,
      },
    ],
  },
  {
    id: "cy-cyprus-general",
    destination_keys: ["cypr", "cyprus", "nikozja", "nicosia"],
    slug: "cyprus-general",
    name_pl: "Cała wyspa (objazd)",
    name_en: "Whole island (road trip)",
    character: "mixed",
    vibe: "balanced",
    area_label_pl: "Tylko jeśli planujecie zmieniać bazę lub jeździć codziennie",
    area_label_en: "Only if you plan to change bases or drive daily",
    overview_pl:
      "Cypr ma ~240 km długości — da się objechać, ale z dziećmi lepiej wybrać jeden rejon na tydzień. Ta opcja ma sens przy 10+ dniach i wynajętym aucie.",
    overview_en:
      "Cyprus is ~240 km long — doable in a loop, but with kids one base per week works better. This option suits 10+ days with a rental car.",
    stay_hint_pl:
      "Typowy plan: 3 dni zachód (Pafos) + 4 dni wschód (Protaras) — dwa hotele, mniej codziennych transferów.",
    stay_hint_en:
      "Typical plan: 3 days west (Paphos) + 4 days east (Protaras) — two hotels, fewer daily transfers.",
    center_lat: 34.85,
    center_lon: 33.2,
    radius_km: 55,
    picks: [
      {
        day_theme: "beach_relax",
        name_pl: "Plaże wschód + zachód",
        name_en: "East & west beaches",
        why_pl: "Nissi i Coral Bay w jednym wyjeździe — wymaga przeprowadzki bazy.",
        why_en: "Nissi and Coral Bay in one trip — needs changing base.",
        activity_slugs: ["sandy_beaches"],
        rank: 1,
      },
      {
        day_theme: "city_culture",
        name_pl: "Nikozja — stara część",
        name_en: "Nicosia old town",
        why_pl: "Jedyna stolica podzielona — muzea i uliczki.",
        why_en: "The divided capital — museums and lanes.",
        activity_slugs: ["old_towns", "museums"],
        rank: 1,
      },
      {
        day_theme: "nature",
        name_pl: "Troodos (dzień z Limassol)",
        name_en: "Troodos day from Limassol",
        why_pl: "Góry jako jednodniówka — nie jako baza noclegowa.",
        why_en: "Mountains as a day trip — not as lodging base.",
        activity_slugs: ["hiking_trails", "viewpoints"],
        rank: 1,
      },
    ],
  },
];
