import type { RegionPick, TouristRegion } from "./tourist-regions";

function bikePick(
  name_pl: string,
  name_en: string,
  why_pl: string,
  why_en: string,
  rank = 1,
): RegionPick {
  return {
    day_theme: "active_outdoor",
    name_pl,
    name_en,
    why_pl,
    why_en,
    activity_slugs: ["bike_rental", "mountain_biking"],
    rank,
  };
}

function hikePick(
  name_pl: string,
  name_en: string,
  why_pl: string,
  why_en: string,
  rank = 1,
): RegionPick {
  return {
    day_theme: "nature",
    name_pl,
    name_en,
    why_pl,
    why_en,
    activity_slugs: ["hiking_trails", "viewpoints"],
    rank,
  };
}

const CRETE_KEYS = ["kreta", "crete", "grecja", "greece"] as const;

/** Pełna siatka Krety + Grecja kontynentalna + Europa rowerowa — nadpisuje starsze seedy po id. */
export const SEED_TOURIST_REGIONS_CYCLING: TouristRegion[] = [
  // ── Kreta (20 rejonów) ──────────────────────────────────────────────
  {
    id: "gr-crete-chania",
    destination_keys: [...CRETE_KEYS, "chania", "hania"],
    slug: "chania-west",
    name_pl: "Chania i zachodnia Kreta",
    name_en: "Chania & western Crete",
    character: "mixed",
    vibe: "balanced",
    overview_pl:
      "Wenecki port, plaże Balos i Falassarna — baza rowerowa na zachodnie wybrzeże i góry Białych Gór.",
    overview_en:
      "Venetian harbour, Balos and Falassarna — cycling base for the west coast and White Mountains.",
    stay_hint_pl: "Chania lub Agia Marina — wypożyczalnie rowerów i szlaki w górach.",
    stay_hint_en: "Chania or Agia Marina — bike rentals and mountain routes.",
    center_lat: 35.51,
    center_lon: 24.02,
    picks: [
      bikePick(
        "Trasy rowerowe z Chanii",
        "Cycling from Chania",
        "Płaskie odcinki przy wybrzeżu i wypożyczalnie w centrum.",
        "Flat coastal legs and rentals in town centre.",
      ),
      hikePick(
        "Wąwóz Samaria (sezon)",
        "Samaria gorge (seasonal)",
        "Klasyczna całodzienna wędrówka — rezerwacja z wyprzedzeniem.",
        "Classic full-day hike — book ahead.",
      ),
      {
        day_theme: "city_culture",
        name_pl: "Stary port w Chanii",
        name_en: "Chania old harbour",
        why_pl: "Wieczorny spacer po porcie — odpoczynek po jeździe.",
        why_en: "Evening harbour stroll — rest after riding.",
        activity_slugs: ["old_towns", "museums"],
        rank: 1,
      },
      {
        day_theme: "beach_relax",
        name_pl: "Falassarna",
        name_en: "Falassarna",
        why_pl: "Długa piaszczysta plaża — dzień regeneracji.",
        why_en: "Long sandy beach — recovery day.",
        activity_slugs: ["sandy_beaches"],
        rank: 1,
      },
    ],
  },
  {
    id: "gr-crete-kissamos",
    destination_keys: [...CRETE_KEYS, "kissamos", "kastelli"],
    slug: "crete-kissamos",
    name_pl: "Kissamos i półwysep Gramvousa",
    name_en: "Kissamos & Gramvousa peninsula",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Spokojniejszy zachód — trasy do Balos, Falassarna i w głąb półwyspu.",
    overview_en: "Quieter west — routes to Balos, Falassarna and the peninsula interior.",
    stay_hint_pl: "Kissamos — tańsze bazy niż Chania, blisko plaż zachodu.",
    stay_hint_en: "Kissamos — cheaper bases than Chania, close to west beaches.",
    center_lat: 35.49,
    center_lon: 23.65,
    picks: [
      bikePick(
        "Wybrzeże zachodnie Kissamos",
        "Kissamos west coast",
        "Długie odcinki przy morzu — mały ruch poza sezonem.",
        "Long coastal legs — light traffic off-season.",
      ),
      {
        day_theme: "beach_relax",
        name_pl: "Balos (wycieczka)",
        name_en: "Balos day trip",
        why_pl: "Laguna — wczesny start lub łódź z Kissamos.",
        why_en: "Lagoon — early start or boat from Kissamos.",
        activity_slugs: ["sandy_beaches", "boat_tour"],
        rank: 1,
      },
    ],
  },
  {
    id: "gr-crete-platanias",
    destination_keys: [...CRETE_KEYS, "platanias", "agia marina"],
    slug: "crete-platanias",
    name_pl: "Platanias i Agia Marina",
    name_en: "Platanias & Agia Marina",
    character: "resort",
    vibe: "popular",
    overview_pl: "Plaże tuż obok Chanii — płaskie trasy wzdłuż wybrzeża na północ.",
    overview_en: "Beaches next to Chania — flat north-coast riding.",
    stay_hint_pl: "Hotele wzdłuż plaży — łatwy dojazd rowerem do Chanii.",
    stay_hint_en: "Beachfront hotels — easy bike ride into Chania.",
    center_lat: 35.52,
    center_lon: 23.91,
    picks: [
      bikePick(
        "Wybrzeże Platanias–Chania",
        "Platanias–Chania coast",
        "Szlaki rowerowe przy morzu — wypożyczalnie w kurorcie.",
        "Coastal bike paths — resort rentals.",
      ),
      {
        day_theme: "beach_relax",
        name_pl: "Plaża Agia Marina",
        name_en: "Agia Marina beach",
        why_pl: "Długa piaszczysta plaża — dzień bez roweru.",
        why_en: "Long sandy beach — rest day.",
        activity_slugs: ["sandy_beaches"],
        rank: 1,
      },
    ],
  },
  {
    id: "gr-crete-kolimbari",
    destination_keys: [...CRETE_KEYS, "kolimbari", "tavronitis"],
    slug: "crete-kolimbari",
    name_pl: "Kolimbari i Tavronitis",
    name_en: "Kolimbari & Tavronitis",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Spokojniejsza północna zatoka — krótsze trasy idealne na rozgrzewkę.",
    overview_en: "Quieter north bay — shorter warm-up rides.",
    stay_hint_pl: "Małe hotele nad zatoką — mniej ruchu niż przy Chanii.",
    stay_hint_en: "Small bay hotels — less traffic than Chania.",
    center_lat: 35.54,
    center_lon: 23.78,
    picks: [
      bikePick(
        "Zatoka Kolimbari",
        "Kolimbari bay loop",
        "Krótkie pętle wzdłuż wybrzeża — dobre na pierwszy dzień.",
        "Short coastal loops — good first-day rides.",
      ),
    ],
  },
  {
    id: "gr-crete-elafonisi",
    destination_keys: [...CRETE_KEYS, "elafonisi", "paleochora"],
    slug: "elafonisi-southwest",
    name_pl: "Elafonisi i południowy zachód",
    name_en: "Elafonisi & southwest",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Różowe piaski i dzikie wybrzeże — wymagające trasy górskie na południowy zachód.",
    overview_en: "Pink sands and wild coast — demanding mountain routes in the southwest.",
    stay_hint_pl: "Paleochora lub Kissamos — baza na Elafonisi i góry.",
    stay_hint_en: "Paleochora or Kissamos — base for Elafonisi and hills.",
    center_lat: 35.27,
    center_lon: 23.54,
    picks: [
      bikePick(
        "Paleochora–Elafonisi (góry)",
        "Paleochora–Elafonisi hills",
        "Wymagające wzniesienia — e-bike lub doświadczeni kolarze.",
        "Climbs — e-bike or experienced riders.",
      ),
      {
        day_theme: "beach_relax",
        name_pl: "Elafonisi",
        name_en: "Elafonisi beach",
        why_pl: "Różowy piasek — nagroda po jeździe.",
        why_en: "Pink sand — reward after riding.",
        activity_slugs: ["sandy_beaches"],
        rank: 1,
      },
    ],
  },
  {
    id: "gr-crete-paleochora",
    destination_keys: [...CRETE_KEYS, "paleochora"],
    slug: "crete-paleochora",
    name_pl: "Paleochora",
    name_en: "Paleochora",
    character: "mixed",
    vibe: "offbeat",
    overview_pl: "Dwa brzegi w jednym miasteczku — baza na południowy zachód i góry Lefka Ori.",
    overview_en: "Two coasts in one town — base for the southwest and Lefka Ori.",
    stay_hint_pl: "Spokojne taverny i wypożyczalnie rowerów w centrum.",
    stay_hint_en: "Quiet tavernas and bike rentals in town.",
    center_lat: 35.23,
    center_lon: 23.68,
    picks: [
      bikePick(
        "Pętla wokół Paleochory",
        "Paleochora loop",
        "Płaskie odcinki wzdłuż obu plaż miasta.",
        "Flat legs along both town beaches.",
      ),
      hikePick(
        "Wąwóz Samaria (dojazd)",
        "Samaria gorge access",
        "Wycieczka autem + trekking — dzień bez roweru.",
        "Drive + hike — rest day off the bike.",
      ),
    ],
  },
  {
    id: "gr-crete-sougia",
    destination_keys: [...CRETE_KEYS, "sougia", "agia roumeli"],
    slug: "crete-sougia",
    name_pl: "Sougia i wybrzeże libyjskie",
    name_en: "Sougia & Libyan coast",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Dziki południowy zachód — mało turystów, trasy wzdłuż libyjskiego morza.",
    overview_en: "Wild south-west — few tourists, routes along the Libyan Sea.",
    stay_hint_pl: "Sougia — małe pensjonaty, spokojny rytm.",
    stay_hint_en: "Sougia — small guesthouses, slow pace.",
    center_lat: 35.24,
    center_lon: 23.97,
    picks: [
      bikePick(
        "Wybrzeże libyjskie",
        "Libyan coast ride",
        "Długie odcinki przy morzu — mały ruch drogowy.",
        "Long coastal legs — light road traffic.",
      ),
    ],
  },
  {
    id: "gr-crete-rethymno",
    destination_keys: [...CRETE_KEYS, "rethymno", "rethimno"],
    slug: "crete-rethymno",
    name_pl: "Rethymno i północna Kreta",
    name_en: "Rethymno & north Crete",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Wenecki port i długa plaża — dobra baza rowerowa między Chaníą a Heraklionem.",
    overview_en: "Venetian harbour and long beach — cycling base between Chania and Heraklion.",
    stay_hint_pl: "Stare miasto lub plaża na wschód od portu.",
    stay_hint_en: "Old town or beach east of harbour.",
    center_lat: 35.37,
    center_lon: 24.47,
    picks: [
      bikePick(
        "Promenada Rethymno",
        "Rethymno promenade ride",
        "Kilometry plaży i płaskie odcinki na wschód.",
        "Miles of beach and flat eastbound riding.",
      ),
      hikePick(
        "Wąwóz Kourtaliotiko",
        "Kourtaliotiko gorge",
        "Wodospady — krótka wycieczka autem z rowerem.",
        "Waterfalls — short drive from your bike base.",
      ),
      {
        day_theme: "city_culture",
        name_pl: "Stare miasto Rethymno",
        name_en: "Rethymno old town",
        why_pl: "Labirynt uliczek nad portem.",
        why_en: "Harbour lane maze.",
        activity_slugs: ["old_towns", "castles"],
        rank: 1,
      },
    ],
  },
  {
    id: "gr-crete-georgioupoli",
    destination_keys: [...CRETE_KEYS, "georgioupoli", "kournas"],
    slug: "crete-georgioupoli",
    name_pl: "Georgioupoli i jezioro Kournas",
    name_en: "Georgioupoli & Lake Kournas",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Rzeka wypływająca na plażę i jedyne naturalne jezioro Krety w pobliżu.",
    overview_en: "River meeting the beach and Crete's only natural lake nearby.",
    stay_hint_pl: "Georgioupoli — spokojniejsze niż Rethymno, blisko jeziora.",
    stay_hint_en: "Georgioupoli — calmer than Rethymno, near the lake.",
    center_lat: 35.33,
    center_lon: 24.26,
    picks: [
      bikePick(
        "Georgioupoli–Kournas",
        "Georgioupoli–Kournas loop",
        "Płaska trasa do jeziora — ok. 20 km w obie strony.",
        "Flat lake loop — ~20 km round trip.",
      ),
    ],
  },
  {
    id: "gr-crete-panormo",
    destination_keys: [...CRETE_KEYS, "panormo", "bali"],
    slug: "crete-panormo",
    name_pl: "Panormo i Bali",
    name_en: "Panormo & Bali",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Małe zatoczki na północy — spokojne trasy między Rethymno a Heraklionem.",
    overview_en: "Small north-coast coves — quiet riding between Rethymno and Heraklion.",
    stay_hint_pl: "Panormo — kameralna baza z taverną nad portem.",
    stay_hint_en: "Panormo — intimate harbour taverna base.",
    center_lat: 35.42,
    center_lon: 24.69,
    picks: [
      bikePick(
        "Północne zatoczki",
        "North cove rides",
        "Krótkie pętle Panormo–Bali — mało ruchu.",
        "Short Panormo–Bali loops — light traffic.",
      ),
    ],
  },
  {
    id: "gr-heraklion-crete",
    destination_keys: [...CRETE_KEYS, "heraklion", "iraklion"],
    slug: "heraklion-crete",
    name_pl: "Heraklion i centralna Kreta",
    name_en: "Heraklion & central Crete",
    character: "historic",
    vibe: "popular",
    overview_pl: "Stolica wyspy — muzea, Knossos i trasy rowerowe w okolicy miasta.",
    overview_en: "Island capital — museums, Knossos and cycling around the city.",
    stay_hint_pl: "Centrum na zwiedzanie; Amoudara na plażę i rower.",
    stay_hint_en: "Centre for sights; Amoudara for beach and bikes.",
    center_lat: 35.34,
    center_lon: 25.14,
    picks: [
      bikePick(
        "Heraklion–Amoudara",
        "Heraklion–Amoudara coast",
        "Płaski odcinek do plaży — wypożyczalnie w kurorcie.",
        "Flat beach strip — resort bike rentals.",
      ),
      {
        day_theme: "city_culture",
        name_pl: "Knossos",
        name_en: "Knossos palace",
        why_pl: "Pałac minojski — pół dnia poza rowerem.",
        why_en: "Minoan palace — half day off the bike.",
        activity_slugs: ["archaeology", "museums"],
        rank: 1,
      },
    ],
  },
  {
    id: "gr-crete-gouves",
    destination_keys: [...CRETE_KEYS, "gouves", "hersonissos", "hersonissos"],
    slug: "crete-gouves",
    name_pl: "Gouves i Hersonissos",
    name_en: "Gouves & Hersonissos",
    character: "resort",
    vibe: "popular",
    overview_pl: "Północno-wschodni kurort — płaskie trasy przy wybrzeżu i wypożyczalnie rowerów.",
    overview_en: "North-east resort strip — flat coastal riding and bike rentals.",
    stay_hint_pl: "Gouves lub Hersonissos — blisko plaż i tras.",
    stay_hint_en: "Gouves or Hersonissos — close to beaches and routes.",
    center_lat: 35.33,
    center_lon: 25.32,
    picks: [
      bikePick(
        "Wybrzeże Hersonissos",
        "Hersonissos coast",
        "Długie płaskie odcinki — popularna trasa rowerowa.",
        "Long flat coastal legs — popular cycling route.",
      ),
    ],
  },
  {
    id: "gr-crete-malia",
    destination_keys: [...CRETE_KEYS, "malia", "stalis"],
    slug: "crete-malia",
    name_pl: "Malia i Stalis",
    name_en: "Malia & Stalis",
    character: "resort",
    vibe: "popular",
    overview_pl: "Wschodnia północ — plaże, minojskie Malia i trasy w kierunku Agios Nikolaos.",
    overview_en: "East north coast — beaches, Minoan Malia and routes toward Agios Nikolaos.",
    stay_hint_pl: "Stalis na spokój; Malia na pełniejszą infrastrukturę.",
    stay_hint_en: "Stalis for calm; Malia for more facilities.",
    center_lat: 35.28,
    center_lon: 25.46,
    picks: [
      bikePick(
        "Malia–Stalis wybrzeże",
        "Malia–Stalis coast",
        "Płaska trasa wzdłuż morza — ok. 15 km w jedną stronę.",
        "Flat seaside route — ~15 km one way.",
      ),
      {
        day_theme: "city_culture",
        name_pl: "Pałac w Malii",
        name_en: "Malia palace",
        why_pl: "Minojska ruina — krótka wycieczka z rowerem.",
        why_en: "Minoan ruins — short ride from base.",
        activity_slugs: ["archaeology"],
        rank: 1,
      },
    ],
  },
  {
    id: "gr-crete-agios-nikolaos",
    destination_keys: [...CRETE_KEYS, "agios nikolaos", "ayios nikolaos"],
    slug: "crete-agios-nikolaos",
    name_pl: "Agios Nikolaos",
    name_en: "Agios Nikolaos",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Jezioro Voulismeni, port i wschodnie wybrzeże — baza na Lassithi i Eloundę.",
    overview_en: "Lake Voulismeni, harbour and east coast — base for Lassithi and Elounda.",
    stay_hint_pl: "Centrum miasta nad jeziorem — dobre wypożyczalnie.",
    stay_hint_en: "Town centre by the lake — good rentals.",
    center_lat: 35.19,
    center_lon: 25.72,
    picks: [
      bikePick(
        "Agios Nikolaos–Plaka",
        "Agios Nikolaos–Plaka ride",
        "Trasa wzdłuż zatoki Mirabello — widoki na morze.",
        "Mirabello bay route — sea views.",
      ),
    ],
  },
  {
    id: "gr-crete-elounda",
    destination_keys: [...CRETE_KEYS, "elounda", "plaka"],
    slug: "crete-elounda",
    name_pl: "Elounda i Plaka",
    name_en: "Elounda & Plaka",
    character: "resort",
    vibe: "popular",
    overview_pl: "Luksusowe kurorty i Spinalonga — spokojne trasy wzdłuż półwyspu.",
    overview_en: "Luxury resorts and Spinalonga — quiet peninsula rides.",
    stay_hint_pl: "Elounda lub Plaka — spokojniejsze niż Agios Nikolaos.",
    stay_hint_en: "Elounda or Plaka — quieter than Agios Nikolaos.",
    center_lat: 35.26,
    center_lon: 25.73,
    picks: [
      bikePick(
        "Półwysep Elounda",
        "Elounda peninsula",
        "Kręte odcinki wzdłuż zatoki — mały ruch.",
        "Winding bay-side legs — light traffic.",
      ),
      {
        day_theme: "beach_relax",
        name_pl: "Plaże Elounda",
        name_en: "Elounda beaches",
        why_pl: "Krystaliczna woda — dzień regeneracji.",
        why_en: "Crystal-clear water — recovery day.",
        activity_slugs: ["sandy_beaches"],
        rank: 1,
      },
    ],
  },
  {
    id: "gr-crete-lassithi",
    destination_keys: [...CRETE_KEYS, "lassithi", "lasithi", "krasi"],
    slug: "crete-lassithi",
    name_pl: "Płaskowyż Lassithi",
    name_en: "Lassithi plateau",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Górski płaskowyż ze wiatrakami — wymagające wzniesienia i spektakularne widoki.",
    overview_en: "Mountain plateau with windmills — climbs and spectacular views.",
    stay_hint_pl: "Wioski na płaskowyżu — e-bike zalecany na stromych odcinkach.",
    stay_hint_en: "Plateau villages — e-bike recommended on steep sections.",
    center_lat: 35.18,
    center_lon: 25.48,
    picks: [
      bikePick(
        "Płaskowyż Lassithi",
        "Lassithi plateau loop",
        "Wiatraki i wioski — jedna z najpiękniejszych tras górskich Krety.",
        "Windmills and villages — one of Crete's best mountain loops.",
      ),
      hikePick(
        "Jaskinia Dikte (Diktaion Antron)",
        "Dikte cave",
        "Minojska legenda — krótki trekking z rowerem.",
        "Minoan legend — short hike from bike base.",
      ),
    ],
  },
  {
    id: "gr-crete-ierapetra",
    destination_keys: [...CRETE_KEYS, "ierapetra", "ierapetra"],
    slug: "crete-ierapetra",
    name_pl: "Ierapetra — południowy wschód",
    name_en: "Ierapetra — south-east",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Najbardziej wysunięte na południe miasto Europy — ciepło i trasy wzdłuż libyjskiego wybrzeża.",
    overview_en: "Europe's southernmost town — warm weather and Libyan coast routes.",
    stay_hint_pl: "Centrum Ierapetry — taverny nad morzem.",
    stay_hint_en: "Ierapetra centre — seaside tavernas.",
    center_lat: 35.01,
    center_lon: 25.74,
    picks: [
      bikePick(
        "Wybrzeże Ierapetra",
        "Ierapetra coast",
        "Długie płaskie odcinki na południu — mało turystów.",
        "Long flat southern legs — fewer tourists.",
      ),
    ],
  },
  {
    id: "gr-crete-sitia",
    destination_keys: [...CRETE_KEYS, "sitia", "vai"],
    slug: "crete-sitia",
    name_pl: "Sitia i wschodnia Kreta",
    name_en: "Sitia & eastern Crete",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Najmniej zatłoczony wschód wyspy — plaża Vai z palmami i górskie trasy.",
    overview_en: "Crete's quietest east — Vai palm beach and mountain routes.",
    stay_hint_pl: "Sitia — spokojne miasto z portem i lotniskiem.",
    stay_hint_en: "Sitia — quiet town with harbour and airport.",
    center_lat: 35.2,
    center_lon: 26.1,
    picks: [
      bikePick(
        "Sitia–Vai",
        "Sitia–Vai ride",
        "Trasa do palmowej plaży — wzniesienia z widokiem.",
        "Route to palm beach — climbs with views.",
      ),
      {
        day_theme: "beach_relax",
        name_pl: "Plaża Vai",
        name_en: "Vai palm beach",
        why_pl: "Jedyna palmowa plaża w Europie — wczesny start.",
        why_en: "Europe's only palm beach — go early.",
        activity_slugs: ["sandy_beaches"],
        rank: 1,
      },
    ],
  },
  {
    id: "gr-crete-matala",
    destination_keys: [...CRETE_KEYS, "matala", "agia galini"],
    slug: "crete-matala",
    name_pl: "Matala i południowa Kreta",
    name_en: "Matala & south Crete",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Klifowe plaże i jaskinie hippisów — spokojniejsze południe wyspy.",
    overview_en: "Cliff beaches and hippie caves — quieter south Crete.",
    stay_hint_pl: "Matala na plażę; Agia Galini na spokojniejszy port.",
    stay_hint_en: "Matala for beach; Agia Galini for quieter harbour.",
    center_lat: 35.0,
    center_lon: 24.75,
    picks: [
      bikePick(
        "Południowe wybrzeże",
        "South coast riding",
        "Trasy Matala–Kommos — umiarkowane wzniesienia.",
        "Matala–Kommos routes — moderate climbs.",
      ),
      {
        day_theme: "beach_relax",
        name_pl: "Plaża Matala",
        name_en: "Matala beach",
        why_pl: "Jaskinie w skale — unikalny klimat.",
        why_en: "Cliff caves — unique vibe.",
        activity_slugs: ["sandy_beaches", "viewpoints"],
        rank: 1,
      },
    ],
  },
  {
    id: "gr-crete-south-sfakia",
    destination_keys: [...CRETE_KEYS, "sfakia", "hora sfakion", "loutro"],
    slug: "crete-sfakia",
    name_pl: "Sfakia i Loutro",
    name_en: "Sfakia & Loutro",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Białe Góry i wybrzeże libyjskie — wymagające trasy i wioski dostępne tylko z morza.",
    overview_en: "White Mountains and Libyan coast — demanding routes and sea-only villages.",
    stay_hint_pl: "Hora Sfakion — prom do Loutro, trasy górskie w okolicy.",
    stay_hint_en: "Hora Sfakion — ferry to Loutro, mountain routes nearby.",
    center_lat: 35.2,
    center_lon: 24.13,
    picks: [
      bikePick(
        "Sfakia–Anopolis",
        "Sfakia–Anopolis climb",
        "Strome wzniesienie — e-bike lub MTB.",
        "Steep climb — e-bike or MTB.",
      ),
      hikePick(
        "Wąwóz Imbros",
        "Imbros gorge",
        "Krótsza alternatywa dla Samarii — sezon letni.",
        "Shorter Samaria alternative — summer season.",
      ),
    ],
  },
  {
    id: "gr-crete-anoia",
    destination_keys: [...CRETE_KEYS, "anogia", "psiloritis"],
    slug: "crete-anoia",
    name_pl: "Anogia i Psiloritis",
    name_en: "Anogia & Psiloritis",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Górskie wioski i najwyższy szczyt Krety — trasy dla zaawansowanych kolarzy.",
    overview_en: "Mountain villages and Crete's highest peak — advanced cycling.",
    stay_hint_pl: "Anogia — tradycyjna wioska, e-bike na górskich odcinkach.",
    stay_hint_en: "Anogia — traditional village, e-bike on mountain sections.",
    center_lat: 35.29,
    center_lon: 24.88,
    picks: [
      bikePick(
        "Góry Psiloritis",
        "Psiloritis mountain routes",
        "Wymagające wzniesienia — tylko dla doświadczonych.",
        "Demanding climbs — experienced riders only.",
      ),
    ],
  },

  // ── Grecja kontynentalna (rower) ────────────────────────────────────
  {
    id: "gr-athens-coast-cycling",
    destination_keys: ["athens", "ateny", "glyfada", "vouliagmeni", "grecja", "greece"],
    slug: "athens-coast-cycling",
    name_pl: "Ateny — wybrzeże",
    name_en: "Athens — coast",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Riviera ateńska — trasy wzdłuż morza i połączenie z centrum tramwajem.",
    overview_en: "Athens Riviera — coastal routes and tram link to centre.",
    stay_hint_pl: "Glyfada lub Vouliagmeni — baza rowerowa z plażą.",
    stay_hint_en: "Glyfada or Vouliagmeni — cycling base with beach.",
    center_lat: 37.86,
    center_lon: 23.75,
    picks: [
      bikePick(
        "Riviera ateńska",
        "Athens Riviera ride",
        "Ścieżki przy morzu — wypożyczalnie w Glyfadzie.",
        "Seaside paths — rentals in Glyfada.",
      ),
    ],
  },
  {
    id: "gr-peloponnese-nafplio-cycling",
    destination_keys: ["nafplio", "nafplion", "argolida", "peloponez", "peloponnese", "grecja", "greece"],
    slug: "peloponnese-nafplio-cycling",
    name_pl: "Nafplio i Argolida",
    name_en: "Nafplio & Argolis",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Weneckie Nafplio u stóp twierdzy — trasy nad zatoką i do Myken.",
    overview_en: "Venetian Nafplio below the fortress — bay rides and Mycenae access.",
    stay_hint_pl: "Stare miasto Nafplio — wypożyczalnie rowerów w porcie.",
    stay_hint_en: "Old Nafplio — bike rentals at harbour.",
    center_lat: 37.57,
    center_lon: 22.8,
    picks: [
      bikePick(
        "Zatoka Argolska",
        "Argolic Gulf loop",
        "Płaskie odcinki wzdłuż wybrzeża — widok na Bourtzi.",
        "Flat coastal legs — Bourtzi fortress views.",
      ),
      {
        day_theme: "city_culture",
        name_pl: "Mykeny (wycieczka)",
        name_en: "Mycenae day trip",
        why_pl: "Agamemnon — krótki dojazd autem z Nafplio.",
        why_en: "Agamemnon — short drive from Nafplio.",
        activity_slugs: ["archaeology"],
        rank: 1,
      },
    ],
  },
  {
    id: "gr-peloponnese-mani-cycling",
    destination_keys: ["mani", "areopoli", "stoupa", "peloponez", "grecja", "greece"],
    slug: "peloponnese-mani-cycling",
    name_pl: "Mani — południe Peloponezu",
    name_en: "Mani — south Peloponnese",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Kamienne wieże i dramatyczne wybrzeże — wymagające trasy na południu Peloponezu.",
    overview_en: "Stone towers and dramatic coast — demanding south Peloponnese routes.",
    stay_hint_pl: "Areopoli lub Stoupa — bazy na pętle wzdłuż wybrzeża.",
    stay_hint_en: "Areopoli or Stoupa — bases for coastal loops.",
    center_lat: 36.67,
    center_lon: 22.38,
    picks: [
      bikePick(
        "Wybrzeże Mani",
        "Mani coast ride",
        "Wzniesienia i widoki — e-bike zalecany.",
        "Climbs and views — e-bike recommended.",
      ),
    ],
  },
  {
    id: "gr-thessaloniki-cycling",
    destination_keys: ["thessaloniki", "saloniki", "salonica", "grecja", "greece"],
    slug: "thessaloniki-cycling",
    name_pl: "Saloniki",
    name_en: "Thessaloniki",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Nabrzeże Thermaikos i Biała Wieża — miejskie trasy rowerowe nad morzem.",
    overview_en: "Thermaikos waterfront and White Tower — urban seaside cycling.",
    stay_hint_pl: "Centrum nad promenadą — łatwy dostęp do tras.",
    stay_hint_en: "Centre on the promenade — easy route access.",
    center_lat: 40.64,
    center_lon: 22.94,
    picks: [
      bikePick(
        "Promenada Salonik",
        "Thessaloniki waterfront",
        "Kilometry ścieżek wzdłuż zatoki.",
        "Miles of bay-side paths.",
      ),
    ],
  },
  {
    id: "gr-chalkidiki-kassandra-cycling",
    destination_keys: ["chalkidiki", "halkidiki", "kassandra", "grecja", "greece"],
    slug: "chalkidiki-kassandra-cycling",
    name_pl: "Chalkidiki — Kassandra",
    name_en: "Halkidiki — Kassandra",
    character: "resort",
    vibe: "popular",
    overview_pl: "Półwysep Kassandra — trasy między plażami i lasy sosnowe.",
    overview_en: "Kassandra peninsula — routes between beaches and pine forests.",
    stay_hint_pl: "Kallithea lub Nea Moudania — wypożyczalnie w kurortach.",
    stay_hint_en: "Kallithea or Nea Moudania — resort rentals.",
    center_lat: 40.05,
    center_lon: 23.45,
    picks: [
      bikePick(
        "Półwysep Kassandra",
        "Kassandra peninsula loop",
        "Płaskie odcinki między zatoczkami — popularne trasy.",
        "Flat legs between coves — popular routes.",
      ),
    ],
  },
  {
    id: "gr-ioannina-cycling",
    destination_keys: ["ioannina", "janina", "epir", "epirus", "grecja", "greece"],
    slug: "ioannina-cycling",
    name_pl: "Janina i Jezioro",
    name_en: "Ioannina & the lake",
    character: "historic",
    vibe: "balanced",
    overview_pl: "Jezioro Pamvotida i wyspa Ioannina — płaskie trasy wokół wody.",
    overview_en: "Lake Pamvotida and Ioannina island — flat lakeside riding.",
    stay_hint_pl: "Centrum Janiny — wypożyczalnie nad brzegiem.",
    stay_hint_en: "Ioannina centre — lakeside rentals.",
    center_lat: 39.67,
    center_lon: 20.85,
    picks: [
      bikePick(
        "Pętla wokół jeziora",
        "Lake loop",
        "Ok. 30 km wokół Pamvotida — mały ruch.",
        "~30 km around Pamvotida — light traffic.",
      ),
    ],
  },
  {
    id: "gr-zagori-cycling",
    destination_keys: ["zagori", "zaguori", "vikos", "grecja", "greece"],
    slug: "zagori-cycling",
    name_pl: "Zagori i wąwozy",
    name_en: "Zagori & gorges",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Kamienne mosty i wioski Epiru — górskie trasy dla zaawansowanych.",
    overview_en: "Stone bridges and Epirus villages — mountain routes for advanced riders.",
    stay_hint_pl: "Monodendri lub Papigo — e-bike na stromych odcinkach.",
    stay_hint_en: "Monodendri or Papigo — e-bike on steep sections.",
    center_lat: 39.88,
    center_lon: 20.75,
    picks: [
      bikePick(
        "Wioski Zagori",
        "Zagori village routes",
        "Wzniesienia między mostami — spektakularne widoki.",
        "Climbs between bridges — spectacular views.",
      ),
      hikePick(
        "Wąwóz Vikos",
        "Vikos gorge",
        "Najgłębszy wąwóz — trekking z rowerem w okolicy.",
        "Deep gorge — hiking near your bike base.",
      ),
    ],
  },
  {
    id: "gr-meteora-cycling",
    destination_keys: ["meteora", "kalambaka", "kalampaka", "grecja", "greece"],
    slug: "meteora-cycling",
    name_pl: "Meteory i Kalambaka",
    name_en: "Meteora & Kalambaka",
    character: "historic",
    vibe: "popular",
    overview_pl: "Klasztory na skałach — wymagające wzniesienia i spektakularne panoramy.",
    overview_en: "Cliff-top monasteries — demanding climbs and spectacular panoramas.",
    stay_hint_pl: "Kalambaka u stóp skał — wypożyczalnie e-bike.",
    stay_hint_en: "Kalambaka below the rocks — e-bike rentals.",
    center_lat: 39.71,
    center_lon: 21.63,
    picks: [
      bikePick(
        "Meteory — pętla",
        "Meteora loop",
        "Wzniesienia do klasztorów — e-bike bardzo popularny.",
        "Climbs to monasteries — e-bikes very popular.",
      ),
    ],
  },
  {
    id: "gr-corfu-north-cycling",
    destination_keys: ["corfu", "korfu", "kerkyra", "grecja", "greece", "ionian"],
    slug: "corfu-north-cycling",
    name_pl: "Korfu — północ",
    name_en: "Corfu — north",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Zatoki i wioski północy — łagodne trasy między plażami.",
    overview_en: "North bays and villages — gentle routes between beaches.",
    stay_hint_pl: "Sidari lub Acharavi — wypożyczalnie w kurortach.",
    stay_hint_en: "Sidari or Acharavi — resort rentals.",
    center_lat: 39.62,
    center_lon: 19.92,
    picks: [
      bikePick(
        "Północ Korfu",
        "North Corfu coast",
        "Płaskie odcinki wzdłuż wybrzeża.",
        "Flat coastal legs.",
      ),
    ],
  },
  {
    id: "gr-lefkada-cycling",
    destination_keys: ["lefkada", "lefkas", "nydri", "grecja", "greece", "ionian"],
    slug: "lefkada-cycling",
    name_pl: "Lefkada (Nydri)",
    name_en: "Lefkada (Nydri)",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Wyspa połączona mostem — trasy wzdłuż wschodniego wybrzeża i do wodospadów.",
    overview_en: "Bridge-linked island — east coast routes and waterfall access.",
    stay_hint_pl: "Nydri — popularna baza rowerowa z wypożyczalniami.",
    stay_hint_en: "Nydri — popular cycling base with rentals.",
    center_lat: 38.7,
    center_lon: 20.71,
    picks: [
      bikePick(
        "Wybrzeże Lefkady",
        "Lefkada coast ride",
        "Trasy Nydri–Vasiliki — widoki na wyspy.",
        "Nydri–Vasiliki routes — island views.",
      ),
    ],
  },
  {
    id: "gr-rhodes-ialyssos-cycling",
    destination_keys: ["rhodes", "rodos", "ialyssos", "grecja", "greece"],
    slug: "rhodes-ialyssos-cycling",
    name_pl: "Rodos — północ (Ialyssos)",
    name_en: "Rhodes — north (Ialyssos)",
    character: "resort",
    vibe: "popular",
    overview_pl: "Północ Rodos — plaże i trasy w kierunku Starého Miasta.",
    overview_en: "North Rhodes — beaches and routes toward the Old Town.",
    stay_hint_pl: "Ialyssos lub Ixia — blisko lotniska i plaż.",
    stay_hint_en: "Ialyssos or Ixia — near airport and beaches.",
    center_lat: 36.41,
    center_lon: 28.2,
    picks: [
      bikePick(
        "Rodos — wybrzeże północne",
        "North Rhodes coast",
        "Płaskie odcinki do Starego Miasta — ok. 15 km.",
        "Flat legs to Old Town — ~15 km.",
      ),
    ],
  },
  {
    id: "gr-kos-cycling",
    destination_keys: ["kos", "grecja", "greece", "dodecanese"],
    slug: "kos-cycling",
    name_pl: "Kos",
    name_en: "Kos",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Płaska wyspa — jedna z najlepszych destynacji rowerowych w Grecji.",
    overview_en: "Flat island — one of Greece's best cycling destinations.",
    stay_hint_pl: "Kardamena lub Kos Town — setki km ścieżek.",
    stay_hint_en: "Kardamena or Kos Town — hundreds of km of paths.",
    center_lat: 36.89,
    center_lon: 27.29,
    picks: [
      bikePick(
        "Płaska Kos",
        "Flat Kos island loop",
        "Wyspa praktycznie płaska — idealna na wielodniowy objazd rowerem.",
        "Nearly flat island — ideal multi-day bike tour.",
      ),
    ],
  },
  {
    id: "gr-pelion-cycling",
    destination_keys: ["pelion", "volos", "grecja", "greece"],
    slug: "pelion-cycling",
    name_pl: "Pelion (Volos)",
    name_en: "Pelion (Volos)",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Górskie wioski i widoki na zatokę — wymagające trasy na półwyspie Pelion.",
    overview_en: "Mountain villages and bay views — demanding Pelion peninsula routes.",
    stay_hint_pl: "Portaria lub Tsagarada — e-bike na stromych odcinkach.",
    stay_hint_en: "Portaria or Tsagarada — e-bike on steep sections.",
    center_lat: 39.36,
    center_lon: 23.01,
    picks: [
      bikePick(
        "Wioski Pelion",
        "Pelion village routes",
        "Kręte drogi między wioskami — spektakularne widoki.",
        "Winding village roads — spectacular views.",
      ),
    ],
  },

  // ── Europa rowerowa ─────────────────────────────────────────────────
  {
    id: "es-mallorca-palma-cycling",
    destination_keys: ["mallorca", "majorka", "palma", "hiszpania", "spain"],
    slug: "mallorca-palma-cycling",
    name_pl: "Majorka — Palma",
    name_en: "Mallorca — Palma",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Stolica wyspy i wybrzeże — baza na trasy w głąb wyspy i Serra de Tramuntana.",
    overview_en: "Island capital and coast — base for inland and Tramuntana routes.",
    stay_hint_pl: "Palma — wypożyczalnie rowerów szosowych i MTB.",
    stay_hint_en: "Palma — road and MTB rentals.",
    center_lat: 39.57,
    center_lon: 2.65,
    picks: [
      bikePick(
        "Palma– wybrzeże",
        "Palma coast ride",
        "Promenada i drogi przy morzu — rozgrzewka przed górami.",
        "Promenade and coastal roads — warm-up before mountains.",
      ),
    ],
  },
  {
    id: "es-mallorca-alcudia-cycling",
    destination_keys: ["mallorca", "majorka", "alcudia", "port d alcudia", "hiszpania", "spain"],
    slug: "mallorca-alcudia-cycling",
    name_pl: "Majorka — Alcúdia",
    name_en: "Mallorca — Alcúdia",
    character: "resort",
    vibe: "popular",
    overview_pl: "Północ Majorki — płaskie trasy do Cap de Formentor i w góry.",
    overview_en: "North Mallorca — flat routes to Formentor and into the hills.",
    stay_hint_pl: "Port d'Alcúdia — popularna baza kolarska.",
    stay_hint_en: "Port d'Alcúdia — popular cycling base.",
    center_lat: 39.85,
    center_lon: 3.12,
    picks: [
      bikePick(
        "Alcúdia–Formentor",
        "Alcúdia–Formentor ride",
        "Kultowa trasa na półwysep — wzniesienia z widokiem.",
        "Iconic peninsula route — climbs with views.",
      ),
    ],
  },
  {
    id: "es-menorca-cycling",
    destination_keys: ["menorca", "minorca", "mao", "mahon", "hiszpania", "spain"],
    slug: "menorca-cycling",
    name_pl: "Menorca",
    name_en: "Menorca",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Spokojniejsza siostra Majorki — Camí de Cavalls wokół wyspy.",
    overview_en: "Mallorca's quieter sister — Camí de Cavalls around the island.",
    stay_hint_pl: "Maó lub Ciutadella — wypożyczalnie rowerów.",
    stay_hint_en: "Maó or Ciutadella — bike rentals.",
    center_lat: 39.89,
    center_lon: 4.27,
    picks: [
      bikePick(
        "Camí de Cavalls",
        "Camí de Cavalls",
        "Szlak wokół wyspy — odcinki na każdy poziom.",
        "Island circuit trail — sections for every level.",
      ),
    ],
  },
  {
    id: "es-formentera-cycling",
    destination_keys: ["formentera", "ibiza", "hiszpania", "spain"],
    slug: "formentera-cycling",
    name_pl: "Formentera",
    name_en: "Formentera",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Płaska wyspa — rower to najlepszy transport między plażami.",
    overview_en: "Flat island — bike is the best way between beaches.",
    stay_hint_pl: "Es Pujols lub La Savina — wypożyczalnie przy porcie.",
    stay_hint_en: "Es Pujols or La Savina — rentals at harbour.",
    center_lat: 38.71,
    center_lon: 1.45,
    picks: [
      bikePick(
        "Formentera end-to-end",
        "Formentera island crossing",
        "Płaska trasa przez całą wyspę — ok. 20 km.",
        "Flat crossing — ~20 km.",
      ),
    ],
  },
  {
    id: "pt-algarve-lagos-cycling",
    destination_keys: ["algarve", "lagos", "portugalia", "portugal"],
    slug: "algarve-lagos-cycling",
    name_pl: "Algarve — Lagos",
    name_en: "Algarve — Lagos",
    character: "resort",
    vibe: "popular",
    overview_pl: "Klifowe wybrzeże i zatoczki — trasy wzdłuż Costa Vicentina.",
    overview_en: "Cliff coast and coves — Costa Vicentina routes.",
    stay_hint_pl: "Lagos — wypożyczalnie rowerów i e-bike.",
    stay_hint_en: "Lagos — bike and e-bike rentals.",
    center_lat: 37.1,
    center_lon: -8.67,
    picks: [
      bikePick(
        "Klifowe zatoczki Lagos",
        "Lagos cliff coves",
        "Trasy do Ponta da Piedade — umiarkowane wzniesienia.",
        "Routes to Ponta da Piedade — moderate climbs.",
      ),
    ],
  },
  {
    id: "pt-lisbon-cascais-cycling",
    destination_keys: ["lisbon", "lizbona", "cascais", "sintra", "portugalia", "portugal"],
    slug: "lisbon-cascais-cycling",
    name_pl: "Lizbona — Cascais",
    name_en: "Lisbon — Cascais",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Wybrzeże Estoril i Cascais — trasy rowerowe z Lizbony pociągiem.",
    overview_en: "Estoril and Cascais coast — cycling routes from Lisbon by train.",
    stay_hint_pl: "Cascais — baza rowerowa z pociągiem do centrum.",
    stay_hint_en: "Cascais — cycling base with train to centre.",
    center_lat: 38.7,
    center_lon: -9.42,
    picks: [
      bikePick(
        "Cascais–Guincho",
        "Cascais–Guincho coast",
        "Wiatr i klify — popularna trasa szosowa.",
        "Wind and cliffs — popular road route.",
      ),
    ],
  },
  {
    id: "it-sardinia-cagliari-cycling",
    destination_keys: ["sardynia", "sardinia", "cagliari", "wlochy", "italy"],
    slug: "sardinia-cagliari-cycling",
    name_pl: "Sardynia — Cagliari",
    name_en: "Sardinia — Cagliari",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Południe Sardynii — trasy wzdłuż wybrzeża i do wewnętrznych wzgórz.",
    overview_en: "South Sardinia — coastal routes and inland hills.",
    stay_hint_pl: "Cagliari — wypożyczalnie w centrum.",
    stay_hint_en: "Cagliari — city centre rentals.",
    center_lat: 39.22,
    center_lon: 9.12,
    picks: [
      bikePick(
        "Południe Sardynii",
        "South Sardinia rides",
        "Trasy do Poetto i w głąb wyspy.",
        "Routes to Poetto beach and inland.",
      ),
    ],
  },
  {
    id: "it-sicily-catania-cycling",
    destination_keys: ["sycylia", "sicily", "catania", "etna", "wlochy", "italy"],
    slug: "sicily-catania-cycling",
    name_pl: "Sycylia — Katania / Etna",
    name_en: "Sicily — Catania / Etna",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Etna i wschodnie wybrzeże — wymagające wzniesienia i widoki wulkanu.",
    overview_en: "Etna and east coast — demanding climbs and volcano views.",
    stay_hint_pl: "Taormina lub Catania — e-bike na stromych odcinkach Etny.",
    stay_hint_en: "Taormina or Catania — e-bike on Etna slopes.",
    center_lat: 37.5,
    center_lon: 15.09,
    picks: [
      bikePick(
        "Etna — dolne stoki",
        "Etna lower slopes",
        "Wzniesienia z widokiem na morze — e-bike zalecany.",
        "Climbs with sea views — e-bike recommended.",
      ),
    ],
  },
  {
    id: "it-tuscany-lucca-cycling",
    destination_keys: ["toskania", "tuscany", "lucca", "wlochy", "italy"],
    slug: "tuscany-lucca-cycling",
    name_pl: "Toskania — Lucca",
    name_en: "Tuscany — Lucca",
    character: "historic",
    vibe: "popular",
    overview_pl: "Mury Luccy i płaskie trasy w dolinie — raj dla rowerzystów.",
    overview_en: "Lucca walls and flat valley routes — cyclist's paradise.",
    stay_hint_pl: "Centrum Luccy — wypożyczalnie przy murach.",
    stay_hint_en: "Lucca centre — rentals by the walls.",
    center_lat: 43.84,
    center_lon: 10.5,
    picks: [
      bikePick(
        "Mury Luccy i okolice",
        "Lucca walls loop",
        "Płaskie trasy w dolinie — winnice i wioski.",
        "Flat valley routes — vineyards and villages.",
      ),
    ],
  },
  {
    id: "it-dolomites-cortina-cycling",
    destination_keys: ["dolomity", "dolomites", "cortina", "wlochy", "italy"],
    slug: "dolomites-cortina-cycling",
    name_pl: "Dolomity — Cortina",
    name_en: "Dolomites — Cortina",
    character: "wild",
    vibe: "popular",
    overview_pl: "Passo Giau i przełęcze — legendarne wzniesienia dla kolarzy szosowych.",
    overview_en: "Passo Giau and passes — legendary road cycling climbs.",
    stay_hint_pl: "Cortina d'Ampezzo — baza na przełęcze, e-bike opcjonalnie.",
    stay_hint_en: "Cortina d'Ampezzo — pass base, e-bike optional.",
    center_lat: 46.54,
    center_lon: 12.14,
    picks: [
      bikePick(
        "Przełęcze Dolomitów",
        "Dolomite passes",
        "Passo Giau, Tre Croci — wymagające wzniesienia.",
        "Passo Giau, Tre Croci — demanding climbs.",
      ),
    ],
  },
  {
    id: "it-lake-garda-riva-cycling",
    destination_keys: ["garda", "lake garda", "riva", "wlochy", "italy"],
    slug: "lake-garda-riva-cycling",
    name_pl: "Jezioro Garda — Riva",
    name_en: "Lake Garda — Riva",
    character: "mixed",
    vibe: "popular",
    overview_pl: "Północ Garda — trasy wzdłuż jeziora i w góry.",
    overview_en: "North Garda — lakeside routes and mountain climbs.",
    stay_hint_pl: "Riva del Garda — wypożyczalnie rowerów i e-bike.",
    stay_hint_en: "Riva del Garda — bike and e-bike rentals.",
    center_lat: 45.89,
    center_lon: 10.84,
    picks: [
      bikePick(
        "Cykl ścieżka Garda",
        "Garda cycle path",
        "Ścieżki wzdłuż północnego brzegu — widoki na jezioro.",
        "North shore paths — lake views.",
      ),
    ],
  },
  {
    id: "fr-corsica-ajaccio-cycling",
    destination_keys: ["korsyka", "corsica", "ajaccio", "francja", "france"],
    slug: "corsica-ajaccio-cycling",
    name_pl: "Korsyka — Ajaccio",
    name_en: "Corsica — Ajaccio",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Górzysta wyspa — wymagające trasy i spektakularne widoki.",
    overview_en: "Mountainous island — demanding routes and spectacular views.",
    stay_hint_pl: "Ajaccio — baza na południowe odcinki GR20 rowerem.",
    stay_hint_en: "Ajaccio — base for southern island loops.",
    center_lat: 41.93,
    center_lon: 8.74,
    picks: [
      bikePick(
        "Korsyka — południe",
        "South Corsica rides",
        "Wzniesienia i wybrzeże — e-bike na dłuższe trasy.",
        "Climbs and coast — e-bike for longer routes.",
      ),
    ],
  },
  {
    id: "hr-istria-porec-cycling",
    destination_keys: ["istria", "istria", "porec", "poreč", "chorwacja", "croatia"],
    slug: "istria-porec-cycling",
    name_pl: "Istria — Poreč",
    name_en: "Istria — Poreč",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Płaskie trasy Parenzany i wybrzeże — idealne na rodzinny rower.",
    overview_en: "Flat Parenzana routes and coast — ideal family cycling.",
    stay_hint_pl: "Poreč lub Vrsar — wypożyczalnie rowerów.",
    stay_hint_en: "Poreč or Vrsar — bike rentals.",
    center_lat: 45.23,
    center_lon: 13.6,
    picks: [
      bikePick(
        "Parenzana — szlak rowerowy",
        "Parenzana cycle route",
        "Dawna linia kolejowa — płaska trasa przez Istrię.",
        "Old railway line — flat route across Istria.",
      ),
    ],
  },
  {
    id: "hr-dalmatia-split-cycling",
    destination_keys: ["split", "dalmacja", "dalmatia", "chorwacja", "croatia"],
    slug: "dalmatia-split-cycling",
    name_pl: "Dalmacja — Split",
    name_en: "Dalmatia — Split",
    character: "historic",
    vibe: "popular",
    overview_pl: "Pałac Dioklecjana i wybrzeże — trasy wzdłuż Riwiery splitńskiej.",
    overview_en: "Diocletian's Palace and coast — Split Riviera routes.",
    stay_hint_pl: "Split — wypożyczalnie w centrum i przy Marinie.",
    stay_hint_en: "Split — rentals in centre and marina.",
    center_lat: 43.51,
    center_lon: 16.44,
    picks: [
      bikePick(
        "Split–Marjan",
        "Split–Marjan ride",
        "Wzgórze Marjan i wybrzeże — krótkie pętle z miasta.",
        "Marjan hill and coast — short city loops.",
      ),
    ],
  },
  {
    id: "si-ljubljana-bled-cycling",
    destination_keys: ["słowenia", "slovenia", "bled", "ljubljana"],
    slug: "ljubljana-bled-cycling",
    name_pl: "Słowenia — Bled",
    name_en: "Slovenia — Bled",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Jezioro Bled i Alpy Julijskie — trasy wokół wody i w góry.",
    overview_en: "Lake Bled and Julian Alps — lakeside and mountain routes.",
    stay_hint_pl: "Bled — wypożyczalnie rowerów i e-bike.",
    stay_hint_en: "Bled — bike and e-bike rentals.",
    center_lat: 46.36,
    center_lon: 14.09,
    picks: [
      bikePick(
        "Pętla wokół Bled",
        "Lake Bled loop",
        "Ok. 6 km wokół jeziora — idealna rozgrzewka.",
        "~6 km lake loop — ideal warm-up.",
      ),
    ],
  },
  {
    id: "at-salzburg-zell-cycling",
    destination_keys: ["austria", "austria", "salzburg", "zell am see", "kaprun"],
    slug: "salzburg-zell-cycling",
    name_pl: "Austria — Zell am See",
    name_en: "Austria — Zell am See",
    character: "wild",
    vibe: "popular",
    overview_pl: "Jezioro i Alpy — trasy rowerowe w dolinach i wzniesienia na Großglockner (e-bike).",
    overview_en: "Lake and Alps — valley cycling routes and Großglockner climbs (e-bike).",
    stay_hint_pl: "Zell am See — wypożyczalnie e-bike i MTB.",
    stay_hint_en: "Zell am See — e-bike and MTB rentals.",
    center_lat: 47.32,
    center_lon: 12.8,
    picks: [
      bikePick(
        "Dolina Salzach",
        "Salzach valley ride",
        "Ścieżki rowerowe wzdłuż rzeki — płaskie odcinki.",
        "River cycle paths — flat sections.",
      ),
    ],
  },
  {
    id: "de-black-forest-freiburg-cycling",
    destination_keys: ["schwarzwald", "black forest", "freiburg", "niemcy", "germany"],
    slug: "black-forest-freiburg-cycling",
    name_pl: "Schwarzwald — Freiburg",
    name_en: "Black Forest — Freiburg",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Freiburg i Schwarzwald — górskie trasy i dolina Ren.",
    overview_en: "Freiburg and Black Forest — mountain routes and Rhine valley.",
    stay_hint_pl: "Freiburg — rowerowe miasto z wypożyczalniami.",
    stay_hint_en: "Freiburg — bike-friendly city with rentals.",
    center_lat: 47.99,
    center_lon: 7.85,
    picks: [
      bikePick(
        "Freiburg–Schauinsland",
        "Freiburg–Schauinsland",
        "Wzniesienia w Schwarzwald — e-bike popularny.",
        "Black Forest climbs — e-bikes popular.",
      ),
    ],
  },
  {
    id: "nl-amsterdam-waterland-cycling",
    destination_keys: ["amsterdam", "holandia", "netherlands", "waterland", "marken"],
    slug: "amsterdam-waterland-cycling",
    name_pl: "Holandia — Waterland",
    name_en: "Netherlands — Waterland",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Polder i wioski nad wodą — płaskie trasy idealne na rower.",
    overview_en: "Polder and waterside villages — flat ideal cycling.",
    stay_hint_pl: "Amsterdam lub Volendam — wypożyczalnie rowerów.",
    stay_hint_en: "Amsterdam or Volendam — bike rentals.",
    center_lat: 52.46,
    center_lon: 5.1,
    picks: [
      bikePick(
        "Waterland — polder",
        "Waterland polder ride",
        "Płaskie trasy między wioskami — wiatr wieje z morza.",
        "Flat village routes — sea breeze.",
      ),
    ],
  },
];
