import type { TouristRegion } from "./tourist-regions";

/** Regiony dla destynacji z DESTINATION_CATALOG — uzupełnienie bazy seed. */
export const SEED_TOURIST_REGIONS_EXTRA: TouristRegion[] = [
  // --- Hiszpania: Wyspy Kanaryjskie ---
  {
    id: "es-tenerife-costa-adeje",
    destination_keys: ["tenerife", "teneryfa", "adeje", "playa de las americas", "los cristianos"],
    slug: "tenerife-costa-adeje",
    name_pl: "Costa Adeje i południe Teneryfy",
    name_en: "Costa Adeje & south Tenerife",
    character: "resort",
    vibe: "popular",
    overview_pl: "Najpopularniejszy kurort wyspy — plaże, parki wodne i blisko Teide.",
    overview_en: "The island's main resort strip — beaches, water parks and Teide access.",
    stay_hint_pl: "Costa Adeje lub Los Cristianos — dobre na rodziny, transfer z TFS ok. 20 min.",
    stay_hint_en: "Costa Adeje or Los Cristianos — family-friendly, ~20 min from TFS.",
    center_lat: 28.08,
    center_lon: -16.73,
    picks: [
      { day_theme: "beach_relax", name_pl: "Playa de las Teresitas", name_en: "Las Teresitas beach", why_pl: "Jedyna piaszczysta plaża na północy — wycieczka na cały dzień.", why_en: "The north's only golden sand beach — worth a day trip.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Playa del Duque", name_en: "Playa del Duque", why_pl: "Spokojniejsza plaża w Costa Adeje — leżaki i promenada.", why_en: "Quieter Costa Adeje beach — sunbeds and promenade.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "nature", name_pl: "Park Narodowy Teide", name_en: "Teide National Park", why_pl: "Wulkan i szlaki — rezerwacja wstępu na szczyt z wyprzedzeniem.", why_en: "Volcano and trails — summit permit books out early.", activity_slugs: ["national_parks", "viewpoints"], rank: 1 },
      { day_theme: "kids", name_pl: "Siam Park", name_en: "Siam Park", why_pl: "Jeden z najlepszych parków wodnych w Europie — cały dzień z dziećmi.", why_en: "One of Europe's top water parks — full day with kids.", activity_slugs: ["water_parks"], rank: 1 },
    ],
  },
  {
    id: "es-tenerife-puerto-cruz",
    destination_keys: ["tenerife", "teneryfa", "puerto de la cruz", "orotava"],
    slug: "tenerife-north",
    name_pl: "Puerto de la Cruz",
    name_en: "Puerto de la Cruz",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Północ wyspy — zielone doliny, Loro Parque i mniej „all inclusive” niż południe.",
    overview_en: "Green north — valleys, Loro Parque, less all-inclusive than the south.",
    stay_hint_pl: "Centrum Puerto — blisko plaży i promenady, autobus do Teide.",
    stay_hint_en: "Central Puerto — near beach and promenade, bus to Teide.",
    center_lat: 28.41,
    center_lon: -16.55,
    picks: [
      { day_theme: "beach_relax", name_pl: "Playa Jardín", name_en: "Playa Jardín", why_pl: "Plaża z ogrodami César Manrique — charakter północy.", why_en: "César Manrique garden beach — north-side character.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "La Orotava", name_en: "La Orotava", why_pl: "Kolonialne kamienice i widok na doliny — 15 min jazdy.", why_en: "Colonial mansions and valley views — 15 min drive.", activity_slugs: ["old_towns"], rank: 1 },
      { day_theme: "kids", name_pl: "Loro Parque", name_en: "Loro Parque", why_pl: "Oceanarium i pokazy — klasyk rodzinnych wyjazdów na Teneryfę.", why_en: "Aquarium and shows — classic Tenerife family day.", activity_slugs: ["aquarium", "zoo"], rank: 1 },
    ],
  },
  {
    id: "es-gran-canaria-maspalomas",
    destination_keys: ["gran canaria", "maspalomas", "playa del ingles", "las palmas"],
    slug: "gran-canaria-south",
    name_pl: "Maspalomas i południe",
    name_en: "Maspalomas & south",
    character: "resort",
    vibe: "popular",
    overview_pl: "Wydmy Maspalomas, długie plaże i największy wybór hoteli na wyspie.",
    overview_en: "Maspalomas dunes, long beaches and the island's widest hotel choice.",
    stay_hint_pl: "Maspalomas / Playa del Inglés — blisko wydm i plaży.",
    stay_hint_en: "Maspalomas / Playa del Inglés — near dunes and beach.",
    center_lat: 27.76,
    center_lon: -15.58,
    picks: [
      { day_theme: "beach_relax", name_pl: "Wydmy Maspalomas", name_en: "Maspalomas dunes", why_pl: "Piaszczyste wydmy nad oceanem — spacer o zachodzie.", why_en: "Sand dunes by the ocean — sunset walk.", activity_slugs: ["sandy_beaches", "viewpoints"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Playa del Inglés", name_en: "Playa del Inglés", why_pl: "Długa plaża z infrastrukturą — dobre na rodziny.", why_en: "Long beach with full facilities — family-friendly.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "active_outdoor", name_pl: "Surf / windsurf (Pozo Izquierdo)", name_en: "Pozo Izquierdo surf", why_pl: "Słynny spot wiatrów — lekcje dla początkujących poza sezonem pro.", why_en: "Famous wind spot — beginner lessons outside pro season.", activity_slugs: ["kayaking"], rank: 1 },
    ],
  },
  {
    id: "es-fuerteventura-corralejo",
    destination_keys: ["fuerteventura", "corralejo", "cotillo"],
    slug: "fuerteventura-north",
    name_pl: "Corralejo i północ",
    name_en: "Corralejo & north",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Plaże przy Parku Dunas de Corralejo i prom na Lanzarote — wiatr i kitesurf.",
    overview_en: "Beaches by Corralejo dunes and Lanzarote ferry — wind and kitesurf.",
    stay_hint_pl: "Corralejo na plażę i restauracje; El Cotillo na spokój.",
    stay_hint_en: "Corralejo for beach and dining; El Cotillo for quiet stays.",
    center_lat: 28.73,
    center_lon: -13.87,
    picks: [
      { day_theme: "beach_relax", name_pl: "Playa Grandes", name_en: "Grandes beach (Corralejo)", why_pl: "Turkus wody i widok na Lobos — leżaki przy promenadzie.", why_en: "Turquoise water and Lobos views — sunbeds on the promenade.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "nature", name_pl: "Isla de Lobos", name_en: "Lobos island", why_pl: "Krótki rejs promem — dzika wysepka, snorkeling.", why_en: "Short ferry hop — wild islet, snorkeling.", activity_slugs: ["boat_tour", "snorkeling"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "El Cotillo", name_en: "El Cotillo", why_pl: "Laguny z płytką wodą — idealne z małymi dziećmi.", why_en: "Shallow lagoon pools — ideal with small kids.", activity_slugs: ["sandy_beaches"], rank: 2 },
    ],
  },
  // --- Grecja ---
  {
    id: "gr-rhodes-lindos",
    destination_keys: ["rodos", "rhodes", "lindos", "roda"],
    slug: "rhodes-lindos",
    name_pl: "Lindos i wschodnie Rodos",
    name_en: "Lindos & east Rhodes",
    character: "historic",
    vibe: "popular",
    overview_pl: "Biała wioska Lindos, akropol nad morzem i plaże zatoki św. Pawła.",
    overview_en: "White Lindos village, clifftop acropolis and St Paul's Bay beaches.",
    stay_hint_pl: "Lindos na klimat (chodzisz pieszo), Faliraki na plażę i noclegi.",
    stay_hint_en: "Lindos for atmosphere (walkable); Faliraki for beach hotels.",
    center_lat: 36.09,
    center_lon: 28.09,
    picks: [
      { day_theme: "city_culture", name_pl: "Akropol Lindos", name_en: "Lindos acropolis", why_pl: "Widok 360° — wspinaczka lub osiołek z dziećmi.", why_en: "360° views — climb or donkey ride with kids.", activity_slugs: ["old_towns", "archaeology"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Zatoka św. Pawła", name_en: "St Paul's Bay", why_pl: "Mała zatoczka pod akropolem — kąpiel i zdjęcia.", why_en: "Small cove below the acropolis — swim and photos.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Stare miasto Rodos (UNESCO)", name_en: "Rhodes Old Town", why_pl: "Uliczki rycerzy joannitów — wycieczka na pół dnia z Lindos.", why_en: "Knights' quarter lanes — half-day trip from Lindos.", activity_slugs: ["old_towns", "castles"], rank: 1 },
    ],
  },
  {
    id: "gr-rhodes-faliraki",
    destination_keys: ["rodos", "rhodes", "faliraki", "ixia", "ialyssos"],
    slug: "rhodes-northwest",
    name_pl: "Faliraki i północny zachód",
    name_en: "Faliraki & northwest",
    character: "resort",
    vibe: "popular",
    overview_pl: "Długie plaże, parki wodne i blisko lotniska — typowa baza all inclusive.",
    overview_en: "Long beaches, water parks, close to airport — classic all-inclusive base.",
    stay_hint_pl: "Faliraki lub Ixia — promenady i taverny nad morzem.",
    stay_hint_en: "Faliraki or Ixia — seafront promenades and tavernas.",
    center_lat: 36.34,
    center_lon: 28.2,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Faliraki", name_en: "Faliraki beach", why_pl: "Długa, piaszczysta, pełna infrastruktury.", why_en: "Long sandy beach with full facilities.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "kids", name_pl: "Waterpark Faliraki", name_en: "Faliraki waterpark", why_pl: "Duży park wodny — cały dzień z dziećmi.", why_en: "Large water park — full day with kids.", activity_slugs: ["water_parks"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs na Syme", name_en: "Symi day trip", why_pl: "Kolorowe porty i kąpiel — prom z Mandraki.", why_en: "Colourful harbour and swim — ferry from Mandraki.", activity_slugs: ["boat_tour"], rank: 1 },
    ],
  },
  {
    id: "gr-corfu-paleokastritsa",
    destination_keys: ["korfu", "corfu", "kerkyra", "paleokastritsa"],
    slug: "corfu-northwest",
    name_pl: "Paleokastritsa i północny zachód",
    name_en: "Paleokastritsa & northwest",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Zatoczki, błękitna woda i klasztor — najpiękniejszy fragment wybrzeża Korfu.",
    overview_en: "Coves, blue water and monastery — Corfu's prettiest coast.",
    stay_hint_pl: "Paleokastritsa lub Agios Georgios — wynajem auta praktyczny.",
    stay_hint_en: "Paleokastritsa or Agios Georgios — car rental recommended.",
    center_lat: 39.67,
    center_lon: 19.7,
    picks: [
      { day_theme: "beach_relax", name_pl: "Zatoki Paleokastritsa", name_en: "Paleokastritsa coves", why_pl: "Kilka małych plaż — łodzie na ukryte zatoczki.", why_en: "Several small beaches — boats to hidden coves.", activity_slugs: ["rocky_beaches", "boat_tour"], rank: 1 },
      { day_theme: "nature", name_pl: "Widok z klasztoru", name_en: "Monastery viewpoint", why_pl: "Moni Theotokou — panorama całej zatoki.", why_en: "Moni Theotokou — panoramic bay views.", activity_slugs: ["viewpoints"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Snorkeling / kajak", name_en: "Snorkel & kayak", why_pl: "Czysta woda w zatokach — wypożyczalnie w porcie.", why_en: "Clear cove water — rentals at the harbour.", activity_slugs: ["snorkeling", "kayaking"], rank: 1 },
    ],
  },
  {
    id: "gr-corfu-benitses",
    destination_keys: ["korfu", "corfu", "benitses", "messonghi", "dassia"],
    slug: "corfu-east",
    name_pl: "Benitses i wschodnie wybrzeże",
    name_en: "Benitses & east coast",
    character: "resort",
    vibe: "popular",
    overview_pl: "Spokojniejsze niż północ — długie plaże i blisko lotniska.",
    overview_en: "Quieter than the north — long beaches near the airport.",
    stay_hint_pl: "Messonghi / Moraitika — długa plaża, dobre na rodziny.",
    stay_hint_en: "Messonghi / Moraitika — long beach, family-friendly.",
    center_lat: 39.48,
    center_lon: 19.92,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Messonghi", name_en: "Messonghi beach", why_pl: "Piaszczysta, płytka — taverny tuż przy brzegu.", why_en: "Sandy, shallow — tavernas on the shore.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Stare miasto Korfu", name_en: "Corfu Old Town", why_pl: "UNESCO, forteca i Liston — autobus z wybrzeża.", why_en: "UNESCO old town, fortress and Liston — bus from coast.", activity_slugs: ["old_towns", "castles"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Achillion (Achilleion)", name_en: "Achilleion Palace", why_pl: "Pałac cesarzowej Sisi — ogrody i widoki.", why_en: "Empress Sisi's palace — gardens and views.", activity_slugs: ["museums", "viewpoints"], rank: 1 },
    ],
  },
  // --- Chorwacja ---
  {
    id: "hr-split-centre",
    destination_keys: ["split", "splitsko", "dalmacja", "dalmatia"],
    slug: "split-centre",
    name_pl: "Split — centrum i wyspy",
    name_en: "Split centre & islands",
    character: "historic",
    vibe: "popular",
    overview_pl: "Pałac Dioklecjana, Riva i promy na Brač, Hvar i Vis — serce Dalmacji.",
    overview_en: "Diocletian's Palace, Riva and ferries to Brač, Hvar and Vis.",
    stay_hint_pl: "W obrębie pałacu lub Bačvice — blisko promów i plaży miejskiej.",
    stay_hint_en: "Inside the palace quarter or Bačvice — near ferries and city beach.",
    center_lat: 43.51,
    center_lon: 16.44,
    picks: [
      { day_theme: "city_culture", name_pl: "Pałac Dioklecjana", name_en: "Diocletian's Palace", why_pl: "Żyjące miasto w ruinach rzymskich — spacer z przewodnikiem.", why_en: "Living city inside Roman ruins — guided walk.", activity_slugs: ["old_towns", "archaeology"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Bačvice", name_en: "Bačvice beach", why_pl: "Miejska plaża picigin — 10 min od centrum.", why_en: "City beach famous for picigin — 10 min from centre.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Hvar (rejs promem)", name_en: "Hvar ferry day trip", why_pl: "Najpopularniejsza wyspa — marina i twierdza.", why_en: "Most popular island — marina and fortress.", activity_slugs: ["boat_tour", "old_towns"], rank: 1 },
    ],
  },
  {
    id: "hr-hvar-island",
    destination_keys: ["hvar", "hvar town", "stari grad"],
    slug: "hvar-island",
    name_pl: "Wyspa Hvar",
    name_en: "Hvar island",
    character: "mixed",
    vibe: "popular",
    overview_pl: "Lawenda, pakleni otoci i nocne życie Hvar Town — premium Dalmacja.",
    overview_en: "Lavender, Pakleni islets and Hvar Town nightlife — premium Dalmatia.",
    stay_hint_pl: "Hvar Town na klimat, Stari Grad spokojniej — prom z Splitu.",
    stay_hint_en: "Hvar Town for vibe, Stari Grad quieter — ferry from Split.",
    center_lat: 43.17,
    center_lon: 16.44,
    picks: [
      { day_theme: "beach_relax", name_pl: "Pakleni otoci", name_en: "Pakleni islands", why_pl: "Łodzie-taxi na ukryte zatoczki — turkus wody.", why_en: "Water taxis to hidden coves — turquoise water.", activity_slugs: ["boat_tour", "rocky_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Twierdza Hvar", name_en: "Hvar fortress", why_pl: "Widok na archipelag — krótki spacer z portu.", why_en: "Archipelago views — short walk from harbour.", activity_slugs: ["castles", "viewpoints"], rank: 1 },
      { day_theme: "nature", name_pl: "Lavender fields (sezon)", name_en: "Lavender fields", why_pl: "Czerwiec–lipiec — wycieczka na pola lawendy.", why_en: "June–July — trip to lavender fields.", activity_slugs: ["viewpoints"], rank: 1 },
    ],
  },
  // --- Cypr ---
  {
    id: "cy-ayia-napa",
    destination_keys: ["ayia napa", "agia napa", "ajia napa", "protaras", "cypr", "cyprus"],
    slug: "ayia-napa",
    name_pl: "Ayia Napa i Protaras",
    name_en: "Ayia Napa & Protaras",
    character: "resort",
    vibe: "popular",
    overview_pl: "Najpiękniejsze plaże Cypru — Fig Tree Bay, Nissi i krystaliczna woda.",
    overview_en: "Cyprus's best beaches — Fig Tree Bay, Nissi and crystal-clear water.",
    stay_hint_pl: "Protaras spokojniej z rodziną, Ayia Napa więcej atrakcji.",
    stay_hint_en: "Protaras quieter for families, Ayia Napa more going on.",
    center_lat: 34.98,
    center_lon: 34.0,
    picks: [
      { day_theme: "beach_relax", name_pl: "Nissi Beach", name_en: "Nissi Beach", why_pl: "Płytka laguna i bary na plaży — klasyk Ayia Napa.", why_en: "Shallow lagoon and beach bars — Ayia Napa classic.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Fig Tree Bay (Protaras)", name_en: "Fig Tree Bay", why_pl: "Błękitna flaga, piaszczysta — idealna z dziećmi.", why_en: "Blue Flag sandy beach — ideal with kids.", activity_slugs: ["sandy_beaches"], rank: 2 },
      { day_theme: "nature", name_pl: "Cape Greco", name_en: "Cape Greco", why_pl: "Klifowe szlaki i jaskinie morskie — rower lub spacer.", why_en: "Cliff trails and sea caves — bike or walk.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
    ],
  },
  // --- Portugalia ---
  {
    id: "pt-madeira-funchal",
    destination_keys: ["madeira", "madera", "funchal"],
    slug: "madeira-funchal",
    name_pl: "Funchal i południe Madery",
    name_en: "Funchal & south Madeira",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Ogrody, kolejka linowa i levady — wyspa na aktywny i spokojny wypoczynek.",
    overview_en: "Gardens, cable car and levadas — active and relaxed island breaks.",
    stay_hint_pl: "Funchal na pierwszy wyjazd — promenada, restauracje, wypożyczalnie.",
    stay_hint_en: "Funchal for a first trip — promenade, restaurants, rentals.",
    center_lat: 32.65,
    center_lon: -16.91,
    picks: [
      { day_theme: "nature", name_pl: "Levada do Caldeirão Verde", name_en: "Caldeirão Verde levada", why_pl: "Klasyczna trasa wzdłuż wodociągu — las i wodospad.", why_en: "Classic levada walk — forest and waterfall.", activity_slugs: ["hiking_trails", "waterfalls"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Ogród Monte / kolejka linowa", name_en: "Monte gardens & cable car", why_pl: "Widok na Funchal i sanie z Monte.", why_en: "Funchal views and Monte toboggan ride.", activity_slugs: ["viewpoints", "museums"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaże w Machico / Caniço", name_en: "Machico / Caniço beaches", why_pl: "Kamieniste zejścia do oceanu — kąpiel po wędrówce.", why_en: "Rocky ocean access — swim after hiking.", activity_slugs: ["rocky_beaches"], rank: 1 },
    ],
  },
  {
    id: "pt-algarve-lagos",
    destination_keys: ["algarve", "lagos", "portimao", "albufeira", "faro"],
    slug: "algarve-lagos",
    name_pl: "Lagos i zachodni Algarve",
    name_en: "Lagos & west Algarve",
    character: "resort",
    vibe: "popular",
    overview_pl: "Klifowe zatoczki Ponta da Piedade i plaże Dona Ana — klasyk Portugalii.",
    overview_en: "Ponta da Piedade cliffs and Dona Ana — Portugal classic.",
    stay_hint_pl: "Lagos na pierwszy raz — marina, klify, rejsy łodzią.",
    stay_hint_en: "Lagos for first-timers — marina, cliffs, boat trips.",
    center_lat: 37.1,
    center_lon: -8.67,
    picks: [
      { day_theme: "beach_relax", name_pl: "Praia Dona Ana", name_en: "Dona Ana beach", why_pl: "Turkus między klifami — najsłynniejsza plaża okolicy.", why_en: "Turquoise between cliffs — the area's most famous beach.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs Ponta da Piedade", name_en: "Ponta da Piedade boat tour", why_pl: "Jaskinie i łuki skalne z wody — obowiązkowy punkt.", why_en: "Sea caves and rock arches — must-do.", activity_slugs: ["boat_tour"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Praia da Marinha", name_en: "Marinha beach", why_pl: "Widokowa plaża na wschód od Lagos — parking nad klifem.", why_en: "Scenic beach east of Lagos — clifftop parking.", activity_slugs: ["rocky_beaches", "viewpoints"], rank: 2 },
    ],
  },
  // --- Turcja ---
  {
    id: "tr-antalya-kaleici",
    destination_keys: ["antalya", "kaleici", "lara", "kundu"],
    slug: "antalya-centre",
    name_pl: "Antalya — Kaleiçi i Lara",
    name_en: "Antalya — Kaleiçi & Lara",
    character: "mixed",
    vibe: "popular",
    overview_pl: "Stare miasto nad portem i długie plaże Lara — all inclusive i zwiedzanie.",
    overview_en: "Old harbour town and long Lara beaches — all-inclusive and sightseeing.",
    stay_hint_pl: "Kaleiçi na klimat, Lara/Kundu na resorty nad morzem.",
    stay_hint_en: "Kaleiçi for atmosphere, Lara/Kundu for beach resorts.",
    center_lat: 36.88,
    center_lon: 30.71,
    picks: [
      { day_theme: "city_culture", name_pl: "Kaleiçi i port", name_en: "Kaleiçi & harbour", why_pl: "Kamienice osmańskie, muzea i promenada.", why_en: "Ottoman houses, museums and harbour walk.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Lara", name_en: "Lara beach", why_pl: "Długa, piaszczysta — hotele i aquaparki w okolicy.", why_en: "Long sandy beach — hotels and aquaparks nearby.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "nature", name_pl: "Wodospady Düden", name_en: "Düden waterfalls", why_pl: "Wodospad wpada do morza — krótki wypad z centrum.", why_en: "Waterfall drops into the sea — short trip from centre.", activity_slugs: ["waterfalls", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "tr-bodrum-peninsula",
    destination_keys: ["bodrum", "gumbet", "bitez", "turgutreis"],
    slug: "bodrum-peninsula",
    name_pl: "Bodrum i półwysep",
    name_en: "Bodrum peninsula",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Białe domki, marina i greckie wyspy na horyzoncie — luźniejszy rytm niż Antalya.",
    overview_en: "White houses, marina and Greek islands on the horizon.",
    stay_hint_pl: "Bodrum Town na nocne życie, Bitez/Gündoğan spokojniej.",
    stay_hint_en: "Bodrum Town for nightlife, Bitez/Gündoğan quieter.",
    center_lat: 37.03,
    center_lon: 27.43,
    picks: [
      { day_theme: "city_culture", name_pl: "Zamek św. Piotra", name_en: "Castle of St Peter", why_pl: "Muzeum podwodne i widok na marinę.", why_en: "Underwater museum and marina views.", activity_slugs: ["castles", "museums"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Bitez", name_en: "Bitez beach", why_pl: "Płytkie, spokojne morze — dobre na rodziny.", why_en: "Shallow, calm sea — good for families.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Rejs na Kos", name_en: "Kos day trip", why_pl: "Grecka wyspa na wycieczkę — prom z Bodrum.", why_en: "Greek island day trip — ferry from Bodrum.", activity_slugs: ["boat_tour"], rank: 1 },
    ],
  },
  // --- Hiszpania: wybrzeże ---
  {
    id: "es-costa-blanca-benidorm",
    destination_keys: ["benidorm", "alicante", "alikante", "calpe", "altea", "costa blanca"],
    slug: "costa-blanca",
    name_pl: "Benidorm i Costa Blanca",
    name_en: "Benidorm & Costa Blanca",
    character: "resort",
    vibe: "popular",
    overview_pl: "Plaże, parki tematyczne i Penyal d'Ifac — popularna baza dla rodzin z Europy.",
    overview_en: "Beaches, theme parks and Peñón de Ifach — popular family base.",
    stay_hint_pl: "Benidorm na infrastrukturę, Altea/Calpe na spokojniejszy klimat.",
    stay_hint_en: "Benidorm for facilities, Altea/Calpe for quieter vibe.",
    center_lat: 38.54,
    center_lon: -0.13,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaże Levante i Poniente", name_en: "Levante & Poniente beaches", why_pl: "Długie, piaszczyste — serce Benidormu.", why_en: "Long sandy beaches — Benidorm core.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "kids", name_pl: "Terra Mítica / Aqualandia", name_en: "Terra Mítica / Aqualandia", why_pl: "Parki rozrywki — cały dzień z dziećmi.", why_en: "Theme parks — full day with kids.", activity_slugs: ["theme_parks", "water_parks"], rank: 1 },
      { day_theme: "nature", name_pl: "Penyal d'Ifac (Calpe)", name_en: "Peñón de Ifach", why_pl: "Skała nad morzem — krótka wspinaczka, widoki.", why_en: "Rock above the sea — short climb, views.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "es-barcelona-coast",
    destination_keys: ["barcelona", "sitges", "badalona", "barceloneta"],
    slug: "barcelona-coast",
    name_pl: "Barcelona i wybrzeże",
    name_en: "Barcelona & coast",
    character: "mixed",
    vibe: "popular",
    overview_pl: "Gaudí, Barceloneta i Sitges na plażę — city break z morzem.",
    overview_en: "Gaudí, Barceloneta and Sitges beach — city break with sea.",
    stay_hint_pl: "Centrum na zwiedzanie, Sitges na dni plażowe (30 min pociągiem).",
    stay_hint_en: "Centre for sightseeing, Sitges for beach days (30 min train).",
    center_lat: 41.39,
    center_lon: 2.17,
    picks: [
      { day_theme: "city_culture", name_pl: "Sagrada Família i Gràcia", name_en: "Sagrada Família & Gràcia", why_pl: "Rezerwuj bilety online — unikniesz kolejek.", why_en: "Book tickets online — skip the queues.", activity_slugs: ["museums", "old_towns"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Barceloneta", name_en: "Barceloneta beach", why_pl: "Miejska plaża — szybki wypad po zwiedzaniu.", why_en: "City beach — quick dip after sightseeing.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Sitges", name_en: "Sitges", why_pl: "Piaszczyste plaże i stare miasto — pociąg z Sants.", why_en: "Sandy beaches and old town — train from Sants.", activity_slugs: ["sandy_beaches", "old_towns"], rank: 2 },
    ],
  },
  // --- Włochy ---
  {
    id: "it-sicily-taormina",
    destination_keys: ["sycylia", "sicily", "taormina", "messina", "etna"],
    slug: "sicily-taormina",
    name_pl: "Taormina i wschodnia Sycylia",
    name_en: "Taormina & east Sicily",
    character: "historic",
    vibe: "popular",
    overview_pl: "Teatr grecki z widokiem na Etna, Isola Bella i kurort nad klifem.",
    overview_en: "Greek theatre facing Etna, Isola Bella and clifftop resort.",
    stay_hint_pl: "Taormina na pierwszy wyjazd — autobus w dół na plażę.",
    stay_hint_en: "Taormina for first-timers — bus down to the beach.",
    center_lat: 37.85,
    center_lon: 15.29,
    picks: [
      { day_theme: "city_culture", name_pl: "Teatr antyczny Taormina", name_en: "Taormina Greek theatre", why_pl: "Widok na Etna i morze — najsłynniejszy punkt Sycylii.", why_en: "Etna and sea views — Sicily's icon.", activity_slugs: ["archaeology", "viewpoints"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Isola Bella", name_en: "Isola Bella", why_pl: "Kameralna zatoczka — kolejka linowa z Taorminy.", why_en: "Intimate cove — cable car from Taormina.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "nature", name_pl: "Etna (wycieczka)", name_en: "Mount Etna trip", why_pl: "Wycieczka z przewodnikiem na strefę wulkanu.", why_en: "Guided trip into the volcanic zone.", activity_slugs: ["national_parks", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "it-sicily-cefalu",
    destination_keys: ["sycylia", "sicily", "cefalu", "cefalù", "palermo"],
    slug: "sicily-north",
    name_pl: "Cefalù i północ",
    name_en: "Cefalù & north coast",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Stare miasto pod skałą, długa piaszczysta plaża i blisko Palermo.",
    overview_en: "Old town below the rock, long sandy beach, close to Palermo.",
    stay_hint_pl: "Cefalù na plażowanie, Palermo na city break (1 h pociągiem).",
    stay_hint_en: "Cefalù for beach time, Palermo city break (1 h train).",
    center_lat: 38.04,
    center_lon: 13.99,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaża Cefalù", name_en: "Cefalù beach", why_pl: "Długa, piaszczysta, tuż przy katedrze.", why_en: "Long sandy beach by the cathedral.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Katedra i centro storico", name_en: "Cathedral & old centre", why_pl: "Normański zabytek i wąskie uliczki.", why_en: "Norman cathedral and narrow lanes.", activity_slugs: ["old_towns", "castles"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Palermo (wycieczka)", name_en: "Palermo day trip", why_pl: "Markety, katedra i street food — pociąg lub auto.", why_en: "Markets, cathedral and street food — train or car.", activity_slugs: ["old_towns", "museums"], rank: 1 },
    ],
  },
  {
    id: "it-sardinia-costa-smeralda",
    destination_keys: ["sardynia", "sardinia", "costa smeralda", "olbia", "porto cervo", "arzachena"],
    slug: "sardinia-costa-smeralda",
    name_pl: "Costa Smeralda",
    name_en: "Costa Smeralda",
    character: "resort",
    vibe: "popular",
    overview_pl: "Szmaragdowe wody północy — luksusowe bazy i dzikie zatoczki.",
    overview_en: "Emerald north-coast water — upscale bases and wild coves.",
    stay_hint_pl: "Olbia lotnisko + wynajem auta — bazy w Arzachena / Palau.",
    stay_hint_en: "Olbia airport + car — bases in Arzachena / Palau.",
    center_lat: 41.08,
    center_lon: 9.5,
    picks: [
      { day_theme: "beach_relax", name_pl: "Spiaggia del Principe", name_en: "Prince's Beach", why_pl: "Turkus i biały piasek — symbol Costa Smeralda.", why_en: "Turquoise and white sand — Costa Smeralda icon.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "La Maddalena (archipelag)", name_en: "La Maddalena archipelago", why_pl: "Rejs łodzią po parku morskim — dzikie plaże.", why_en: "Boat tour in marine park — wild beaches.", activity_slugs: ["boat_tour", "rocky_beaches"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Snorkeling Capo Testa", name_en: "Capo Testa snorkel", why_pl: "Granitowe formacje i czysta woda.", why_en: "Granite formations and clear water.", activity_slugs: ["snorkeling"], rank: 1 },
    ],
  },
  // --- Francja ---
  {
    id: "fr-nice-riviera",
    destination_keys: ["nicea", "nice", "cote d azur", "riviera", "villeneuve loubet"],
    slug: "nice-riviera",
    name_pl: "Nice i Lazurowe Wybrzeże",
    name_en: "Nice & French Riviera",
    character: "mixed",
    vibe: "popular",
    overview_pl: "Promenada Anglais, stare miasto i Monaco w zasięgu pociągu.",
    overview_en: "Promenade des Anglais, old town and Monaco by train.",
    stay_hint_pl: "Nice centrum — tramwaj do plaży, pociąg do Monaco/Antibes.",
    stay_hint_en: "Central Nice — tram to beach, train to Monaco/Antibes.",
    center_lat: 43.71,
    center_lon: 7.26,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plage publique Nice", name_en: "Nice public beaches", why_pl: "Kamieniste zejścia — leżaki i kąpiel w centrum.", why_en: "Pebble beaches — sunbeds and swim in centre.", activity_slugs: ["rocky_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Vieux Nice i Cours Saleya", name_en: "Old Nice & Cours Saleya", why_pl: "Targ kwiatów, uliczki i socca.", why_en: "Flower market, lanes and socca.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Monaco / Eze (wycieczka)", name_en: "Monaco / Èze day trip", why_pl: "Księstwo i średniowieczna wioska nad morzem.", why_en: "Principality and medieval hill village.", activity_slugs: ["old_towns", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "fr-corsica-ajaccio",
    destination_keys: ["korsyka", "corsica", "ajaccio", "porto vecchio", "bonifacio"],
    slug: "corsica-south",
    name_pl: "Ajaccio i południe Korsyki",
    name_en: "Ajaccio & south Corsica",
    character: "wild",
    vibe: "balanced",
    overview_pl: "Dzika wyspa Francji — klify Bonifacio, plaże Palombaggia i szlaki GR20 (fragmenty).",
    overview_en: "France's wild island — Bonifacio cliffs, Palombaggia beaches, GR20 sections.",
    stay_hint_pl: "Ajaccio lub Porto-Vecchio — wynajem auta praktycznie konieczny.",
    stay_hint_en: "Ajaccio or Porto-Vecchio — car rental essential.",
    center_lat: 41.92,
    center_lon: 8.74,
    picks: [
      { day_theme: "beach_relax", name_pl: "Palombaggia", name_en: "Palombaggia beach", why_pl: "Biały piasek i sosnowy las — top plaża Korsyki.", why_en: "White sand and pine forest — Corsica's top beach.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "nature", name_pl: "Bonifacio — klify", name_en: "Bonifacio cliffs", why_pl: "Miasto na klifie i rejs po grotach.", why_en: "Clifftop town and cave boat tour.", activity_slugs: ["viewpoints", "boat_tour"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Szlak do Calanche de Piana", name_en: "Calanche de Piana trail", why_pl: "Czerwone skały UNESCO — wycieczka samochodem i krótki spacer.", why_en: "UNESCO red granite — drive and short walk.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
    ],
  },
  // --- Miasta (city break) ---
  {
    id: "it-rome-centre",
    destination_keys: ["rzym", "rome", "roma"],
    slug: "rome-centre",
    name_pl: "Rzym — centrum",
    name_en: "Rome centre",
    character: "historic",
    vibe: "popular",
    overview_pl: "Koloseum, Watykan i Trastevere — city break bez plaży, za to z historią.",
    overview_en: "Colosseum, Vatican and Trastevere — city break heavy on history.",
    stay_hint_pl: "Monti / Prati — blisko metra i głównych atrakcji.",
    stay_hint_en: "Monti / Prati — near metro and main sights.",
    center_lat: 41.89,
    center_lon: 12.49,
    picks: [
      { day_theme: "city_culture", name_pl: "Koloseum i Forum", name_en: "Colosseum & Forum", why_pl: "Rezerwuj skip-the-line — oszczędzisz godziny.", why_en: "Book skip-the-line — saves hours.", activity_slugs: ["archaeology", "old_towns"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Watykan i okolice", name_en: "Vatican area", why_pl: "Muzea i Plac św. Piotra — ubierz się skromnie.", why_en: "Museums and St Peter's — dress modestly.", activity_slugs: ["museums"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Trastevere wieczorem", name_en: "Trastevere evenings", why_pl: "Taverny i uliczki — kolacja po zwiedzaniu.", why_en: "Taverns and lanes — dinner after sightseeing.", activity_slugs: ["old_towns"], rank: 2 },
    ],
  },
  {
    id: "pt-lisbon-cascais",
    destination_keys: ["lizbona", "lisbon", "lisboa", "cascais", "sintra"],
    slug: "lisbon-coast",
    name_pl: "Lizbona i Cascais",
    name_en: "Lisbon & Cascais",
    character: "mixed",
    vibe: "balanced",
    overview_pl: " Alfama, tramwaje i plaże Estoril — city break z oceanem.",
    overview_en: "Alfama, trams and Estoril beaches — city break with ocean.",
    stay_hint_pl: "Baixa/Chiado na zwiedzanie, Cascais na dni nad morzem.",
    stay_hint_en: "Baixa/Chiado for sights, Cascais for sea days.",
    center_lat: 38.72,
    center_lon: -9.14,
    picks: [
      { day_theme: "city_culture", name_pl: "Alfama i Belém", name_en: "Alfama & Belém", why_pl: "Fado, pastel de nata i Wieża Belém.", why_en: "Fado, pastel de nata and Belém Tower.", activity_slugs: ["old_towns", "castles"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Cascais / Guincho", name_en: "Cascais / Guincho", why_pl: "Pociąg z Cais do Sodré — plaże zachodniego wybrzeża.", why_en: "Train from Cais do Sodré — west coast beaches.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "nature", name_pl: "Sintra (Pałace)", name_en: "Sintra palaces", why_pl: "Pena i Quinta da Regaleira — całodniowa wycieczka.", why_en: "Pena and Quinta da Regaleira — full-day trip.", activity_slugs: ["castles", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "cy-cyprus-general",
    destination_keys: ["cypr", "cyprus", "nikozja", "nicosia", "limassol", "larnaca"],
    slug: "cyprus-general",
    name_pl: "Cypr — wyspa (baza centralna)",
    name_en: "Cyprus — island overview",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "Gdy wybierasz cały Cypr — Limassol jako centrum, stąd Ayia Napa, Pafos i Troodos.",
    overview_en: "When you pick Cyprus as a whole — Limassol as hub, then Ayia Napa, Pafos and Troodos.",
    stay_hint_pl: "Limassol lub Larnaca — blisko lotnisk, łatwy dojazd w obie strony wyspy.",
    stay_hint_en: "Limassol or Larnaca — near airports, easy drives both ways.",
    center_lat: 34.68,
    center_lon: 33.04,
    picks: [
      { day_theme: "beach_relax", name_pl: "Plaże Limassol", name_en: "Limassol beaches", why_pl: "Długa promenada i piaszczyste odcinki — dobre na start.", why_en: "Long promenade and sandy stretches — good starting base.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Nikozja — stara część", name_en: "Nicosia old town", why_pl: "Jedyna stolica podzielona — muzea i uliczki.", why_en: "The divided capital — museums and lanes.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "nature", name_pl: "Troodos (góry)", name_en: "Troodos mountains", why_pl: "Szlaki i chłód w upalne dni — 1–2 h jazdy.", why_en: "Trails and cooler air on hot days — 1–2 h drive.", activity_slugs: ["hiking_trails", "viewpoints"], rank: 1 },
    ],
  },
  {
    id: "es-valencia-city",
    destination_keys: ["walencja", "valencia", "ciudad de las artes"],
    slug: "valencia-city",
    name_pl: "Walencja — miasto i plaża",
    name_en: "Valencia — city & beach",
    character: "mixed",
    vibe: "balanced",
    overview_pl: "City of Arts, stare miasto i Malvarrosa — city break z morzem.",
    overview_en: "City of Arts, old town and Malvarrosa — city break with sea.",
    stay_hint_pl: "Ruzafa / centrum na zwiedzanie, Cabanyal bliżej plaży.",
    stay_hint_en: "Ruzafa / centre for sights, Cabanyal near the beach.",
    center_lat: 39.47,
    center_lon: -0.38,
    picks: [
      { day_theme: "city_culture", name_pl: "Ciudad de las Artes", name_en: "City of Arts & Sciences", why_pl: "Oceanarium i futurystyczna architektura — dzieci to kochają.", why_en: "Aquarium and futuristic architecture — kids love it.", activity_slugs: ["aquarium", "museums"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Plaża Malvarrosa", name_en: "Malvarrosa beach", why_pl: "Miejska plaża z paellą na promenadzie.", why_en: "City beach with paella on the promenade.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Barrio del Carmen", name_en: "El Carmen quarter", why_pl: "Stare miasto, katedra i tapas.", why_en: "Old town, cathedral and tapas.", activity_slugs: ["old_towns"], rank: 2 },
    ],
  },
  {
    id: "it-venice-lagoon",
    destination_keys: ["wenecja", "venice", "venezia", "murano", "burano"],
    slug: "venice-lagoon",
    name_pl: "Wenecja i laguna",
    name_en: "Venice & lagoon",
    character: "historic",
    vibe: "popular",
    overview_pl: "Kanały, Piazza San Marco i wyspy szkła — city break bez aut.",
    overview_en: "Canals, St Mark's and glass islands — car-free city break.",
    stay_hint_pl: "Cannaregio / Castello — taniej i ciszej niż przy San Marco.",
    stay_hint_en: "Cannaregio / Castello — quieter and cheaper than San Marco.",
    center_lat: 45.44,
    center_lon: 12.32,
    picks: [
      { day_theme: "city_culture", name_pl: "San Marco i Pałac Dożów", name_en: "St Mark's & Doge's Palace", why_pl: "Rezerwuj rano — mniej tłumów przed południem.", why_en: "Book early morning — fewer crowds before noon.", activity_slugs: ["old_towns", "museums"], rank: 1 },
      { day_theme: "city_culture", name_pl: "Murano i Burano", name_en: "Murano & Burano", why_pl: "Wydmuchane szkło i kolorowe domki — vaporetto z Fondamente Nove.", why_en: "Glass blowing and colourful houses — vaporetto from Fondamente Nove.", activity_slugs: ["boat_tour", "old_towns"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Spacer po Dorsoduro", name_en: "Dorsoduro walk", why_pl: "Mosty, galerie i zachód słońca nad kanalem.", why_en: "Bridges, galleries and canal sunset.", activity_slugs: ["old_towns", "viewpoints"], rank: 2 },
    ],
  },
  {
    id: "es-gran-canaria-puerto-rico",
    destination_keys: ["gran canaria", "puerto rico", "mogan", "amadores"],
    slug: "gran-canaria-southwest",
    name_pl: "Puerto Rico i południowy zachód",
    name_en: "Puerto Rico & southwest",
    character: "resort",
    vibe: "balanced",
    overview_pl: "Marina, plaże Amadores i spokojniejsze zachodnie zachody słońca.",
    overview_en: "Marina, Amadores beaches and quieter west-coast sunsets.",
    stay_hint_pl: "Puerto de Mogán na klimat portowy, Puerto Rico na rodziny.",
    stay_hint_en: "Puerto de Mogán for harbour charm, Puerto Rico for families.",
    center_lat: 27.79,
    center_lon: -15.71,
    picks: [
      { day_theme: "beach_relax", name_pl: "Playa Amadores", name_en: "Amadores beach", why_pl: "Sztuczna zatoka z białym piaskiem — płytkie morze.", why_en: "Imported white sand cove — shallow sea.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "beach_relax", name_pl: "Puerto de Mogán", name_en: "Puerto de Mogán", why_pl: "„Mała Wenecja” — kanały i promenada.", why_en: "Little Venice — canals and promenade.", activity_slugs: ["old_towns", "sandy_beaches"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Delfiny / rejsy", name_en: "Dolphin cruises", why_pl: "Rejsy z południa wyspy — obserwacja delfinów (sezon).", why_en: "South coast cruises — dolphin spotting (seasonal).", activity_slugs: ["boat_tour"], rank: 1 },
    ],
  },
  {
    id: "es-fuerteventura-morro-jable",
    destination_keys: ["fuerteventura", "morro jable", "jandia", "costa calma"],
    slug: "fuerteventura-south",
    name_pl: "Morro Jable i Jandía",
    name_en: "Morro Jable & Jandía",
    character: "wild",
    vibe: "offbeat",
    overview_pl: "Najdłuższe plaże wyspy — wiatr, kite i pustynny krajobraz.",
    overview_en: "The island's longest beaches — wind, kite and desert scenery.",
    stay_hint_pl: "Morro Jable na południu — blisko Sotavento na kite.",
    stay_hint_en: "Morro Jable in the south — near Sotavento for kite.",
    center_lat: 28.05,
    center_lon: -14.35,
    picks: [
      { day_theme: "beach_relax", name_pl: "Playa de Sotavento", name_en: "Sotavento beach", why_pl: "Kilometry piasku — kite i laguny przy pływie.", why_en: "Miles of sand — kite and tidal lagoons.", activity_slugs: ["sandy_beaches"], rank: 1 },
      { day_theme: "nature", name_pl: "Park Jandía", name_en: "Jandía Natural Park", why_pl: "Pustynne wydmy i szlaki — wynajem auta.", why_en: "Desert dunes and trails — car rental.", activity_slugs: ["hiking_trails", "national_parks"], rank: 1 },
      { day_theme: "active_outdoor", name_pl: "Kitesurfing / windsurf", name_en: "Kite & windsurf", why_pl: "Sotavento — szkoły dla początkujących.", why_en: "Sotavento — schools for beginners.", activity_slugs: ["kayaking"], rank: 1 },
    ],
  },
];
